### ISSUE TITLE
[enhancement] Using web workers for barcode decoding

### ISSUE THREAD

**Issue by SunboX** [serratus/quaggaJS#1]
Would be nice if quaggaJS would support web workers for barcode decoding. So the UI keeps responding on lower end devices.

https://developer.mozilla.org/en-US/docs/Web/Guide/Performance/Using_web_workers

**Comment by serratus** [comment]
Finally, after multiple iterations of different approaches, I managed to find a good solution which works for most use-cases. If you are interested, take a look at the [issue-1a](https://github.com/serratus/quaggaJS/tree/issue-1a) branch. Feedback is greatly appreciated.

**Comment by serratus** [comment]
This issue should be solved with #12
