### ISSUE TITLE
Quagga.onDetected not called on multiple==true

### ISSUE THREAD

**Issue by JauernigIT** [serratus/quaggaJS#100]
I really don't know why, but... when I set `args.decoder.multiple: true` to detect multiple barcodes at once, the `Quagga.onDetected` event is not called on successful scans. 

In `function publishResult()` in quagga.js, `hasCodeResult(result)` is true on successful scans and `_commonEvents2['default'].publish("detected", resultToPublish);` is executed, but my onDetected callback is not hit. It seems that `_commonEvents2['default'].publish` isn't handling the callback, but it's a strange behavior...

If I set `args.decoder.multiple: false`, everything works fine and the `onDetected` callback is executed. The `onProcessed` callback is hit in both cases correctly...

**Comment by serratus** [comment]
Thanks for reporting this error. Are you experiencing this issue using a `LiveStream` or do you try to decode a static image?

**Comment by JauernigIT** [comment]
I'm using the live stream.

**Comment by serratus** [comment]
I've fixed the issue. Could you please try again?

**Comment by JauernigIT** [comment]
Yes, works. Thanks for the fast help!

**Comment by sceline** [comment]
Can either of you clarify if multiple property when set to true works with all barcodes in view. In my case i am trying to capture atleast 5 barcodes with multiple=true but i am seeing only one barcode in the resultCollector. Can someone help with this. I am trying to use quagga to scan code-128 and code-39. 

Its urgent . Please reply.

**Comment by sceline** [comment]
To add to the above comment, i am using quagga.min.js
