### ISSUE TITLE
drawRect() throws on locator.debug.showPatches==true

### ISSUE THREAD

**Issue by JauernigIT** [serratus/quaggaJS#103]
The title says it all... following [the documentation](https://github.com/serratus/quaggaJS/#locator) I wanted to activate the locator.debug options to show the located patches:

    locate: true,
    locator: {
        patchSize: "medium",
        halfSample: true,
        debug: {
            showCanvas: true,
            showPatches: true
        }
    }

Unfortunately, I get the following error in console output: `Uncaught TypeError: Cannot set property 'strokeStyle' of null` (`in drawRect <- boxFromPatches <- findBoxes <- locate <- getBoundingBoxes <- locateAndDecode`). Seems that the function parameter ctx as `_canvasContainer.ctx.binary` is undefined.

I'm using the current master commit ([117ab05](https://github.com/serratus/quaggaJS/commit/117ab05c09bb6759c237f3ce5ad262a97bae6438)).

Thanks in advance,
Matthias

**Comment by serratus** [comment]
As already pointed out in #96, make sure to not use web-workers. Due to a configuration-missmatch, you currently have to define `showCanvas` twice:
```javascript
{
locator: {
    showCanvas: true,
    debug: {
      showCanvas: true
    }
}
```

**Comment by JauernigIT** [comment]
Using the web worker was the problem, setting `numOfWorkers: 0` and your temporary config "hack" worked. Thanks so much!
