### ISSUE TITLE
After update to Version 0.10.0 page doesn't work anymore

### ISSUE THREAD

**Issue by sascha-hendel** [serratus/quaggaJS#105]
I updated my book label scan page from 0.9 to 0.10 (and changed facing attribute to facingMode), but Quagga doesn't work anymore (only displays video preview, but doesn't show green frames (detected barcodes))
Old stable version:
https://buch.archinform.net/service/scan.htm
New defunct version:
https://buch.archinform.net/service/scan2.htm

In Firefox 45 with Firebug two Javascript errors: "TypeError: h.debug is undefined"
In Chrome 49 two Javascript errors: "Uncaught TypeError: Cannot read property 'showCanvas' of undefined"

**Comment by serratus** [comment]
Thanks for reporting this issue. Unfortunately, this was caused by a misplaced debug statement and did not function correctly in the production version. Could you please try it again with the new version?

**Comment by sascha-hendel** [comment]
Wow, thanks for this highspeed fixing! New version works.
