### ISSUE TITLE
EAN-13 and UPCa barcode type are not working !

### ISSUE THREAD

**Issue by sidhesh333** [serratus/quaggaJS#107]
EAN-13 and UPCa barcode type are not working ! 
Whats "ean_reader" and "upc_reader" in decoder types ,initially i thought it will support complete EAN and UPC barcode types using above decoder type.Can u please suggest,how i can i read this above 2 types of barcode?

**Comment by serratus** [comment]
What do you mean by "not working"?
Please provide more information on how your setup looks like. Any console errors? Configuration? Live-Stream? Which barcodes should be decoded? UPC, EAN, UPC-E, EAN-8? 
As you can check in the [examples](https://serratus.github.io/quaggaJS/examples/static_images.html) they all do work.

**Comment by sidhesh333** [comment]
Hey thanks and sorry for late reply.

Its working fine for me now ,issue was in readers array there was syntax error ,my bad.

Last thing i wanted to know is ,is there any chance that CODE 93 barcode will be supported by this plugin in future ,or any way to accommodate same in this?

**Comment by serratus** [comment]
Good to know that you have resolved your error. Regarding the Code 93 barcodes: After a quick research it doesn't seem to be too much effort to put it into Quagga. I'll see what I can do. Maybe you could create a new issue and give it an `enhancement` label and provide some links/specs.

I'll close that issue since the original error was resolved

**Comment by saivipani** [comment]
@serratus , im not able to scan EAN 13 barcode using live web cam. im scanning the attached barcode using webcam. the code is logging a value in consule, but it is actually different. 
![whatsapp image 2018-10-15 at 8 59 16 pm](https://user-images.githubusercontent.com/44112693/46961403-51d3d180-d0be-11e8-8aab-dcd58ecc4a7e.jpeg)

consule log:
Barcode detected and processed : [11722423]

**Comment by ericblade** [comment]
@saivipani please open a new ticket, and provide your configuration details as well, thanks :)

**Comment by VeerneToor** [comment]
HI, I've a problem with QuagaJs.
I try decoder EAN13 but not work, this already solved?.

`<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <title>Barcode</title>
</head>
<style type="text/css">
#resultado{
  margin: 30px;
  border-radius: 3px;
  border: 1px solid black;
  font-size: 32px;
}
#camera{
  width: 50%;
  height: 50%;
}



</style>
<body>
  <div id="resultado"></div>
<div id="camera"></div>

  <script src="quagga.js"></script>

  <script>
    Quagga.init({
      inputStream: {
        name: "Live",
        type: "LiveStream",
        target: document.querySelector('#camera') // Or '#yourElement' (optional)
      },
      decoder: {
        readers: ["code_128_reader", "ean_5_reader","ean_8_reader", "ean_2_reader", "code_39_reader", "code_93_reader"]
      }
    }, function(err) {
      if (err) {
        console.log(err);
        return
      }
      console.log("Initialization finished. Ready to start");
      Quagga.start();
    });

    Quagga.onDetected(function(data){

console.log(data);

document.querySelector("#resultado").innerHTML = data.codeResult.code;

    });
  </script>
</body>

</html>
`

**Comment by ericblade** [comment]
well, you definitely don't have ean13 in your list there...

**Comment by EddWilly** [comment]
Hey so i try to read ean13 but i can't. ean8 works fine though. 
``` <script>
      Quagga.init(
        {
          inputStream: {
            name: "Live",
            type: "LiveStream",
            target: document.querySelector("#camera"), // Or '#yourElement' (optional)
          },
          decoder: {
            readers: ["ean_13_reader"],
          },
        },
        function (err) {
          if (err) {
            console.log(err);
            return;
          }
          console.log("Initialization finished. Ready to start");
          Quagga.start();
        }
      );

      Quagga.onDetected(function (data){
        console.log(data);
        document.getElementById('codigo').innerHTML = data.codeResult.code;
        alert(JSON.stringify(data));
      });
    </script>```

Am i listing it wrong or something?

**Comment by ericblade** [comment]
@EddWilly 

> readers: ["ean_13_reader"],

I believe you want 'ean_reader' there

**Comment by EddWilly** [comment]
Sure thing! Thank you

**Comment by Panchopipuchomelenuz** [comment]
Hi,

Any one can use EAN-13 and UPC barcode?

Can you tell me how can use this type of barcodes in the js, please?

Regards!!!

**Comment by ericblade** [comment]
```
                decoder: {
                    readers: ['upc_reader', 'ean_reader'],
                },
```

**Comment by Panchopipuchomelenuz** [comment]
@ericblade
Thanks for your answer. 

I just have to add at the end of the js file or do I have to remove the read_code_128 and replace it with this one?

Regards!!!
