### ISSUE TITLE
Development Mode

### ISSUE THREAD

**Issue by brendensoares** [serratus/quaggaJS#108]
How can I enable development mode so I can make use of the `#debug` element and see what features are being detected in the photos I am scanning?

I see:
```
        new webpack.DefinePlugin({
            ENV: require(path.join(__dirname, './env/', process.env.BUILD_ENV))
        })
```

but I am not familiar enough with node.js to know when/where I need to set the `BUILD_ENV`.

PS - I am using webpack in my own app, too.

**Comment by serratus** [comment]
Unfortunately there is a big hole in the documentation on that topic. Let me help you here really quick:
1. Build the library in `development` mode by running: `npm run build:dev`
2. Make sure you have a `#debug` element in the DOM
3. Adapt the configuration before initializing to the following values:
```javascript
state: {
    //....
    debug: true,
    locator: {
        patchSize: "medium",
        halfSample: true,
        debug: {
            showCanvas: true,
            showFoundPatches: true
        }
    },
}
```

This results in the following output:
![debug-mode](https://cloud.githubusercontent.com/assets/1381822/14997990/d9b4e340-1181-11e6-98d5-f8b7fb657e5f.PNG)

You can take a look into `src/config/config.dev.js` for all the available debug flags.
Hope that helps
