### ISSUE TITLE
Firefox - [ReferenceError: Quagga is not defined]

### ISSUE THREAD

**Issue by AlejandroPerezMartin** [serratus/quaggaJS#111]
Hello.

I'm using **Firefox 46.0.1** on **OS X 10.11.4** and I'm getting this error, both in my personal project and the official website example as shown in the screenshot.

I've also checked it with the same Firefox version on Windows and I get the same error:

<img width="1096" alt="screen shot 2016-05-19 at 00 19 14" src="https://cloud.githubusercontent.com/assets/5501685/15376766/62f53bb0-1d57-11e6-84da-78f7e24d0ebf.png">

Thanks!

**Comment by serratus** [comment]
That's an odd error. I've just tried to reproduce this error, but I cannot. I'm using OS X 10.11.4 and Firefox 46.0.1 and it looks like this:
![quaggajs__an_advanced_barcode-reader_written_in_javascript_and_coberhofer_christophs-macbook-pro-2____work_xxxl-is_ _-zsh_ _159x63](https://cloud.githubusercontent.com/assets/1381822/15666707/8ec7fe5c-2712-11e6-9199-4d75bbbcf887.png)

Can you try to open a new tab, open the console and type: `typeof mozRTCPeerConnection`. What's the output?
![new_tab](https://cloud.githubusercontent.com/assets/1381822/15666793/002b7916-2713-11e6-8a42-ca0ae2030f96.png)

**Comment by AlejandroPerezMartin** [comment]
Hello @serratus, I have checked it and I get "undefined" and had a search on Google and fixed it enabling **mozRTCPeerConnection** as it was disabled.

Thank you!

**Comment by serratus** [comment]
I'm glad it worked out. Just out of curiosity: was it disabled by default? Also on mobile?

**Comment by AlejandroPerezMartin** [comment]
No, I was using Firefox at work so they probably disabled it for some reason, but luckily it's not disabled by default

**Comment by serratus** [comment]
Alright, thanks for the info. Good to know 👍
