### ISSUE TITLE
MediaStreamTrack.getSources is deprecated.

### ISSUE THREAD

**Issue by sheam** [serratus/quaggaJS#113]
I keep getting the following error when initializing Quagga:

_MediaStreamTrack.getSources is deprecated. See https://www.chromestatus.com/feature/4765305641369600 for more details._

My config looks like this:

    {
        inputStream:
        {
            type: 'LiveStream',
            constraints:
            {
                width: 330,
                height: 240,
                facingMode: 'environment' // or user
            }
        },
        locator:
        {
            patchSize: 'medium',
            halfSample: true
        },
        numOfWorkers: 4,
        decoder:
        {
            readers: [ 'upc_reader' ]
        },
        locate: true
    };

Is this something I should be concerned about? I don't like warnings showing up in application that users might see.

**Comment by serratus** [comment]
This is not an error, but simply a warning. QuaggaJS is still using this *old* API because `facingMode` was not supported by Chrome until now. I have to check if this is still the case.

Thanks though for pointing that out, I'll investigate.

**Comment by serratus** [comment]
I've just updated to the latest version of [webrtc-adapter](https://github.com/webrtc/adapter) and removed `MediaStreamTrack.getSources`. Thanks for letting me know.
