### ISSUE TITLE
How to determine if device supports getMediaSources/aka live stream?

### ISSUE THREAD

**Issue by sheam** [serratus/quaggaJS#114]
Is there a way to detect if a device supports the live stream method? I would like to be able to detect this so that I can prove the static image functionality to those clients.

**Comment by nanoo-k** [comment]
From here: http://stackoverflow.com/questions/12885896/getusermedia-how-to-detect-if-the-device-actually-has-a-camera

...it's suggested...

> You can use MediaStreamTrack.getSources. This returns a list of video and audio devices connected to the PC. This does not require user permission.
> 
> You can then pass the ID to getUserMedia to get the desired media device.

I haven't tried it myself. Hope that helps.

**Comment by serratus** [comment]
QuaggaJS has a hard dependency on [webrtc-adapter](https://github.com/webrtc/adapter) and by using some kind of feature detection you could then decide which method to use:

```javascript
if (navigator.mediaDevices && typeof navigator.mediaDevices.getUserMedia === 'function') {
  // safely access `navigator.mediaDevices.getUserMedia`
}
```

After a quick check, the aforementioned condition returns:
- Microsoft Edge: `true`
- Chrome: `true`
- Firefox: `true`
- IE 11: `false`

Please close this issue if you got it working for you
