### ISSUE TITLE
Use of Promise not supported

### ISSUE THREAD

**Issue by pdorrestijn** [serratus/quaggaJS#115]
Hi,

IE11 does not support promises.
Should I include es6-promise to fix this?

**Comment by pdorrestijn** [comment]
update: I've added es6-promise.js to my page and the error is no longer logged.
However, I would have expected getUserMedia to work for IE11.
But it doesn't, how can I fix this?

**Comment by serratus** [comment]
Unfortunately IE11 does not support `getUserMedia` as documented here: https://github.com/serratus/quaggaJS#browser-support
