### ISSUE TITLE
Example of live camara is not working.

### ISSUE THREAD

**Issue by hanishmaram** [serratus/quaggaJS#116]
I used Android mobile device with chrome browser

**Comment by fatbearLTG** [comment]
I have also encountered the same problem.
The example in 'https://serratus.github.io/quaggaJS/v1.0.0-beta.1/examples/scan-to-input/' works OK.
But when I use follow that way in my own web, it will not work. 
It is interesting that my web will work on a PC Chrome browser, but not on an Android mobile device with chrome browser.
Maybe the "https"VS"http" settings?

**Comment by ErtugKaya** [comment]
I changed the following settings and it started to work on my LG G3 @ chrome.

width to 640px
height to 480px
aspect ratio: 4/3
device id: camera 0, facing back

**Comment by serratus** [comment]
First off, you have to use `https` if you are not working on `localhost` otherwise Chrome will refuse you to request the camera. I'll add that to the Readme ASAP.

**Comment by fatbearLTG** [comment]
Thanks all.
I finally works OK when I tried using https.

**Comment by github-ajay** [comment]
QuaggaJs is not working Code 39. Can you share me solution ASAP. Also it bar-code scanner gives some random number when I scan other products.
![7eea9eeb-1450-4bec-aee7-5487f5d3f958](https://user-images.githubusercontent.com/38049444/45502062-965b0d00-b7a0-11e8-9869-b8441a7311b2.jpg)

**Comment by ericblade** [comment]
Without seeing your configuration, there's not a lot we can suggest.

**Comment by github-ajay** [comment]
<!DOCTYPE html>
<html lang="en">

<head>
    <title></title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        /* In order to place the tracking correctly */
        canvas.drawing, canvas.drawingBuffer {
            position: absolute;
            left: 0;
            top: 0;
        }
    </style>
</head>

<body>
    
    <div id="scanner-container"></div>
    <input type="button" id="btn" value="Start/Stop the scanner" />


<script src="https://cdn.rawgit.com/serratus/quaggaJS/0420d5e0/dist/quagga.min.js"></script>

    <script>
        var _scannerIsRunning = false;

        function startScanner() {
            Quagga.init({
                inputStream: {
                    name: "Live",
                    type: "LiveStream",
                    target: document.querySelector('#scanner-container'),
                    constraints: {
                        width: 480,
                        height: 320,
                        facingMode: "environment"
                    },
                },
                decoder: {
                    readers: [
                        "code_128_reader",
                        "ean_reader",
                        "ean_8_reader",
                        "code_39_reader",
                        "code_39_vin_reader",
                        "codabar_reader",
                        "upc_reader",
                        "upc_e_reader",
                        "i2of5_reader"
                    ],
                    debug: {
                        showCanvas: true,
                        showPatches: true,
                        showFoundPatches: true,
                        showSkeleton: true,
                        showLabels: true,
                        showPatchLabels: true,
                        showRemainingPatchLabels: true,
                        boxFromPatches: {
                            showTransformed: true,
                            showTransformedBox: true,
                            showBB: true
                        }
                    }
                },

            }, function (err) {
                if (err) {
                    console.log(err);
                    return
                }

alert("Initialization finished. Ready to start");
                console.log("Initialization finished. Ready to start");
                Quagga.start();

                // Set flag to is running
                _scannerIsRunning = true;
            });

            Quagga.onProcessed(function (result) {
                var drawingCtx = Quagga.canvas.ctx.overlay,
                drawingCanvas = Quagga.canvas.dom.overlay;

                if (result) {
                    if (result.boxes) {
                        drawingCtx.clearRect(0, 0, parseInt(drawingCanvas.getAttribute("width")), parseInt(drawingCanvas.getAttribute("height")));
                        result.boxes.filter(function (box) {
                            return box !== result.box;
                        }).forEach(function (box) {
                            Quagga.ImageDebug.drawPath(box, { x: 0, y: 1 }, drawingCtx, { color: "green", lineWidth: 2 });
                        });
                    }

                    if (result.box) {
                        Quagga.ImageDebug.drawPath(result.box, { x: 0, y: 1 }, drawingCtx, { color: "#00F", lineWidth: 2 });
                    }

                    if (result.codeResult && result.codeResult.code) {
                        Quagga.ImageDebug.drawPath(result.line, { x: 'x', y: 'y' }, drawingCtx, { color: 'red', lineWidth: 3 });
                    }
                }
            });


            Quagga.onDetected(function (result) {
            var code_result=result.codeResult.code;
            if(code_result.length>8){
            alert("Barcode detected and processed : [" + result.codeResult.code + "]");
            }
               // console.log("Barcode detected and processed : [" + result.codeResult.code + "]", result);
            });
        }


        // Start/stop scanner
        document.getElementById("btn").addEventListener("click", function () {
            if (_scannerIsRunning) {
                Quagga.stop();
            } else {
                startScanner();
            }
        }, false);
    </script>
</body>

</html>


This is the complete file 
Also it take too much time to scan the barcode and give me some random numbers many times.

**Comment by ericblade** [comment]
My first thought on that, is that you should trim the "readers" section down to only the ones you need -- my nexus 5 runs pretty quickly only using the UPC and EAN readers in my application.  Having 9 decoders is going to lead to a ton of unnecessary CPU time. As well, you've got a lot of debug options on, and although I'm not familiar with the debug options, my guess is that it'd probably perform better with them off.  Definitely trim the list of readers down to only what you need, though.   If you have different situations where you need all 9 of them, maybe use different pages, or conditional initialization?

**Comment by abhimal** [comment]
why Quaggajs not working in my mobile browser using localhost

**Comment by lapalup** [comment]
> why Quaggajs not working in my mobile browser using localhost

Because you need HTTPS to access camera on safari and chrome.

**Comment by ericblade** [comment]
> why Quaggajs not working in my mobile browser using localhost

are you actually running a server on the phone?  if so, is it https ?
