### ISSUE TITLE
Source for v1.0.0-beta.1 example?

### ISSUE THREAD

**Issue by nanoo-k** [serratus/quaggaJS#123]
I'm wondering which tools you are using in the v1.0.0-beta.1 example [https://serratus.github.io/quaggaJS/v1.0.0-beta.1/examples/sandbox/].

It looks like you use react, v1.0.0-beta.1, and anything else? Would you be willing to make the source for that example available so I can see in detail what you do?

Also, a colleague of mine believes that the VIN reader (code_39) is more accurate than what we're using (v0.11.0). Since v0.11.0 is later than the beta example, is that even possible?

Thanks for your great tool, and sorry if this isn't the right medium for asking this question. I searched for another mode of contact on your site and didn't see one.

**Comment by serratus** [comment]
Hi there. Sorry, I totally messed up with the branching this time. I've created a new branch [1.0](https://github.com/serratus/quaggaJS/tree/1.0) and also published a beta release on npm and github under [v1.0.0-beta.1](https://github.com/serratus/quaggaJS/releases/tag/v1.0.0-beta.1)

Yes, for this example I use [react](), [material-ui] and the beta version of quagga with it's new API. This API is not yet documented, but you can scan through the [examples](https://github.com/serratus/quaggaJS/tree/1.0/example) and take a look yourself.

VIN reader? I haven't done any improvements over the last year. It never worked as I expected it to work. I'm still figuring out how to improve the overall quality of the reading/detection.

Hope that helps.

**Comment by nanoo-k** [comment]
Thanks for the links to `v1.0.0-beta.1` and to the examples. I see now that `v1.0.0-beta.1` actually is more recent, lol. Somehow I kept reading `v0.11.0` as `v1.11.0`.

I've selected tag `v1.0.0-beta.1` from the dropdown and it looks like I've found the beta example in the sandbox directory, thanks!

What sort of troubles are you currently having with the VIN reader? I'm not sure how much I'm capable of helping, but I have been put on the assignment of improving the tool if I can.

**Comment by serratus** [comment]
Is it OK for you if I close this issue? Please create another issue regarding your problems with the VIN reader. You could help by providing some sample images and barcodes. Usually the problem with VIN is the sheer length, and the massive amount of data cramped into it. Also the dimensions in general make it hard to find the barcode. It could help turning off the localization feature and try aligning it yourself.

**Comment by nanoo-k** [comment]
Oh absolutely, let's close this card. I'll open one specifically for the VIN reader and reprint what we've said here about it. Then I'll get to looking at it.
