### ISSUE TITLE
Chrome Warning: MediaStreamTrack.getSources is deprecated.

### ISSUE THREAD

**Issue by richbradshaw** [serratus/quaggaJS#124]
On Chrome 53, I'm seeing:

> MediaStreamTrack.getSources is deprecated. See https://www.chromestatus.com/feature/4765305641369600 for more details.

The link explains that:

> Remove support for the MediaStreamTrack.getSources() method. This method was removed from the spec in favor of MediaDevices.enumerateDevices().

I'm not sure if this is a find/replace change, or if it's more significant.

**Comment by TomasHubelbauer** [comment]
Same, I don't think this issue is still valid.

**Comment by ericblade** [comment]
Going ahead with closing.
