### ISSUE TITLE
Newest version ignores facingMode

### ISSUE THREAD

**Issue by slemrmartin** [serratus/quaggaJS#129]
Hi, 
I started implementation with version from 2016-04-19. I've set facingMode: "environment" and scanner is using rear camera.

When I replaced library with newer version, it is using front camera with same settings. 
So what's wrong?

**Comment by slemrmartin** [comment]
sorry it seams like duplicate of #128.
But I'm not sure, how to use this workaround you mentioned. 

Has the newer version significant benefits to replace old version?

**Comment by serratus** [comment]
Please continue the discussion in #128
