### ISSUE TITLE
Demo with file upload not working

### ISSUE THREAD

**Issue by adekock11** [serratus/quaggaJS#13]
I wanted to see a demo of QuaggaJS (http://serratus.github.io/quaggaJS/examples/file_input.html) but it doesn't work.

I am using FireFox and the error I am getting is "Error: invalid arguments" quagga.js:6718.

Is this an issue with QuaggaJS or something else?

Kind regards

**Comment by adekock11** [comment]
Never mind. This issue happens only when uploading PNG files :)

**Comment by serratus** [comment]
I'm glad you sorted that one out :-) But actually, the demo should work regardless of the image format used, whether it's JPG or PNG. Does your PNG file have some odd dimensions? Because I just tried it with PNG and it worked flawlessly.
