### ISSUE TITLE
i2of5_reader returns an Array of Boxes and no code result.

### ISSUE THREAD

**Issue by heath-the-monastery** [serratus/quaggaJS#139]
Object {boxes: Array[1]}
boxes
:
Array[1]
0
:
Array[4]
0
:
Array[2]
0
:
269.8982119733191
1
:
278.70339883941415
length
:
2
**proto**
:
Array[0]
1
:
Array[2]
0
:
282.59318291126874
1
:
179.79641961492143
length
:
2
**proto**
:
Array[0]
2
:
Array[2]
0
:
450.10176770562794
1
:
201.29658707019098
length
:
2
**proto**
:
Array[0]
3
:
Array[2]
0
:
437.4067967676783
1
:
300.2035662946837
length
:
2
**proto**
:
Array[0]
length
:
4
**proto**
:
Array[0]
length
:
1
**proto**
:
Array[0]
**proto**
:
Object

**Comment by Hongbo-Miao** [comment]
@heath-the-monastery can you let us know how you solve this? thanks
