### ISSUE TITLE
Quagga.decoder is not a function

### ISSUE THREAD

**Issue by ClickpointMechelen** [serratus/quaggaJS#143]
Im trying to implement the function on this page: https://serratus.github.io/quaggaJS/v1.0.0-beta.1/examples/scan-to-input/.

I used to code you showed on this page. But when I click the button the console shows: Quagga.decoder is not a function.
Any Idea what went wrong?

**Comment by hcvazquez** [comment]
Hello! Im the same problem. How do you fix it?

**Comment by Matoo125** [comment]
Hello I have the same problem. Any ideas? Using chrome 57

**Comment by Matoo125** [comment]
if I use script from example https://serratus.github.io/quaggaJS/v1.0.0-beta.1/examples/js/quagga.js I get Quagga.decoder(...).locator(...).fromImage is not a function

When I use script from bower installation I get  Quagga.decoder is not a function

**Comment by randal4** [comment]
I finally got this working after viewing the source on the page and discovering that the source they are using to actually render the page is different than the source they display at the bottom of the page.

If you use this version of quaggajs:
https://serratus.github.io/quaggaJS/v1.0.0-beta.1/examples/js/quagga.js

And this version of the example code (notice 'fromImage' displayed on the pages "sample code" is replaced by 'fromSource'):
https://serratus.github.io/quaggaJS/v1.0.0-beta.1/examples/file-input/index.js

it works.  I haven't compared the versions to figure out what actual build this is that actually works but hopefully this helps if someone else searches for this issue.
