### ISSUE TITLE
LiveStream behavior with pause() and start()

### ISSUE THREAD

**Issue by gelliott181** [serratus/quaggaJS#147]
I implemented the livestream and want to be able to pause and restart Quagga without reloading my page. Leaving Quagga running after I've accepted a code makes my UI very laggy on my target device (Low end android tablet with limited specs).

I call `Quagga.pause()` which seems to go normally, but then when I attempt to call `Quagga.start()` again Quagga throws an exception. I'm running Quagga in an Angular 2 component, so my workaround right now is to get rid of the entire component when scanning is done and then reinitialize every time I've finished processing the scanned code. This is not a good solution because Quagga then has to request permission to access the camera every time.

Error: 
```ORIGINAL EXCEPTION: _framegrabber is undefined```

Last few calls in the stack: 
```
update@https://cdnjs.cloudflare.com/ajax/libs/quagga/0.11.5/quagga.js:4244:14
frame@https://cdnjs.cloudflare.com/ajax/libs/quagga/0.11.5/quagga.js:4272:18
startContinuousUpdate@https://cdnjs.cloudflare.com/ajax/libs/quagga/0.11.5/quagga.js:4267:16
_start@https://cdnjs.cloudflare.com/ajax/libs/quagga/0.11.5/quagga.js:4281:10```

**Comment by gelliott181** [comment]
I've been working on a reproduction to see what causes this, and it seems related to using Angular's @ViewChild decorator to call functions inside the Quagga component. Calling `pause()` and `start()` in the component work just fine, but calling from the parent breaks things.

**Comment by eddyeHa** [comment]
Can you told me how you start using quaggaJS I dont understand... :(
