### ISSUE TITLE
file-input.html select issue

### ISSUE THREAD

**Issue by lightway28** [serratus/quaggaJS#148]
Hi, 
I have an issue with the select "Barcode-Type".
I want to select by default this:
<option value="ean">EAN</option>

![what-i-want](https://cloud.githubusercontent.com/assets/24432713/20966832/8d94dd52-bc7c-11e6-91dd-9d5d65baacff.jpg)

(by default code_128 is chosen)

I've tried different ways but nothing work.

I have to change manually to another option and then change again to <option value="ean">EAN</option> and then after I click the "Rerun button" it work great.

Here my trials but nothing work:
1) <option id="ean" value="ean" selected="selected">EAN</option>
2) $("#ean").prop('selected', true);
    or
    $("#ean").attr('selected', true);

Your project is great!
Can you help me?

**Comment by serratus** [comment]
I suppose you are using the provided examples. You need to change two things to make it work: 

First, set the `selected` attribute of the `<select>` box to __ean_reader__ in the `.html` file.

```html
<select name="decoder_readers">
    <option value="code_128">Code 128</option>
    <option value="ean" selected="selected">EAN</option>
</select>
```

Second, modify the `.js` file and set the config for `decoder.readers` to `'ean_reader'` like this:

```javascript
decoder: {
    readers: ['ean_reader']
},
```

Hope this works.

**Comment by lightway28** [comment]
Wow thank you!
It works great!
