### ISSUE TITLE
IE Desktop\Mobile does not Support Promise

### ISSUE THREAD

**Issue by allfa** [serratus/quaggaJS#156]
Im triing to use the beta version 1.0 and looks like Internet Explorer for both Desktop and Mobile cannot use Promises the [CanIUse](http://caniuse.com/promises/embed) suggests to use polyfill as replacement. but im not a JS is not my thing so just reporting it.

**Comment by serratus** [comment]
Polyfills for `Promises` are not included. A potential polyfill would be https://github.com/taylorhakes/promise-polyfill#downloads that you can simply include in your html file.

I suggest using Microsoft Edge, if you are locked in on Microsoft's browsers.
