### ISSUE TITLE
2D barcode scan

### ISSUE THREAD

**Issue by sinsar** [serratus/quaggaJS#16]
will this work for 2d barcodes(pdf417) i have been trying to scan a pdf417 barcode nothing happens in the browser can you please help me out. I have attached image for your reference iam using chrome on andriod mobile. when i click stop nothing happens.
![image1](https://cloud.githubusercontent.com/assets/11075834/6289267/e6d73ce2-b8ec-11e4-9b51-34453675fc84.JPG)

**Comment by serratus** [comment]
Sorry, 2D barcode decoding is not yet implemented. Currently Code128 and EAN are the only options available. In the near future, a few more one-d barcodes will be supported.

2D barcodes are further down the roadmap and will require quite some effort. Maybe someone in the community can help out.

**Comment by smunet** [comment]
thank you for your quick response. can you please point me to something when i can decode 2d barcodes or can you please help me in getting the barcode image from the video stream so that i can pass the image to a barcode reader. your help is so much appreciated thank you

**Comment by serratus** [comment]
Sorry, I don't quite understand what your requirements are. Do you need it to run in a web-browser? You could try [zxing](https://github.com/zxing/zxing) for running it natively on your phone. But I don't know any implementation running in the browser.

**Comment by sinsar** [comment]
i am trying to run in a web browser. i am able to open camera take a snapshot from video and send the image to the server and passing that bitmap image to zxing barcoder reader But the problem is with the snapshot the images are not clear and  zxing reader cannot recognize the bitmap. can you suggest a way to fetch the barcode image out of the viedo stream?

**Comment by serratus** [comment]
One way to get clearer images is by using the html5 File-API and prompt the user to take a picture with his/her camera.

If you want to use `getUserMedia`, try to increase the resolution of the camera by setting the appropriate constraints. Take a look at [camera_access](https://github.com/serratus/quaggaJS/blob/master/src/camera_access.js) if you want to know how.

**Comment by sinsar** [comment]
i tried using this camera_access.js file in the application when i am trying to load it says define is not defined i am really new to javascript please help me

**Comment by sinsar** [comment]
i tried setting the below code for video but it stays the same can you please help 
                        video: {
                                    "mandatory": {
                                "minWidth": "1280",
                                "maxWidth": "1280",
                                "minHeight": "720",
                                "maxHeight": "720",
                                "minFrameRate": "30"
                            },
                            "optional": []
                        }

**Comment by serratus** [comment]
I've created a [gist](https://gist.github.com/serratus/71eeac7b216dd584186a) which demonstrates how to request the camera stream, including constraints (for Chrome only). Additionally, the video stream is copied to a canvas element which can then be used to capture the frames. You can take a look at the canvas API [here](https://developer.mozilla.org/en/docs/Web/API/HTMLCanvasElement) where you can find the calls for your use-case (most probably `toDataURL()`)

**Comment by sinsar** [comment]
Thank you very much. Now i am able to get clear picture with resolution thank again you help me a lot

**Comment by jibin19** [comment]
@serratus , Does it support 2D barcodes now??
