### ISSUE TITLE
Live Stream leaves a black screen

### ISSUE THREAD

**Issue by ruskibenya** [serratus/quaggaJS#161]
I've incorporated Quaggajs successfully into my node project however after the scan is complete and Quagga.stop() is called a black screen fills the area of the scanner and doesn't close out. I am using the LiveStream function. Has anyone else had to deal with this problem?

Here is my code:

Index.html:

`                <section id="UPC Search">
                    <form id="form-search">
                      <button class="submit-button mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent">Scan barcode</button>
                      <input type="hidden" name="query" value=""/>
                      <div id="interactive" class="viewport"></div>
                    </form>  `

`               var $formSearch = $("#form-search");
                var $submitButton = $formSearch.find('.submit-button');

$submitButton.on('click', function(e){
                   e.preventDefault(); //prevent form submission
                   openReader();
                }); 

                $formSearch.submit(function(event) {
                    // cancel default behavior
                    event.preventDefault();

                    var query = $formSearch.find("input[name='query']").val();
                    console.log("index query value = "+ query);

                    $brand.html('');
                    $manufacturer.html('');
                    window.upcSearch.queryProducts(query, $brand, $manufacturer, $subsidies, $violations, $co_profile_description, $parentCo);

                }); `

BarcodeReader.js:

`function openReader(){
  Quagga.init({
    inputStream: {
        name: "Live",
        type: "LiveStream",
        constraints: {
            width: 640,
            height: 480,
            facingMode: "environment"
        }
    },
    locator: {
        patchSize: "medium",
        halfSample: true
    },
    numOfWorkers: 4,
    locate: true,
    decoder : {
        readers: ["upc_reader", "upc_e_reader"]
    }
}, function() {
    Quagga.start();
});

Quagga.onDetected(function(result) {
    var code = result.codeResult.code;
    console.log("The code is "+code);

    var $form = $("#form-search");

    $form.find("input[name='query']").val(code);
    Quagga.stop();
    $form.submit();
});
}
`

[https://github.com/ruskibenya/DolDem/tree/quaggajs](url)

**Comment by serratus** [comment]
Judging by your repository, you have solved the problem by a simple:
```javascript
$(".viewport").hide();
```

**Comment by shwetameta** [comment]
Hi,
I am still facing this issue of black screen display on Android mobile, chrome browser.
Camera shown for 1 second after that it goes black. 
On desktop it works fine.
Any help would be appreciated.
Thanks

**Comment by ericblade** [comment]
@shwetameta seeing some code would be helpful

**Comment by shwetameta** [comment]
> @shwetameta seeing some code would be helpful

I just run the below url, earlier it used to work on my Android >> Chrome browser but suddenly it started showing black screen.
https://serratus.github.io/quaggaJS/examples/live_w_locator.html

I also tried to run the code given in the link below:

https://ourcodeworld.com/articles/read/460/how-to-create-a-live-barcode-scanner-using-the-webcam-in-javascript

In this I tried to capture the error and it says : notreadableerror: could not start video source 

Thanks

**Comment by ericblade** [comment]
it does sound like some sort of a problem with the device not being able to start the camera, perhaps lack of camera permissions in Android Chrome?

**Comment by shwetameta** [comment]
> it does sound like some sort of a problem with the device not being able to start the camera, perhaps lack of camera permissions in Android Chrome?

It works in Edge browser of my mobile but not Chrome browser of same mobile. Earlier it used to work but suddenly stopped.
Camera permission is allowed. Camera is displayed for a second and then suddenly turns black.
Please help!!

**Comment by ericblade** [comment]
hmm.  difficult to debug without the device hooked up to chrome inspector, but my first thought would be to check Settings->Apps->Chrome->Permissions->Camera (something like that) to make sure that Chrome has access to the camera, then check inside Chrome's settings to make sure that the *pages* have permissions to use the camera as well, clear any caches, cookies, history, etc, and reboot the phone.    If that doesn't solve the problem, then I don't really know what to do -- connect your phone to Chrome Inspector on a PC and try to debug the page?

**Comment by shwetameta** [comment]
> hmm. difficult to debug without the device hooked up to chrome inspector, but my first thought would be to check Settings->Apps->Chrome->Permissions->Camera (something like that) to make sure that Chrome has access to the camera, then check inside Chrome's settings to make sure that the _pages_ have permissions to use the camera as well, clear any caches, cookies, history, etc, and reboot the phone. If that doesn't solve the problem, then I don't really know what to do -- connect your phone to Chrome Inspector on a PC and try to debug the page?

Hi,
Thanks for your help. I uninstalled last chrome updates and enabled chrome browser again under Settings -> Apps  and it started working again. Looks like there was some issue with last chrome update that was causing this.

**Comment by ericblade** [comment]
Are you using Android 11?  We're tracking some issues with Android 11 https://github.com/ericblade/quagga2/issues/266   What version of both Android and Chrome do you have?

**Comment by shwetameta** [comment]
Its. Android 10.

**Comment by ericblade** [comment]
Alright, well, if the issue comes back, I guess we'll do some more investigation, but if everything is fine now, i'm happy to leave it where it is 👍

**Comment by shwetameta** [comment]
Hi, 
I am facing a problem, where our client not able to scan the barcode from their Android >> chrome browser. It is Android version 10, phone, Samsung A71. Camera and the green focus box is displayed but not scanning at all.

It is scanning on client's iphone >> safari browser.
It is also scanning on my Android phone, Samsung G8.
Any help would be appreciated.

Thanks,
Shweta

**Comment by ericblade** [comment]
Check the console to see if there's any errors or other information available.

Make sure you're not using a camera that is a wide-angle lens (you may need to use enumerateDevices to get a list of camera ids, and figure out which one is which somehow, i do it via user input)

**Comment by shwetameta** [comment]
> Check the console to see if there's any errors or other information available.
> 
> Make sure you're not using a camera that is a wide-angle lens (you may need to use enumerateDevices to get a list of camera ids, and figure out which one is which somehow, i do it via user input)

Thank you for the reply.
I found out that, there are 2 back camera's detected:
1. camera 2 2,facing back
2. camera 2 0, facing back

If I select option 2, it scans properly. But option 1 is set as default, how do I change so that option 2 i.e. camera 2 0, facing back.
I tried setting it, the value is set but camera still shows that of option 1.

Thanks

**Comment by ericblade** [comment]
I use this for my constraints block to specify camera

```
                constraints: {
                    width: 640,
                    height: 480,
                    ...(cameraId && { deviceId: cameraId }),
                    ...(!cameraId && { facingMode: 'environment' }),
                },
```

if cameraId is not falsy, then use deviceId: cameraId, otherwise use the (i believe deprecated, but still working) facingMode: 'environment' constraint

I do wonder if it would be possible to specify constraints such as aspect ratio, as required elements, to automatically prevent the wide-angle lenses from being used.  I do not know what numbers would need to be plugged in to do that, though.

**Comment by shwetameta** [comment]
I solved it by setting the desired value via jquery and triggering the change event.

Thanks

**Comment by PriyaN-d** [comment]
Hi @shwetameta ,

Could you please help me on how you resolved it. I am facing the issue(playing video stream when I click on scan button and if I close the popup then the value is getting bind to Input field) issue is on IOS device. 

Regards,
Priya

**Comment by ericblade** [comment]
That sounds like a lot of issue in the app
