### ISSUE TITLE
 Blob is not defined

### ISSUE THREAD

**Issue by dipakdeshmukh-tudip** [serratus/quaggaJS#166]
I am using method decodeSingle to read a barcode image from file system.
But getting error on cancel as :

\node_modules\quagga\lib\quagga.js:4845
    blob = new Blob(['(' + workerInterface.toString() + ')(' + factorySource + '
);'], { type: 'text/javascript' });
               ^

ReferenceError: Blob is not defined

**Comment by saiaman** [comment]
What was the problem ?

**Comment by sunnykeerthi** [comment]
Hey @dipakdeshmukh-tudip I know it is an age old post. I'm facing this issue now. Can you please shower some light here?

Thanks
