### ISSUE TITLE
webrtc-adapter dependency is outdated

### ISSUE THREAD

**Issue by nicolashenry** [serratus/quaggaJS#167]
Can you update the "webrtc-adapter" dependency ? The latest version is "3.1.6" but quagga has a hard dependency on "2.0.2". Note that I would rather have a quagga file which do not include "webrtc-adapter" and add it myself in my projects.

**Comment by serratus** [comment]
Thanks for pointing that out. I'm currently in the progress of updating all outdated dependencies. Actually, thinking about it, you are right. I could just remove the `webrtc-adapter` and point the users to it if they want to use it. Nevertheless, it's just a polyfill. I'll consider doing that with a potential 0.12 release.
