### ISSUE TITLE
Angular 2/4 + Typescript + SystemJS how-to

### ISSUE THREAD

**Issue by 3Pi** [serratus/quaggaJS#173]
Good news, there is a typescript definition file in the project !

The problem is that I cannot figure out how to use in in my Angular 4 project...

Is there a way to use the typescript 'import way' and get both typing definitions and trigger 'quagga.min.js' loading and so have Quagga instantiated in my app ?
(Typescript finds the definitions, maybe not up-to-date with version 2.2.1 according to the errors I get)

I tried to fool SystemJS to point the right fights to load, with no good result.

Do I miss something ?
Is that possible at the moment to get QuaggaJS run in my Angular project.
Is there a least a tricky way to achieve this ?

**Comment by mhadaily** [comment]
Well, regarding your question: "Is that possible at the moment to get QuaggaJS run in my Angular project."

I have used it and just upgraded to angular4 and it's working perfectly. Here is the link: https://github.com/mhadaily/ng2-barcode-validator

I made it with a promise based service as well as reactive approach. 
Hope it can help you.

**Comment by 3Pi** [comment]
Thank you Majid, for your input.
It is good know that you managed to use QuaggaJS in your MAterial / Angular 4 project.

I do import Quagga in my component (import Quagga from 'quagga';)
I tried to load different version in my system.config.js file ;
- lib/quagga.js : many missing files try to be loaded (and I cannot find the way to solve all of them, I am not even sure that's a good idea)
- dist/quagga.js, dist/quagga.min.js : I get an error (Cannot read property 'init' of undefined) when trying to use Quagga

I didn't find out in you Github project how you did solve these questions ?

Maybe you have some hints to help ?

Thanks again.

**Comment by mhadaily** [comment]
@3Pi 
are you using "version": "0.11.6" ?

**Comment by 3Pi** [comment]
Yes, I did use 0.11.6 version, either by importing in :
- my main html file : <script src="https://cdnjs.cloudflare.com/ajax/libs/quagga/0.11.6/quagga.min.js"></script>
- my system.config.js file : System.import('npm:quagga/dist/quagga.min.js');

If I use /// <reference path="../node_modules/quagga/type-definitions/quagga.d.ts"/> , then TS Compiler does not find 'Quagga.' and it ends in a 'Cannot read property 'setAttribute' of undefined'(when createLiveStream is called on Quagga init.

If I use 'import Quagga from 'quagga';', typings are OK, but I get a 'Cannot read property 'init' of undefined' at runtime when trying to init Quagga (Quagga form libray is not boung to my Quagga object).

I suspect that there is something tricky (read - that I do not know or understand- ) in the the exports of QuaggaJS...

The problem is you found out a way to use the library in you project but I do not understand how !!!

**Comment by mhadaily** [comment]
Can you reproduce only this error in a repo and let me check your code? I see no problem! I tested again... You can easily fork my project and use it if you like...

**Comment by 3Pi** [comment]
I made an extract of my project to reproduce my problem.

You may have a look on [https://github.com/3Pi/QuaggaTest](url)..

Thank you very much for your precious help !

**Comment by mhadaily** [comment]
Sorry, I couldn't get your repo to start. I recommend you to start building an app with Ng-CLI or at least follow the Quick start in Angular documentation website. 

However, I get this app to work for you in this repo https://github.com/mhadaily/ng4-Systemjs-Quagga.

**Comment by 3Pi** [comment]
Sorry for the delay; I am coding on my spare time and I been away till this evening...
Your repo helped me to find that I had to use : import * as Quagga from 'quagga';
The resulting problem is that there is no typing on Quagga.
I would need more understanding in Typescript to solve that.
I will use it without typings for the moment...

**Comment by mhadaily** [comment]
@3Pi I am happy that you could manage and got that to work. However, I would mention that you should consider this file and import Quagga here as well. https://github.com/mhadaily/ng4-Systemjs-Quagga/blob/master/src/systemjs.config.js

Good to see your problem was resolved. 

@serratus I think this issue can be closed.

**Comment by 3Pi** [comment]
Off course I imported Quagga in my systemjs.config.js !
I tried to change the types definition file, but I didn't manage to get typing work...

Maybe I will come back on that question later.

Thanks again, I close this thread...
