### ISSUE TITLE
Not decoding barcode.

### ISSUE THREAD

**Issue by sajeetharan** [serratus/quaggaJS#175]
I am trying to decode the bar code from a jpeg image. and my code is as follows,

 
```
Quagga.decodeSingle({
    src: "1.jpeg",
    numOfWorkers: 0,  // Needs to be 0 when used within node 
    inputStream: {
        size: 800  // restrict input-size to be 800px in width (long-side) 
    },
    decoder: {
        readers: ["code_128_reader","ean_reader"] // List of active readers 
    },
}, function(result) {
    if(result.codeResult) {
        console.log("result", result.codeResult.code);
    } else {
        console.log("not detected");
    }
});
```

**Output**

FrameGrabber {"videoSize":[2479,3508],"canvasSize":[565,800],"stepSize":[4.387610619469027,4.385],"size":[560,800],"topRight":{"x":0,"y":0}}
E:\QrCode\handler.js:22
    if(result.codeResult) {
             ^

TypeError: Cannot read property 'codeResult' of undefined
    at E:\QrCode\handler.js:22:14
    at Object.callback (E:\QrCode\node_modules\quagga\lib\quagga.js:4953:32)
    at Timeout._onTimeout (E:\QrCode\node_modules\quagga\lib\quagga.js:5397:30)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

**Attached Image**

![Uploading 1.png…]()

**Comment by mhadaily** [comment]
is your barcode one of these "code_128_reader","ean_reader" formats? 
I think you need to attached your jpg for more inspection.

**Comment by sajeetharan** [comment]
Added the attachment     
![ticket-2-page-001](https://cloud.githubusercontent.com/assets/4833351/24321367/6b4210d2-1170-11e7-81bc-0327f126e97e.jpg)

**Comment by mhadaily** [comment]
This format has not been supported. it's PDF417. All the formats of boarding pass barcode are not being supported see here https://en.wikipedia.org/wiki/Bar-coded_boarding_pass

here is the list of supported readers and barcodes:

> The most important property is readers which take an array of types of barcodes which should be decoded during the session. Possible values are:

> code_128_reader (default)
> ean_reader
> ean_8_reader
> code_39_reader
> code_39_vin_reader
> codabar_reader
> upc_reader
> upc_e_reader
> i2of5_reader

**Comment by serratus** [comment]
Thanks @mhadaily for clarifying this.

**Comment by TomasHubelbauer** [comment]
See #70 for PDF417 support status.
