### ISSUE TITLE
camera facing problem

### ISSUE THREAD

**Issue by sgtsgnt** [serratus/quaggaJS#177]
i use quaggaJS-v0.11.2-0 and chrome 55.0.2883.91 in ASUS Zenfone 2, the camera facing environment.
i use quaggaJS-v0.11.6-7 and chrome 55.0.2883.91 in ASUS Zenfone 2, the camera facing user.
i use quaggaJS-v0.11.2-0 and chrome 56.0.2924.87 in LG G3, the camera facing user.
i use quaggaJS-v0.11.6-7 and chrome 56.0.2924.87 in LG G3, the camera facing user.

so, i choose quaggaJS-v0.11.2-0 with my ASUS Zenfone 2, cause the camera facing environment.
the others are bug. please fix this. thank you.

**Comment by serratus** [comment]
Thanks for reporting this bug. Unfortunately, all the browsers behave differently on different devices. And it also depends from version to version which camera is being selected. The constraint-API is not yet fully specified on that topic.
I suggest you query all the cameras yourself by making use of `navigator.mediaDevices.enumerateDevices` and let the user decide.
