### ISSUE TITLE
Viedo and Canvas Rendering Issues

### ISSUE THREAD

**Issue by Naki21** [serratus/quaggaJS#185]
So I have been trying to implement the box outline/overlay when scanning for barcodes and I'm running a problem. The video and the canvas elements are rendering on top of one another so when I scan the outline boxes are being drawn in a box below the video element. I am wondering if there are ways to work around this in the config or if you may know a good trick to fixing this up in the css. I am using bootstrap in my application, I'm thinking this may have something to do with it. 

 I also was curious if the box drawing feature is supposed to be a build in function itself.  I am currently using the function that is used in the `live` example but from the documentation, it seemed like this functionality was built into the scanner itself. I wanted to know if I was missing something. I am using the package with npm to execute the functionality. Any help or insight would be greatly appreciated. Thanks!

**Comment by Naki21** [comment]
Fixed with proper CSS selection and rules

**Comment by qasimalbaqali** [comment]
@Naki21 Could you share the css you have used, would be really helpful :)
