### ISSUE TITLE
Support for QR code

### ISSUE THREAD

**Issue by g-p-g** [serratus/quaggaJS#2]
Are there any plans to support recognizing QR codes?

**Comment by gabrielfurini** [comment]
@serratus Are you still working on implementation of this feature?

**Comment by serratus** [comment]
Unfortunately this feature costs a lot of time I currently don't have. Sorry, I just don't want to promise anything.

**Comment by maxshuty** [comment]
@gabrielfurini Probably a little late. But anyway - I recently had to do an implementation of QuaggaJS and needed QR Code scanning functionality as well. What I did was add the ZXing library to my solution, which reads QR Codes (but ibviously not at all of the angles like QuaggaJS will). In the JavaScript I'm just checking if Quagga detects a barcode, and if not then go do an AJAX call and have ZXing do a lookup. It's not exactly the ideal solution, but works just fine.

**Comment by gabrielfurini** [comment]
It's never too late, @maxshuty! Thanks for sharing your experience and how you dealt with the problem. That's the spirit of open-source. Regards

**Comment by rugk** [comment]
@maxshuty And which QR code scanner do you use? Aka which JS-port of the ZXing library?

**Comment by maxshuty** [comment]
@rugk I used QuaggaJS and a port of ZXing for .NET

**Comment by brianwong3** [comment]
Might be a bit late, but just thought of contributing on my approach to this issue. I went through the codes and noticed that the @serratus had catered to allow for the codes to be extended with the concept of readers. 

I created a new reader just for qr codes and opted to use a port of the [jsqrcode](https://github.com/edi9999/jsqrcode) since the original version is no longer maintained.
[qr_code_reader.txt](https://github.com/serratus/quaggaJS/files/1164821/qr_code_reader.txt)

You will need to do 3 small changes to the existing libraries though. 
1) Add your new reader to the _READERS_ variable in barcode_decoder.js .

2) In barcode_decoder.js, you need to overload _decodePattern_ function in _tryDecode_ to pass in an extra parameter, the inputImageWrapper variable. 
`result = _barcodeReaders[i].decodePattern(barcodeLine.line, inputImageWrapper);`

3) In the jsqrcode library, the library grayscales the image passed in and you will need to remove that portion of code since ( I suspect that quagga already grayscales the image ) grayscaling a grayscaled image is a bad idea.

**Comment by mikemand** [comment]
@brianwong3 Could you tell us how you disabled grayscaling in `jsqrcode`? I found the spot that does the grayscaling (`node_modules/qrcode-reader/src/qrcode.js:116`), but I am unsure what I need to remove...

**Comment by brianwong3** [comment]
@mikemand , you can just change 
`var image = this.grayScaleToBitmap(this.grayscale(imageData));` to 
`var image = this.grayScaleToBitmap(imageData);`

**Comment by mikemand** [comment]
@brianwong3 Thank you!

**Comment by kaburkett** [comment]
@brianwong3 seems like a fix for this issue... if you added in the project and did a PR he would prob merge it

**Comment by brianwong3** [comment]
@kaburkett its not really an fix though especially since quagga was built for reading 1D barcodes. the fix is really just an extension of @serratus code structure.

**Comment by hfilipowicz** [comment]
@brianwong3 Sorry, but I'm afraid, I didn't get it. Could you explain a little bit detailed, what is to do , to include the QR-Reader into the Quagga jf file?

**Comment by centogram** [comment]
Thanks for providing a sample of this integration for QR.  When I sttempt myself I'm getting the error:

**Comment by centogram** [comment]
@brianwong3 Did you have to tweak the locator to locate the QR codes.  I'm finding it won't recognize the full patch?

**Comment by brianwong3** [comment]
@centogram, I didnt have to tweak the locator, but then again, my users are trained operators so it doesnt affect my project.

**Comment by cgonzalvo** [comment]
> Might be a bit late, but just thought of contributing on my approach to this issue. I went through the codes and noticed that the @serratus had catered to allow for the codes to be extended with the concept of readers.
> 
> I created a new reader just for qr codes and opted to use a port of the [jsqrcode](https://github.com/edi9999/jsqrcode) since the original version is no longer maintained.
> [qr_code_reader.txt](https://github.com/serratus/quaggaJS/files/1164821/qr_code_reader.txt)
> 
> You will need to do 3 small changes to the existing libraries though.
> 
> 1. Add your new reader to the _READERS_ variable in barcode_decoder.js .
> 2. In barcode_decoder.js, you need to overload _decodePattern_ function in _tryDecode_ to pass in an extra parameter, the inputImageWrapper variable.
>    `result = _barcodeReaders[i].decodePattern(barcodeLine.line, inputImageWrapper);`
> 3. In the jsqrcode library, the library grayscales the image passed in and you will need to remove that portion of code since ( I suspect that quagga already grayscales the image ) grayscaling a grayscaled image is a bad idea.
> 
> Note: I have only done some light testing so if it breaks for you, do inform me.

HI, how do you add new reader to READERS? can anyone explain? I new on JS. Thanks in advance

**Comment by caiotarifa** [comment]
@rinukkusu What exactly did you pack? Is it still necessary to edit an original library?

**Comment by rinukkusu** [comment]
@caiotarifa it's probably easier to just use https://github.com/zxing-js/library
