### ISSUE TITLE
Unable to play video stream. Is webcam working?

### ISSUE THREAD

**Issue by MonasteryJohn** [serratus/quaggaJS#205]
We're using Quagga in a responsive web application we've written, great library works really well on most devices. We are running into some issues on a few older android phones while trying to mess with LiveStream sources.  A few things are interesting about that, first if we run the examples we can get the phone camera to work as long as we don't move the resolution above 800. Secondly, in our app if we target the front camera instead of the back camera it works fine. In all other scenarios we get "Unable to play video stream. Is webcam working?"

There's nothing particularly unique about our init (which is where the error occurs) and we've tried numerous variations of it all to the same effect on that device (Note 3 Android 4.4.2). We have tried with the adapter.js plugin and without it as well and the effects are the same. On newer devices (Google Pixel) it seems to function just as we'd expect.

I'd appreciate any direction you might have on what is potentially causing this issue. Happy to provide any follow-on information you might require.

**Comment by MonasteryJohn** [comment]
I found the cause of this issue. Our Quagga init was burried inside of the result of another call to the getMedia

**Comment by SexyCrane** [comment]
It appears in my project too, I'm trying to resolve it. Do you Have any ideas? Thank you very much

**Comment by veiico** [comment]
Same issue of "Unable to play video stream. Is webcam working?". I have bare Quagga.init with bare configuration, onDetected and start methods (simple clean startup example). It works on laptop and S7, but on older devices gives this message.

P.S. Maybe this will help: I'm working on a React project, so Quagga is initialized inside React class methods (componentDidMount)

Any help would be appreciated :)

**Comment by veiico** [comment]
Update:

Got it working, issue was too big contraints width and height (i used them from window.offset, when switched for portrait, it showed that message). It would be great if this default message would be dismissed if native error message is present (i saw different native constraints error when i relaunched Quagga with setTimeout, while on first init it showed "unable to play" error without any pointers)
