### ISSUE TITLE
getUserMedia is not defined (Android/iOS)

### ISSUE THREAD

**Issue by reinerluke** [serratus/quaggaJS#215]
I have an Ionic 2( Based on Angular2+) App which uses QuaggaJS to Stream the Camera to my View (Div Container) like Snapchat to scan QR Codes. In the browser, it all works like a charm but, the moment it gets built as APK or IPA file I'm getting the Error.

## **Android:**
`chromium: [INFO:CONSOLE(76955)] "Error: getUserMedia is not defined"`

I used ADB and a Virutal Android Device to get the logcat output. Important Info: Yes I have all Permissions and yes my Device is **on Android 7.0** (because WebRTC is only supported on 5.0+)!
## **iOS:**
`Error: getUserMedia is not defined`

And yes I have **iOS 11 Beta 3** installed on my Device (because WebRTC is only supported on iOS 11)!
Here a picture of the error output on my mac (Sorry for the bad quality).

![ios error](https://user-images.githubusercontent.com/30616142/28816186-299600f0-76a4-11e7-8148-9c0167d39c3d.png)

## **Browser:**
Everything works perfekt!

## **Code Snippet:**
As you can see above the error it states

> ERRORINFO: SetUp QuaggaJS

This is a Console Output which is generated by myselfe to locate the error.
So the error must be here in this codesnippet:
```
   Quagga.init({
         inputStream : {
             name : "Live",
             type : "LiveStream",
             constraints: {
               width:  window.innerWidth,
               height: window.innerHeight,
               facingMode: "environment"
             },
             area: {
                top: "0%",
                right: "0%",
                left: "0%",
                bottom: "0%"
            },
           target: document.querySelector('#scanner')
         },
         locator: {
           patchSize: "medium",
           halfSample: true
         },
         numOfWorkers: (navigator.hardwareConcurrency ? navigator.hardwareConcurrency : 4),
         decoder : {
          readers: [ "code_128_reader",
                     "ean_reader",
                     "ean_8_reader",
                     "code_39_reader",
                     "code_39_vin_reader",
                     "codabar_reader",
                     "upc_reader",
                     "upc_e_reader",
                     "i2of5_reader" ],
         },
         locate: true
       }, function(err) {
           if (err) {
               console.error("ERRORINFO: SetUp von QuaggaJS");
               console.error(err);
               return
           }
           console.log("Initialization finished. Ready to start");
           Quagga.start();
       });

```
And for me it looks like the error gets triggered in this line:

`           target: document.querySelector('#scanner')`

#scanner is just an div container for the livestream (as I said it works in browser, but just if you wonder what scanner is):
```
<div id="scanner" ion-fixed class="scannerdiv">
</div>
```

## **What have I tried?**
As you mentioned in your documentary:

> Every browser seems to differently implement the mediaDevices.getUserMedia API. Therefore it's highly recommended to include webrtc-adapter in your project.

So I **installed it with npm**. 
But that didnt work, so after that I imported it directly in my index.html like this:

`  <script src="https://webrtc.github.io/adapter/adapter-latest.js"></script>`

Well that didnt work either. @serratus

**Comment by lukay97** [comment]
## **Update:**
I found out that in Browser it works with unsafe sites. You mentioned to always use https but for me it only works on unsafe sites?

**Also finally on Android it works too as APK (native App).**
Just be sure to enable origin in your App config.xml;

`<access origin="*" subdomains="true" />`

But on iOS it still doesnt work in Browser and as Native App (iOS 11 Beta 3)

**Comment by lukay97** [comment]
## **Update:**
I found out that on **iOS it doesnt have premissions** for the camera. Well I set the premissions in code and on Android it works but it seems on iOS I must **call the premissions in lifetime** to ask the user to access the camera. 

So I'm searching for a **Ionic/Cordova Plugin** which **ask users in lifetime to gain premissions** for Camera, Storage and Audio.
If that worked I'll post it here.

**Comment by ziaur-grmtech** [comment]
it work in Browser and  but  still doesnt work as Native App (iOS 11 Beta 7). Any update?

**Comment by Biglr** [comment]
@lukay97 have you found a fix for this?
I've been trying to get this working as well but to no avail...

**Comment by poliander** [comment]
I can confirm that Quagga definitely works on iOS11 (at least with WebRTC adapter.js included).

**Comment by reinerluke97** [comment]
@poliander Does it work for you in Browser only or in does it work in native iOS App too? 
How did you implement Adapter.js? Did you use ionic(typescript/angular)? Explain it a little more because for me it only works on in Browser but not as Native App.

**Comment by poliander** [comment]
Tested with Safari on iOS 11, as a JS package bundled using webpack. This at least proves that QuaggaJS is able to access GetUserMedia API properly on this platform. I suppose your use case is not supported and since development has stalled, it probably never will be.

**Comment by ericblade** [comment]
Is this still an issue here? or is it a permissions level issue with iOS?

**Comment by jaan** [comment]
I see the same issue as mentioned in the description.
`Error: getUserMedia is not defined`

It works on safari on IOS but not on the webview in IOS app.

**Comment by reinerluke** [comment]
Still not supported from WebView in iOS Apps. 
I thought they would support it on iOS 11 and they did, but only for Safari Browser. Not WebViews. 

Maybe we will see some changes with iOS 12. 
But until then -> we have to wait.

**Comment by shankarlald** [comment]
any update on iOS???
now it's 13.3

**Comment by ericblade** [comment]
> any update on iOS???
> now it's 13.3

probably not likely to ever be included in anything but Safari.

**Comment by lreiner** [comment]
I did it once on safari but sadly I can remember anymore how I did it. Its 3 years ago. I only remember that it was very complicated to implement it.

**Comment by ericblade** [comment]
If you're loading a page in Safari, from a secure server, that includes Quagga, it should Just Work
