### ISSUE TITLE
Not working in mobile browsers

### ISSUE THREAD

**Issue by saravanasksp** [serratus/quaggaJS#217]
Not working in mobile browsers. Taking very long time to scan in desktop and also asking SSL to run in live. Do you have any idea about this.

**Comment by lukay97** [comment]
Same Problem

**Comment by aellis** [comment]
I am not on the dev team for this project, but a quick suggestion at least for the "not working" aspect - have you tried flipping your mobile device into a different orientation when taking the picture?  On my iPhone 6, nothing seemed to be working until I flipped the orientation to landscape and I started getting results.  May be a different problem you are having, but thought I'd throw it out there.

**Comment by eddyeHa** [comment]
aellis How do you work whit iPhone 6?

I had understood this library dosnt work whit IOS because of the getUserMedia...

So I really apreciate if you share whit me how do you put this work in your IOS system.

Thanks a lot.

**Comment by alexbaulch** [comment]
It seems to work with the iOS 11 beta, which has support for getUserMedia. Haven't done exhaustive testing but am able to access the camera.

**Comment by aellis** [comment]
@eddyeHa without digging into the prerequisites of jQuery and such, here is the very simplified version of what worked for me.  First here is the important HTML for static image upload:

```
<input type="file" id="imageLoader" name="imageLoader"/>
<canvas id="imageCanvas"></canvas>
```

Then you just need JavaScript to attach to this imageLoader and know to run QuaggaJS on it when a change occurs:

```
var imageLoader = document.getElementById('imageLoader');
    imageLoader.addEventListener('change', handleImage, false);

function handleImage(e){
    var reader = new FileReader();
    reader.onload = function(event){      
        Quagga.decodeSingle({
            decoder: {
                        readers: [
                            "code_128_reader",
                            "ean_reader",
                            "ean_8_reader",
                            "code_39_reader",
                            "code_39_vin_reader",
                            "codabar_reader",
                            "upc_reader",
                            "upc_e_reader",
                            "i2of5_reader"
                        ],
            },
            locate: true, // try to locate the barcode in the image
            src: (<any>event.target).result
        }, function(result){
            if(result.codeResult) {
               console.log(result.codeResult);
            } else {
              	console.log('not detected');
            }
        });
      
    }
    reader.readAsDataURL(e.target.files[0]);
}
```

Everything here just dumps out to console so it won't be obvious it did anything unless you pull that up.  Hope this helps!

**Comment by hendranata** [comment]
yes when i try https://serratus.github.io/quaggaJS/examples/live_w_locator.html yes working well.
but when try the example source code..it does not work on mobile phone.
anything missing?

**Comment by ericblade** [comment]
Running from a secure location is a requirement of getUserMedia these days.

**Comment by Jhuffare** [comment]
Quagg js works perfectly fine in Safari browser But when i am coming to chrome its showinf getUserMedia() is not defined

**Comment by ericblade** [comment]
@Jhuffare can you provide a screenshot and your chrome version?  are you using webrtc-adapter? navigator.getUserMedia() has been supported for quite a long time in Chrome, and as navigator.mediaDevices.getUserMedia() since at least 55.  I'm using 67 here.

**Comment by geersch** [comment]
@Jhuffare 

Apple released support for WebRTC / getUserMedia last year when they released iOS 11. It is only supported in Safari. The Chrome app is not actually the Chrome browser, but a wrapper around WKWebView. Unfortunately this functionality is not available in the WKWebView (or the old UIWebView), that's why you get the message "getUserMedia() is not defined.". You'll run into this anywhere where you try to use Quagga in a site which is displayed in-app via a web view.

This issue is known by Apple:

http://www.openradar.me/33571214

But no timeframe when it will be resolved. Tested this with iOS 11.4 and it's not supported yet.

**Comment by ericblade** [comment]
ah, yes, if it's iOS Chrome, then that's exactly it.
