### ISSUE TITLE
Scanner Not Scanning ON LG Devices - LG4 LG5 LG6

### ISSUE THREAD

**Issue by smithjosh5461** [serratus/quaggaJS#223]
The scanner cannot seem to focus on the lg devices. Found this issue on the LG4 and just replicated the issue on the LG6. Seems the phone has 2 lenses for the back facing camera and It cannot focus to scan a barcode is there any ways I can grab just one of those lenses for these devices?.

**Comment by ericblade** [comment]
@smithjosh5461 ever figure out anything related to this?

**Comment by smithjosh124** [comment]
@ericblade Unfortunately I have not!

**Comment by ericblade** [comment]
@smithjosh124 one of my testers pointed out to me that the G5 and G6 have multiple  rear facing cameras, and that it appears to default to using the wide angle. I haven't yet implemented a device enumeration function in my app to see if that helps, though.  G4 does not appear to share that trait, though.

**Comment by ericblade** [comment]
@smithjosh124 Quagga.CameraAccess.enumerateVideoDevices() on a G5 returns:

````
camera2 2, facing back
camera2 1, facing front
camera2 0, facing back
````

i haven't yet got the interface to actually switch cameras, but i should have that soon, and maybe can report if that fixes it at all

**Comment by ericblade** [comment]
@smithjosh124 "camera2 0, facing back" seems to autofocus if opened by specifying the deviceId for it.  I finally got to implementing camera selection for my app, and a G5 user has reported that it can now scan barcodes, with that camera device selected.

**Comment by ericblade** [comment]
This 100% fixes for G5 and G6, selecting the correct camera device.  I do not have a solution for G4, although I have tried requiring auto-focus in the constraints, that didn't seem to achieve anything, as well as forcing autoFocus on in the settings.  Perhaps if there's anyone else out there with a G4, we should file a separate ticket on that, although I don't know what the solution might be.
