### ISSUE TITLE
Live Mode Barcode (canvas.DrawingBuffer) Overlay Shows Below Camera/Video Frame

### ISSUE THREAD

**Issue by kenslachtajr** [serratus/quaggaJS#226]
Perhaps I am missing something basic, but I am having an issue where the video and canvas.DrawingBuffer are showing one above the over instead of one top of each other as I have seen in other examples. 
<img width="750" alt="screen shot 2017-09-19 at 4 11 20 pm" src="https://user-images.githubusercontent.com/1828602/30619619-377541cc-9d55-11e7-9791-43cdb38805de.png">
I believe this is a CSS issue, but is there a setting in the library to control the way those layers interact? I look forward to your response. Thanks!

**Comment by cweitat** [comment]
How did u solve this problem?

**Comment by agusdutra** [comment]
@kenslachtajr I'm facing this issue, can you tell us how did you solved it? thanks

**Comment by alyuekse** [comment]
Could you please tell us the solution?

**Comment by agusdutra** [comment]
I've managed to fix this issue by defining the video and canvas tags inside the div which is set as target and adding css to style the canvas.

```
    <div id="interactive" class="viewport">
      <video class="videoCamera" autoplay="true" preload="auto" src="" muted="true"
             playsinline="true"></video>
      <canvas class="drawingBuffer"></canvas>
    </div>

```


CSS


```
.drawingBuffer {
  position: absolute;
  top: 0;
  left: 0;
}

```

**Comment by rajutanniru44** [comment]
update the below code in onProcessed block 
Quagga.onProcessed(result => {
      const drawingCanvas = Quagga.canvas.dom.overlay;
      drawingCanvas.style.display = 'none';
    });

**Comment by camp0sfer** [comment]
> I've managed to workaround this issue by defining the video and canvas tags inside the div which is set as target and adding css to style the canvas.
> 
> ```
>     <div id="interactive" class="viewport">
>       <video class="videoCamera" autoplay="true" preload="auto" src="" muted="true"
>              playsinline="true"></video>
>       <canvas class="drawingBuffer"></canvas>
>     </div>
> ```
> 
> CSS
> 
> ```
> .drawingBuffer {
>   position: absolute;
>   top: 0;
>   left: 0;
> }
> ```

Maybe I am missing something, when I use this solution my video doesn't apper. :( Can someone help our post other solution?

**Comment by lina-is-here** [comment]
hi, I had this problem too, because I missed the CSS from the example (https://github.com/serratus/quaggaJS/blob/master/example/live_w_locator.html#L12).

@camp0sfer for this workaround to work, you also need to add `position: relative` for the parent element. For example,
```
.viewport {
    position: relative;
}
```

I wrote about it here https://notes.lina-is-here.com/2022/01/12/css-position-absolute-relative-quaggajs.html
