### ISSUE TITLE
Bug a simple add library?

### ISSUE THREAD

**Issue by pkochubey** [serratus/quaggaJS#23]
I have simle html5 page:
```
<div class="form-group" style="text-align: center">
        <video id="video" width="320" height="240" autoplay></video>
        <canvas id="barcode" width="320" height="240" style="display:none"></canvas>
</div>
<script>
 this start of using video
</script>
```
I add library in head:
```
<script src="/Scripts/Libs/quagga.min.js" type="text/javascript"></script>
```

After adding the library I stopped working component video, just a black screen.

**Comment by serratus** [comment]
Please take a look at the examples available in [/examples](https://github.com/serratus/quaggaJS/tree/master/example) or open up the source code on the [examples](http://serratus.github.io/quaggaJS/examples/) page.

Nevertheless, the following code shows the most basic usage of quagga using a camera:
```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Example</title>
        <script src="../dist/quagga.min.js" type="text/javascript"></script>
        <script type="text/javascript">
            window.addEventListener("load", function() {
                Quagga.init({
                    inputStream: {
                        name: "Live",
                        type: "LiveStream"
                    },
                    decoder: {
                        readers: ["code_128_reader"]
                    }
                }, function() {
                    Quagga.start();
                });
                Quagga.onDetected(function(result) {
                    console.log(result.codeResult.code);
                });
            }, false);
        </script>
    </head>
    <body>
        <div id="interactive" class="viewport">
            <video id="video" width="320" height="240" autoplay></video>
        </div>
    </body>
</html>
```

**Comment by pkochubey** [comment]
Thank you, I saw examples.
Look, here's my example, and it works: https://jsfiddle.net/pkochubey/98sqs3oc/.
But if you insert QuaggaJS it no longer works: https://jsfiddle.net/pkochubey/qx8cw6ec/.

**Comment by serratus** [comment]
Can you explain what you are trying to do? Judging by your examples, you are simply trying to get the quagga working in jsfiddle, right? But when I look at your second link, you are requesting the camera stream outside of quagga, which is not the way it works. Quagga itself requests the camera if it is initialized to have a __LiveStream__ as an input (see example above).

Or try this adaption of your fiddle: https://jsfiddle.net/qx8cw6ec/1/

**Comment by pkochubey** [comment]
Ok. I understand.
