### ISSUE TITLE
Mobile device rotation causes failure to scan from live video...

### ISSUE THREAD

**Issue by Kujako** [serratus/quaggaJS#241]
When running on a mobile device, rotating it causes scanning to stop working. In the canvas where the camera feed is shown I can see the green scan boxes being drawn, but they are not over the actual barcodes. I think this has to do with the canvas not resizing on rotation, but I'm not seeing a good way to resize the canvas and reinstantiate QuaggaJS. Any ideas?

**Comment by poliander** [comment]
Do a Quagga.stop() when an orientationchange event happens. Problem here is that the video stream may physically change when orientation changes. I notices that the stream which was initialized with 480x640 in landscape suddenly flipped to 480x480 when changing to portraitorientation. Probably not easy fixable on Quagga side so just do a full stop (or restart...) somehow

**Comment by Kujako** [comment]
@poliander thanks for the response. Looks like I have it solved, I had to first call Quagga.stop() and then reinitialize it to get everything working, but that does the trick.

`function readDeviceOrientation() {                        
    if (Math.abs(window.orientation) === 90) {
        console.log('Landscape');
    } else {
        console.log('Portrait');
    }
    Quagga.stop();
    initQuagga();
}
window.onorientationchange = readDeviceOrientation;`

**Comment by poliander** [comment]
Then close this issue pls
