### ISSUE TITLE
Width and height constraint inverted in android chrome

### ISSUE THREAD

**Issue by agusdutra** [serratus/quaggaJS#245]
It's weird but I'm testing this library with a resized camera (wich is not working on iOS [(#244)](https://github.com/serratus/quaggaJS/issues/244)

I'm testing on an android device using chrome, and on a windows computer using also chrome, with a mobile view.

If i set the constraints: 
 ```
constraints: {
          width: 100,
          height: 300
        }
```

In the computer I get this: 

![lector-pc](https://user-images.githubusercontent.com/12460226/33737863-575ca5f2-db76-11e7-86b9-c268155430d9.png)

Which is the expected behaviuour, since it's height is bigger than the width. 
But when I open it on the android chrome I get: 

![lector-android](https://user-images.githubusercontent.com/12460226/33738053-ef4e4faa-db76-11e7-85bb-2e5fc4d958ee.jpg)

Same code for both. 

Don't know what is happening, and I don't know which is the correct approach for resizing, since this doesn't work on Safari and It has this behaviour on chrome for PC and Android.

**Comment by poliander** [comment]
Try including WebRTC adapter.js in your project

**Comment by agusdutra** [comment]
Thanks for the response.. it's a valid workaround, but I couldn't figure out why this issue is happening. 

Maybe it has something to do with the portrait mode and the init configuration when is mobile.

**Comment by poliander** [comment]
No, it's a known inconsistent behaviour of slightly different getUserMedia/MediaStream API implementations. Has nothing to do with Quagga JS.

**Comment by agusdutra** [comment]
Ok, thanks, I close this issue then and will try with your suggestion.

**Comment by geersch** [comment]
The suggested fix doesn't work for me, if I switch the constraints on landscape, Quagga won't even start.

**Comment by osieckiAdam** [comment]
Hey @geersch this is very old discussion but today I had exactly the same issue and I managed to solve it, so I will leave this for the potential future use. In my case changing aspectRatio helps, by default its 1:2, so I changed it to 1:100 and it looks correct now, see example configuration below:
```
inputStream: {
  type: "LiveStream",
  constraints: {
    facingMode: "environment",
    width: parseInt(elemWidth),
    aspectRatio: {min: 1, max: 100}
  },
  target: elem
}
```

**Comment by ericblade** [comment]
FWIW, if you ask for an aspectRatio of 100 max on iOS, you'll get it, and nothing will be right. :-D
