### ISSUE TITLE
Reading barcode from file : result undefined

### ISSUE THREAD

**Issue by remi0411** [serratus/quaggaJS#249]
Hello,

I'm trying to read a barcode from an image (working via web demo), but when I'm trying to launch code on node js, i got "undefined" for the value of "Result"

`
var Quagga = require('quagga').default;

Quagga.decodeSingle({
    src: "qrcode128.png",
    numOfWorkers: 0,  // Needs to be 0 when used within node
    inputStream: {
        size: 800  // restrict input-size to be 800px in width (long-side)
    },
    decoder: {
        readers: ["code_128_reader"] // List of active readers
    },
}, function(result) {
    console.log(result);        //result is undefined there
    if(result.codeResult) {
        console.log("result", result.codeResult.code);
    } else {
        console.log("not detected");
    }
});
`

thank you

**Comment by fanqisoft** [comment]
我遇到了相同的问题但不知道如何去解决它
