### ISSUE TITLE
Static Images Example Fails

### ISSUE THREAD

**Issue by BastardCode** [serratus/quaggaJS#25]
The static Images example fails silently. The dev console on Firefox reports
+ "Security Error: The operation is insecure" -  quagga.min.js:9:0
+ Unknown property '-moz-box-shadow'.  Declaration dropped.

On google chrome (version 41) I get..
+ "Uncaught SecurityError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data."
+ The value "device-width;" for key "width" is invalid, and has been ignored.
+ Error parsing a meta element's content: ';' is not a valid key-value pair separator. Please use ',' instead.

It seems to be related to running the examples locally (as well as my own code) because
the examples themselves work fine when running them from the browser here on github.

I'm working on an independent project for my employer in retail as a tech demo that could save us a significant amount of money in employee labor for an otherwise irritating and expensive (albeit simple) everyday task. I'm not a full time programmer but I'd gladly toss a twenty your way via paypal or what-have-you, if someone can fix this. Thanks.

**Comment by serratus** [comment]
This error is most probably caused by running the code directly from the file-system. Due to security-constrains on the canvas-object, it somehow does not allow certain operations when executing code directly from ``file:///``. Try serving the code through a webserver like apache/nxing/ngrok and check if it still fails.

**Comment by BastardCode** [comment]
Confirmed. Fails running from ZWAMP. Still getting the same error as before. "Invalid Argument."

**Comment by serratus** [comment]
But ``Invalid Argument`` is not the same error as before, or is it? This error is also caused if the images have really odd dimensions. Have you changed anything on the code side? Or the images?

**Comment by serratus** [comment]
It's just been too quiet...

**Comment by serratus** [comment]
@BastardCode thanks for considering QuaggaJS. Have you had success getting the examples to run in your environment?
