### ISSUE TITLE
mobile phone camera does not open for scanning barcode

### ISSUE THREAD

**Issue by hendranata** [serratus/quaggaJS#250]
helo
i download all your source code and open the example file
http://localhost/camera/serratus-quaggaJS-eff0c5a/example/live_w_locator.html
yes when i open from my laptop, it looks working..
however when i try to open from iphone browser. the camera does not show up. 
but when i try to open live example from https://serratus.github.io/quaggaJS/examples/live_w_locator.html , yes it works in my iphone.
is there anything missing?

**Comment by poliander** [comment]
Do you have WebRTC adapter.js included in your project?

**Comment by hendranata** [comment]
Solved after using https


Sent from Yahoo Mail for iPhone


On Friday, January 5, 2018, 4:07 PM, René Pollesch <notifications@github.com> wrote:


Do you have WebRTC adapter.js included in your project?

**Comment by poliander** [comment]
So what about closing this issue ;-)
