### ISSUE TITLE
Detection not working on iPhones (even on example page)

### ISSUE THREAD

**Issue by qdupendra** [serratus/quaggaJS#254]
Can't get any of the two iPhones to scan barcodes via live streaming option work. 
When accessing the example page, the console shows error: "Error: getUserMedia is not defined".
At the same time, It works as expected on my Android device. Please suggest me how I can make it work on iOS. Also, please let me know if there is any minimum OS version below which it will not work?

Console error: 
```
Error: getUserMedia is not defined
o — quagga.min.js:1:32721
o — quagga.min.js:1:38810
o
promiseReactionJob

```

**Comment by NessterGit** [comment]
Only works on Safari 11 and up
https://caniuse.com/#feat=stream

**Comment by qdupendra** [comment]
Ah ok. Thanks for the info.
