### ISSUE TITLE
Start/trigger an Angular function by scanning the barcode

### ISSUE THREAD

**Issue by yuvanesh10** [serratus/quaggaJS#257]
I am working on a project with Angular 4 as front end, Node as server and Arango as database. At the moment, the connection between Angular to database is working fine. I am able to get the documents from db using a button in Angular. But I like to start the process just by scanning a barcode instead of clicking a button.

I found quagga.js for scanner in browser. Now I would like to use the callback option in the barcode library.

quagga.js (I didn't add the complete code)
startScanner() {
this.barcode = '';
this.ref.detectChanges();

Quagga.onProcessed((result) => this.onProcessed(result));

Quagga.onDetected((result) => this.logCode(result));

Quagga.init(this.configQuagga, (err) => {
  if (err) {
    return console.log(err);
  }
  Quagga.start();
  console.log('Barcode: initialization finished. Ready to start');
});
}

I have an Angular function in the browser as follows. I am executing this function with help of a button on click in html file

app.component.ts

private apiUrl = 'http://192.000.00.000:8080/edge';
server_get(){
return this.http.get(this.apiUrl)
.map((res: Response) => res.json())
}

But I would like to execute the Angular function just by scanning the barcode. How can I do that?

**Comment by Eonasdan** [comment]
what's wrong with this?

    Quagga.onDetected(quaggaDetected);
   function quaggaDetected(data) { ... }

granted it's not AG but this works well for me in plain old javascript

**Comment by yuvanesh10** [comment]
@Eonasdan quagga works but i am trying to use callback..but there are no examples  to follow through..so i am just asking how are we supposed to execute
