### ISSUE TITLE
Codabar support

### ISSUE THREAD

**Issue by sylvar** [serratus/quaggaJS#26]
QuaggaJS would be useful for libraries (I mean book-lenders, not code resources!) if it supported the [Codabar symbology](http://www.barcodeisland.com/codabar.phtml). There is already web-based software for loaning books to borrowers, and integrating QuaggaJS could make any tablet with a webcam capable of being a checkout computer. Thanks!

**Comment by serratus** [comment]
Support for Codabar was just released with the merge of https://github.com/serratus/quaggaJS/pull/28
