### ISSUE TITLE
Problem with Chrome 64.0.3282.123

### ISSUE THREAD

**Issue by CarmineScala92** [serratus/quaggaJS#260]
Good Morning, quagga.js don't work with new version Google Chrome (64.0.3282.123).
This is the message that appears to me:
Unable to play video stream. Is webcam working?

In the example on-line => https://serratus.github.io/quaggaJS/examples/live_w_locator.html appear black screen.
There are no problems on explore and firefox.

Thanks for the support

**Comment by jimgray81** [comment]
I'm having similar issues; below is my timeline so it can be compared to Chrome Updates:

- Nov 10, 2017 Tested Solution to ensure it matched project requirements
- FEB  16, 2018 Noticed the "front/back" facing feature no longer worked in Boostrapped app in Silk Browser on Kindle Fire (only displayed front facing camera)
- FEB 26, 2018 both deployed app (IIS, viewed in Silk) showed default "grey crossed-out camera" icon where camera view would display.
- Checked in Chrome and its the same
- cleared cache, both Local Host and IIS deploy show grey camera in Chrome

**Silk** Broswer v59.3.1.3071.117.10
**Chrome** v64.0.3282.167 (Official Build) (64-bit)
   (no error displayed in Developer Tools Console)
**IE** v11.0.9.9600.18893 update v11.0.50(KB4056568) (does not display camera view at all)
   Error: 'Promise' is undefined @ Quagga.init(...

**Comment by jimgray81** [comment]
I wanted to add that my Phone device works fine with the below version:
Chrome 64.0.3282.137

front and back facing work fine as well.

**Comment by ericblade** [comment]
Works fine for current Chrome. I'm going to close.
