### ISSUE TITLE
CODE93 and EAN13 support for QuaggaJS

### ISSUE THREAD

**Issue by rohin-jain** [serratus/quaggaJS#265]
Can we decode CODE 93 and EAN13 format barcode scanning support in Quagga JS , because I am using QuaggaJS and other format I want is supported by Quagga and it is the best library I found for barcode decoding. But my essential requirement is CODE93 and EAN13.

**Comment by davetransom** [comment]
Both of those are available already - you need to set the `ean_reader` or `code_93_reader` in the config. 

See the [decoder](https://github.com/serratus/quaggaJS#decoder) documentation for details.

**Comment by ericblade** [comment]
increase resolution, improve lighting?

**Comment by jegjessing** [comment]
Like in small, medium, large? I've tried them all.
Lighting, I have of course tried that :-)

**Comment by ericblade** [comment]
These are supported and working, please reopen or file more specific issues if you have any more specific data :-)
