### ISSUE TITLE
is this project developing or dead?

### ISSUE THREAD

**Issue by kodermax** [serratus/quaggaJS#274]

**Comment by jampy** [comment]
No signs of the author since late 2017. 

Last tweets:

https://twitter.com/overaldi/status/872530304505970688?s=19

https://twitter.com/grazjs/status/917047722506543110?s=19

:-(

**Comment by ericblade** [comment]
hey @serratus are you still out there?

**Comment by radar1975** [comment]
By any chance, is there someone else taking the lead of this projet ?
There was 413 fork ... maybe someone is ready to take it over since this project has a lot of potential.

**Comment by TomasHubelbauer** [comment]
See #300.
