### ISSUE TITLE
Any chance to see example code

### ISSUE THREAD

**Issue by PanRada** [serratus/quaggaJS#276]
is any chance to see example code for 
https://serratus.github.io/quaggaJS/v1.0.0-beta.1/examples/sandbox/

**Comment by robertoltrocha** [comment]
Hi,
Thanks for your code. It's perfect for what I need.
But I can't see the code, as I need to make some adaptations. Is it possible to show the code without being minified? I installed npm and I can't see everything. I'm new to this system.

I appreciate the help.
