### ISSUE TITLE
How to get the active stream or video track?

### ISSUE THREAD

**Issue by nitinsbuzz** [serratus/quaggaJS#278]
How can i get the active video track? I would like to use the capabilities (torch and zoom functionalities) but i just cannot get access to the active stream or video track. 

Unfortunately, the function Quagga.CameraAccess.getActiveTrack() does not work.

(I am loading quagga.min.js in the browser.)

**Comment by nitinsbuzz** [comment]
Problem solved!

It is possible to get the stream (mediaStreamTrack) by getting the srcObject from the video element (document.getElementById(‘video-element’).srcObject). I can now switch on/off torch and control zoom while scanning a barcode but it seems i cannot configure torch and zoom at the same time using camera capabilities. But this is another problem.

**Comment by ericblade** [comment]
I can get through Quagga.CameraAccess...

**Comment by Maritims** [comment]
You have to run it within the callback method of Quagga.init or getActiveTrack() won't actually have anything to return thus resulting in undefined.

**Comment by nitinsbuzz** [comment]
It is possible to get the stream (mediaStreamTrack) by getting the srcObject from the video element (document.getElementById(‘video-element’).srcObject).
