### ISSUE TITLE
chrome doesn't Open quagga scanner.

### ISSUE THREAD

**Issue by yuvanesh10** [serratus/quaggaJS#284]
I am using android mobile with version 5.0
I have a browser application which uses scanner. Quagga library works fine when I use it with firefox but chrome doesn't support it. When I run..,this is what I get in console. 
How can I rectify this problem ?

**Error**
quagga.min.js:1 [Deprecation] getUserMedia() no longer works on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. 

inspection.component.ts:130 DOMException: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).

**Comment by ericblade** [comment]
You literally *must* be serving it from either localhost, or a https origin.  Only secure origins are allowed to access the camera, just like it says.  You can click the link in the error message for further information.

**Comment by yuvanesh10** [comment]
Yes..,I read the details given  in the link but there is no solution to it. Just some set of rules

**Comment by ericblade** [comment]
The solution is that your app must be served from a secure web server, or localhost.

**Comment by rodrigoords** [comment]
I have the same problem in my application, and it is on https provider when I try to use on android chrome browser got this error. 
App:
https://obaja-barcode.herokuapp.com/

**Comment by rodrigoords** [comment]
My bad, in android I was using url without https. It's working fine.

**Comment by ericblade** [comment]
Great :) Closing. :)

**Comment by ClaudiaGiv** [comment]
> You literally _must_ be serving it from either localhost, or a https origin. Only secure origins are allowed to access the camera, just like it says. You can click the link in the error message for further information.

This worked for me, I had the same problem. Thanks! 👍
