### ISSUE TITLE
decodeSingle: Failed to load resource (Safari, iOS 10.1)

### ISSUE THREAD

**Issue by geersch** [serratus/quaggaJS#306]
Hi,

On browsers that support `navigator.mediaDevices.getUserMedia()` I use a video input device (facingMode: environment). However on older browsers I fallback to HTML media capture.

```html
<input type="file" accept="image/*" capture="camera">
```

I bind to the `change` event of the input.

```javascript
var input = document.querySelector('input');
input.addEventListener('change',  processFile);
```

and when a picture is made I call:

```javascript
processFile = function (e) {
    var config = {
      inputStream: { size: 800 },
      src: URL.createObjectURL(e.target.files[0]),
      ...
    }
    Quagga.decodeSingle(config, function (result) { ... });

}
```

This works fine for most browsers, but on mobile Safari (iOS 10.1) I get the following exception:

```
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (blob:https://s.codepen.io/29ce6a7c-c266-4b39-8de2-9ec61cc38455, line 0)
```

I debugged Quagga to see what was going on and it goes wrong in the ```ImageLoader.load``` function. 

```javascript
...
for (i = 0; i < htmlImagesSrcArray.length; i++) {
     img = new Image();
    htmlImagesArray.addImage(img);
    addOnloadHandler(img, htmlImagesArray);
    img.src = htmlImagesSrcArray[i];
}
...
```

The assignment of `blob:`to `img.src` is what causes the exception.

I reproduced this case in a small codepen.

https://codepen.io/geersch/pen/rKrwEN?editors=1010#0

Here's another demo from MDN which does the same:

https://developer.mozilla.org/en-US/docs/Web/API/File/Using_files_from_web_applications#Example_Using_object_URLs_to_display_images

Also fails for me on iOS 10.1 Safari.

Also tested with iOS 10.3.2 and there it works fine. Looking at the support matrix, I would think it should work on ios 10.1 as well:

https://caniuse.com/#feat=webworkers,canvas,typedarrays,bloburls,blobbuilder

Anybody knows what is going on?

**Comment by geersch** [comment]
@ericblade : Unfortunately I can't share the code. It's a private repository. Did figure out what was causing my weird issue. Turned out that the iPad device I was testing on was running iOS 10.1 beta 1. Looked over that part, noticed it when I compared it to iOS 10.1 running on a simulator.

**Comment by ericblade** [comment]
well, i'd like to borrow the concept then, if/when I get to getting my application working in iOS :-) 

So, are you saying that it works in iOS 10.1 release, but not beta? or does it not work in the release as well?

**Comment by geersch** [comment]
Using the live camera feed (MediaDevices.getUserMedia) works fine on iOS 11+ in Safari, but not in-app when the site is loaded via a UIWebView / WKWebView. 
For lower versions of iOS you'll have to fallback to decoding the barcode via a static image. It worked fine for me on the final versions of iOS 10.3.2 (device) and iOS 10.1 (simulator). Only the iOS 10.1 beta 1 caused issues, so I'm just going to file that under "chasing a red herring".

**Comment by ericblade** [comment]
Frankly, I didn't even know you could use a input tag to grab from a camera, seems like an early html5 thing that got quickly outdated, maybe?  But if wrapping Quagga in something that does that would allow it to work in Chrome on iOS, to some degree, then that's really kind of huge.

That said, I think I'd like to keep this open for a little bit.  I'm going to be picking up a real iOS device this weekend, probably, and if it's got 10.1, or I can put 10.1 release on it before I put it into use, I can check it out

**Comment by geersch** [comment]
That works fine in Chrome on iOS or any other app that utilizes WKWebView (or UIWebView). 

Support is limited to mobile browsers, but that's OK as you don't really want it on desktop browsers.

* Safari and Chrome Mobile for iOS 6+
* Chrome Mobile for Android OS 3+
* Firefox Mobile for Android OS 3+
* Opera 16 for Android OS 3+

As far as I can find.

https://caniuse.com/#feat=html-media-capture
