### ISSUE TITLE
Scan speed is too fast

### ISSUE THREAD

**Issue by thaibinh1909** [serratus/quaggaJS#318]
Hello, I know this is not an issue but I just wonder if scan speed can be reduced a little bit?
It likes immediate scanning, continuously so I end up with a lot of same codes each scan, 3 or 4 same each time.
Regards,
Binh

**Comment by ericblade** [comment]
:-D There is a configuration option that you can use to slow down the scanning speed (it can be useful to adjust that lower to improve battery life on portable devices, however it will of course scan slower), also you could pause the scanning when you receive a code.

**Comment by thaibinh1909** [comment]
Thank you.
I just found the `frequency: 10,` set it to `1`.
