### ISSUE TITLE
Would like to pass aspectRatio (min and max) in to constraints

### ISSUE THREAD

**Issue by elsigh** [serratus/quaggaJS#32]
Happy to write this CL if you're open to it.

I was thinking of just setting min to 0 and max to 100 as defaults, and then passing in the normalized values in case the user adds those. (the way you do with 640, 480 and "environment")

**Comment by serratus** [comment]
I don't quite understand what you want to achieve with that?! And what do you mean with a min and max setting for the aspect ratio? Can you give me an example?

**Comment by elsigh** [comment]
I'm scanning a wide barcode (VIN) and a minAspectRatio of 5 will become a horizontal bar scanner instead of a square. 

Check out https://src.chromium.org/svn/trunk/src/chrome/test/data/webrtc/manual/constraints.html
Put in 50 for min height/width and 5 for minAspectRatio and 10 for maxAspectRatio and you'll see what I mean

**Comment by serratus** [comment]
Sorry, I didn't know that you were talking about the video-stream constraints. This basically allows you to get only a portion of the image. But if you do that, do you even need the localization part any more? Because if you restrict the camera to a certain image-size (say 50 x 300 px) you have to align the the barcode anyway.

**Comment by elsigh** [comment]
I figured aligning the barcode at least some (I'm not being quite as restrictive as 50x300) would make the detection faster and more efficient since I'm scanning horizontal barcodes instead of square codes.

It seems like it did make the detection faster to me on my phone anyway.

I like that I don't have to spend much time lining up the barcode so I figure I'm still benefiting from the localization.
