### ISSUE TITLE
Cannot read property 'setAttribute' of undefined at Object.o.createLiveStream

### ISSUE THREAD

**Issue by wordjelly** [serratus/quaggaJS#321]
Hi,
Configuration:
OS: Ubuntu 16.04
Chrome Version: 57.0.2987.133 unknown (64-bit)
Qagga(0.12.1) : Using [cdn](https://cdnjs.cloudflare.com/ajax/libs/quagga/0.12.1/quagga.min.js)
Javascript Code(from the documentation home page):

```
$(document).ready(function(){
    Quagga.init({
    inputStream : {
      name : "Live",
      type : "LiveStream",
      target: document.querySelector('#scanner-container')
    },
    decoder : {
      readers : ["code_128_reader"]
    }
  }, function(err) {
      if (err) {
          console.log(err);
          return
      }
      console.log("Initialization finished. Ready to start");
      Quagga.start();
  });    
})

```
Get the error:

```
Cannot read property 'setAttribute' of undefined at Object.o.createLiveStream
```

Same thing happens with Firefox as well, with an error: 

```
't' is undefined
```

Any help is appreciated , I cannot use the library at all at this point.
Calling the following in Chrome Console:

```
MediaDevices.getUserMedia
=> undefined
```

I don't know if that has something to do with it.

Look forward to some help.
Thanks,
Bhargav

**Comment by wordjelly** [comment]
If anyone comes across this problem, its because your target does not exist on the page, when Qagga is initialized. Solved that. Closing.

**Comment by balaji3027** [comment]
I have same problem occurs while using on salesforce. So how can i resolve it ?

**Comment by alekslario** [comment]
Basically, `navigator.mediaDevices.getUserMedia`, used by this lib,  works only through https. In development environment, If you are using web-dev-server, add `--https`. ¯\_(ツ)_/¯

**Comment by vidpotocnik** [comment]
This was really helpful! I've solved this problem by changing target querySelector to document.getElementById.

Regards.
