### ISSUE TITLE
Issue in draw box on the barcodes

### ISSUE THREAD

**Issue by SopraUser** [serratus/quaggaJS#326]
Hello,

It is scanning properly. but i am facing issue with drawing box on the bar-codes.
Below is the code snip 
<pre>
function startQuaggaJS(textBoxId,DivWidth, backCamID){
	
	Quagga.init({
	        inputStream: {
			    name: "Live",
	            type: "LiveStream",
	            target: document.querySelector('#video-container'),
	            constraints: {
	            	width: DivWidth,
	                height: 470,
	                facingMode: "environment"
	                ,deviceId: backCamID
	            },
	        },
        numOfWorkers:navigator.hardwareConcurrency,
	    locate: true,
        frequency: 1,
        debug: {
            drawBoundingBox: true,
            showFrequency: true,
            drawScanline: true,
            showPattern: true
        },
        multiple:false,
        locator: {
        	halfSample: false,
	      	  patchSize: "large", // x-small, small, medium, large, x-large
	      	  debug: {
	      	    showCanvas: false,
	      	    showPatches: false,
	      	    showFoundPatches: false,
	      	    showSkeleton: false,
	      	    showLabels: false,
	      	    showPatchLabels: false,
	      	    showRemainingPatchLabels: false,
	      	    boxFromPatches: {
	      	      showTransformed: false,
	      	      showTransformedBox: false,
	      	      showBB: false
	      	    }
	      	  }
        },
        decoder: {
            readers: [
                "code_128_reader",
                "ean_reader",
                "ean_8_reader",
                "code_39_reader",
                "code_39_vin_reader",
                "codabar_reader",
                "upc_reader",
                "upc_e_reader",
                "i2of5_reader"
            ]
        
        }
	}, function (err) {
        if (err) {
			alert("error name:-"+err.name + " & error message:-"+err.message);
        }
       
        Quagga.start();
    });	
	
	Quagga.onProcessed(function (result) {
        var drawingCtx = Quagga.canvas.ctx.overlay,
        drawingCanvas = Quagga.canvas.dom.overlay;

        if (result) {
            if (result.boxes) {
                drawingCtx.clearRect(0, 0, parseInt(drawingCanvas.getAttribute("width")), parseInt(drawingCanvas.getAttribute("height")));
                result.boxes.filter(function (box) {
                    return box !== result.box;
                }).forEach(function (box) {
                    Quagga.ImageDebug.drawPath(box, { x: 0, y: 1 }, drawingCtx, { color: "green", lineWidth: 2 });
                });
            }

            if (result.box) {
                Quagga.ImageDebug.drawPath(result.box, { x: 0, y: 1 }, drawingCtx, { color: "#00F", lineWidth: 2 });
            }

            if (result.codeResult && result.codeResult.code) {
                Quagga.ImageDebug.drawPath(result.line, { x: 'x', y: 'y' }, drawingCtx, { color: 'red', lineWidth: 3 });
            }
        }
    });

Quagga.onDetected(function(result) {
        
	var audio = new Audio('audio_file.mp3');
	audio.play();
	var code = result.codeResult.code;
	alert("Barcode Reader value : "+code);
	Quagga.stop();
        	 
});
}
</pre>
Thanks in advance.

**Comment by SopraUser** [comment]
Has anyone else had to deal with this problem?

**Comment by ericblade** [comment]
I seem to recall having quite a lot of trouble with trying to get drawing of scan area working, and just gave up.  Much of the time my phone has the scan completed and the barcode entered into the text input in my app before the camera is even visible on display . . so I just stopped trying to figure it out

**Comment by SopraUser** [comment]
Issue has been resolved. There is css missing for canvas.

**Comment by SopraUser** [comment]
<pre>
 <video id="video-container" playsinline autofocus autoplay ></video>
<canvas class="drawingBuffer"></canvas>
</pre>

for <i>drawingBuffer</i> i have missed css.
<pre>.drawingBuffer {
  position: absolute;
  top: 0;
  left: 0;
}</pre>

**Comment by ericblade** [comment]
Thanks! I'll have to revisit mine soon and see if that helps me fix it on mine :)

**Comment by TGRBTRFLY** [comment]
That didn't work for me. I think I need to try window.onload
