### ISSUE TITLE
IOS safari 11.4- Back camera opening issue

### ISSUE THREAD

**Issue by SopraUser** [serratus/quaggaJS#327]
Hi,
I am using quagga v0.12.1 and facing issue with ios safari.
No error is given by quagga but it is not opening back camera.
Same code is working fine with Android(Chrome, Firefox).
I am passing <b>Back Camera Id(backCamID)</b> for all version.
<pre>

var audio = new Audio('audio_file.mp3');

function startQuaggaJS(textBoxId,DivWidth, backCamID){
		
	Quagga.init({
	        inputStream: {
			    name: "Live",
	            type: "LiveStream"
	            ,target: document.querySelector('#video-container')
	            ,
	            constraints: {
	            	width: 640,
	                height: 480,
	                facingMode: "environment"
	                ,deviceId: backCamID
	            }
	        },
        //numOfWorkers: 2,
	    numOfWorkers:navigator.hardwareConcurrency,
	    //singleChannel: false, // true: only the red color-channel is read
        locate: true,
        frequency: 10,
        debug: {
            drawBoundingBox: true,
            showFrequency: true,
            drawScanline: true,
            showPattern: true
        },
        multiple:false,
        locator: {
        	halfSample: true,
	      	  patchSize: "large", // x-small, small, medium, large, x-large
	      	  debug: {
	      	    showCanvas: false,
	      	    showPatches: false,
	      	    showFoundPatches: false,
	      	    showSkeleton: false,
	      	    showLabels: false,
	      	    showPatchLabels: false,
	      	    showRemainingPatchLabels: false,
	      	    boxFromPatches: {
	      	      showTransformed: false,
	      	      showTransformedBox: false,
	      	      showBB: false
	      	    }
	      	  }
        },
        decoder: {
            readers: [
                "code_128_reader",
                "ean_reader",
                "ean_8_reader",
                "code_39_reader",
                "code_39_vin_reader",
                "codabar_reader",
                "upc_reader",
                "upc_e_reader",
                "i2of5_reader"
            ]
        //, multiple: false
        }
	}, function (err) {
        if (err) {
			alert("Quagga error name:-"+err.name + " & Quagga error message:-"+err.message);
			$('#ajax-modal-screen-for-barcodejs').modal('hide');
        }
        
        Quagga.start();
    });	
	
	Quagga.onProcessed(function (result) {
        var drawingCtx = Quagga.canvas.ctx.overlay,
        drawingCanvas = Quagga.canvas.dom.overlay;

        if (result) {
            if (result.boxes) {
                drawingCtx.clearRect(0, 0, parseInt(drawingCanvas.getAttribute("width")), parseInt(drawingCanvas.getAttribute("height")));
                
                result.boxes.filter(function (box) {
                    return box !== result.box;
                }).forEach(function (box) {
                    Quagga.ImageDebug.drawPath(box, { x: 0, y: 1 }, drawingCtx, { color: "green", lineWidth: 3 });
                });
            }

            if (result.box) {
                Quagga.ImageDebug.drawPath(result.box, { x: 0, y: 1 }, drawingCtx, { color: "#00F", lineWidth: 3 });
            }

            if (result.codeResult && result.codeResult.code) {
                Quagga.ImageDebug.drawPath(result.line, { x: 'x', y: 'y' }, drawingCtx, { color: 'red', lineWidth: 4 });
            }
        }
    });

Quagga.onDetected(function(result) {
        
        	audio.play();
        	var code = result.codeResult.code;
        	$("#"+textBoxId).val(code);
            Quagga.stop();
        	$('#ajax-modal-screen-for-barcodejs').modal('hide');
        
});
}
</pre>

**Comment by ericblade** [comment]
Can you provide the output of Quagga.CameraAccess.enumerateVideoDevices(), and validate that you are passing the correct thing to your Quagga init?

**Comment by SopraUser** [comment]
Sorry to say, but we have some constraints due to which we are not able to get the log.
We have some progress about camera opening. Now camera is opening, but every time it is opening front camera and after few second it is getting black. 

Has anyone else had to deal with this problem?

**Comment by ericblade** [comment]
If you're not able to see the console of what you're trying to work with, it's going to be pretty difficult to be able to figure out what's going on.

Good news, I just got a couple of iOS devices, although they are currently locked, and i'm not sure that they will be able to be unlocked.  If they are, though, then I'll be able to do some validation on iOS

**Comment by SopraUser** [comment]
now i have <b>Quagga.CameraAccess.enumerateVideoDevices()</b>. So @ericblade please share you views 

![screen shot 2018-09-27 at 5 00 05 pm](https://user-images.githubusercontent.com/43196424/46184983-b4bf1d80-c2f5-11e8-9180-aa37a2fec941.png)

**Comment by ericblade** [comment]
is the A5FA... identifier what you're passing in as "backCamID" in startQuaggaJS ?   (also, for a general performance tip, you might want to really cut down on the number of decoders you're using . . if you don't really need all those barcode types, eliminate some.. it'll perform a lot better)

**Comment by SopraUser** [comment]
https://github.com/serratus/quaggaJS/issues/327#issuecomment-425785095

I am passing back camera Id in "backCamID"

**Comment by ericblade** [comment]
Try taking out facingMode if a deviceId is available?  I'm kind of grasping at straws here.

**Comment by SopraUser** [comment]
I have commented <b><i>target: document.querySelector('#video-container')</i></b> and its worked.
It is now opening back camera and scanning properly.
Thank you for you support.

**Comment by ericblade** [comment]
Great to hear. Note: facingMode and deviceId are not compatible with each other. :-D

**Comment by synedra-mpe** [comment]
For anyone landing here in search for a solution to this issue. deviceId has to be
`deviceId: {exact: deviceId}`, to make proper selection of desired camera.
Testet under iOS 12.2.

**Comment by ericblade** [comment]
I'll try to get one of my iOS users to test, but it *seems* to work for me using just "constraints.deviceId = cameraId"

**Comment by synedra-mpe** [comment]
Tried it again, and if `exact` property is omitted, camera switching to front is possible, but trying to switch back to rear camera, it stays at front camera. Maybe this get influenced by the initial start with `facingMode: {ideal: 'environment'}`?

Here the corresponding code in my projoct:

```javascript
quaggaStart() {
  let config = {
    locate: LOCATOR,
    inputStream: {
      name: 'Live',
      type: 'LiveStream',
      constraints: {
        ...(this.state.currentDevice ? {deviceId: {exact: this.state.currentDevice}} : {facingMode: {ideal: 'environment'}})
      }
  },
  decoder: {
    readers: SUPPORTED_READERS
  }
};

this.quagga.init(config, error => {
  if (!error) {...
```
