### ISSUE TITLE
Inconsistent barcode results?

### ISSUE THREAD

**Issue by Wancieho** [serratus/quaggaJS#330]
I got quaggaJS working from a tutorial online which uses my laptops webcam. Everything works perfectly fine but the barcode barely ever scans as the correct barcode? 2 in 10 scans actually gets the correct barcode and I've used 2 different products.

Why is the scanning so erratic? I'm in an average lit area but I find it hard to believe that lighting has such a drastic impact on the results?

**Comment by ericblade** [comment]
I've got 3 different webcams and a laptop built in camera, and none of them have image quality good enough to reliably scan.  Just because a camera says it's HD, doesn't mean it gives a very good image. :-S

**Comment by Wancieho** [comment]
Cool thanks. Moving to QR Codes as they seem way more reliable when using a webcam/laptop cam.
