### ISSUE TITLE
DOMException: Requested device not found

### ISSUE THREAD

**Issue by ashishlal91** [serratus/quaggaJS#333]
Here is the code I have used in my react component.

```
import Quagga from 'quagga'

  componentDidMount() {
    Quagga.init({           
      inputStream : {
          name : "Live",
          type : "LiveStream",
          target: document.querySelector('#barcode-scanner'), 
           constraints: {
              width: 520,
              height: 400,                  
              facingMode: "user"  //"environment" for back camera, "user" front camera
              }               
      },                         
      decoder : {
          readers : ["code_128_reader","code_39_reader"]
      }

  }, function(err) {
      if (err) {
        console.log(err)
        return
      }
      Quagga.start()
      Quagga.onDetected(function(result) {                              
        var last_code = result.codeResult.code;                   
        console.log("last_code "); 
     })
    })
  }
```

Which gives me following error

`DOMException: Requested device not found`

**Please help!!!**

**Comment by ericblade** [comment]
It's telling you you don't have a device that fits the constraints that you've given, width, height, and/or facingMode.

What device/browser/camera?

**Comment by ashishlal91** [comment]
@ericblade Thank you for replying. I am on chrome browser.

**Comment by ericblade** [comment]
and does the device have a camera?  If you open a new tab, then open inspector, you should be able to do: ````Promise.resolve(navigator.mediaDevices.getUserMedia({ video: true }));```` and it should ask for permission to use your camera, then return a Promise with a PromiseValue that should give some info

**Comment by pj1301** [comment]
Bringing this up again, I'm having an interesting issue in that I've got it working on mobile, but I get a DOMException error on all desktop browsers and the above promise command: 

Promise.resolve(navigator.mediaDevices.getUserMedia({ video: true }));

returns the error that the device cannot be found, regardless of the website. I've set my browser privacy to accept camera requests to no avail. My code is effectively the same as above except I've removed all constraints. 

Any ideas would be appreciated.

**Comment by mmaaart3n** [comment]
Some laptops are having a camera disable button, if you enable it with fn + F6 maybe it should work :)

**Comment by ericblade** [comment]
Yeah I don't really have any particular ideas on that one.  If it can't find the device, it's definitely some sort of local issue :-S

**Comment by NickPea** [comment]
Had the same issue. 

Simply restarted my laptop and now it works again.
