### ISSUE TITLE
Scanning sound(beep) after bar-code scanning

### ISSUE THREAD

**Issue by SopraUser** [serratus/quaggaJS#334]
i have used a mp3 file to create a scanning sound(beep) after scanning barcodes.

<pre>var audio = new Audio('audio_file.mp3');</pre> and play this after scannning complete.
<pre>audio.play();</pre>

It is working in Chrome and Firefox, but not in ios safari.

Has anyone else had to deal with this problem?

**Comment by Domratchev** [comment]
@SopraUser Try setting audio.currentTime = 0; before audio.play();

**Comment by ericblade** [comment]
i did this in my app too, but i found the lag time for audio.play() to frequently be completely unacceptable. Didn't really find an answer to that.  Don't have a functional iOS device to try it on, but @Domratchev suggestion seems potentially helpful, Safari does some weird stuff.

**Comment by PierreFritsch** [comment]
Since June 2017, Safari prevents `audio` from playing when it wasn't triggered by an explicit user interaction. 

https://webkit.org/blog/7734/auto-play-policy-changes-for-macos/

No idea how to circumvent this for the bar-code scanning use case...
