### ISSUE TITLE
Large barcodes not detecting corectly

### ISSUE THREAD

**Issue by binduks** [serratus/quaggaJS#34]
Hello 

Quaggajs is very nice for barcode reading but i found some issues that large barcode reads wrongly in live locator. Not getting the correct result.

And also another thing sometimes it is not correctly focusing the barcode. Can we have any solution for this? Can we make it as touch and focus correctly and then scan the barcode and after getting the correct data stop it.

I am familiar with getusermedia but this barcode scanning making problems to me. Because sometimes we are getting the wrong result with barcode scanning. But in zxing app it is focusing correctly and getting the correct solution always and also for lengthy barcodes too. So if i get the accurate result like that then i will be very happy.

**Comment by serratus** [comment]
If you work with really large barcodes, meaning that they cover more than half of the image, you should consider adjusting the ``patchSize``. In your case, setting it to ``large`` or even ``x-large`` could help addressing the problem.

Like you already said, the example is using ``getUserMedia`` which is controlled by the browser. There is currently no way, or at least I don't know any, to adjust the focus from within the browser. zxing has the huge advantage that it runs natively and has access to all device-specific APIs. Sorry, but currently there is nothing I could do about it.

Regarding barcodes which are incorrectly recognized, I'm working on reducing the rate of false positives. Which codes are you currently testing?

**Comment by binduks** [comment]
Hello 

Thank you for the fast reply.

I tested both live stream and file input method. You given examples for this

http://serratus.github.io/quaggaJS/examples/file_input.html

http://serratus.github.io/quaggaJS/examples/live_w_locator.html

Here in both these method I am experiencing some issues.

1) In file input method if the camera is larger than 8 MP then memory issues there with browser. It will not save the image. It will show only title of image. I checked the file input method with my sony xepria t2 ultra 13 mp camera and also moto g and motox with 10 mp camera. After taking the picture the image not coming back to the screen.

2) For the live stream when the page loaded it camera tracing the barcode and if it detects half then also it gives wrong barcode and again and again in between some times it detects correct one. For some barcode it is not at all giving the output.

**Comment by syntaxTerr0r** [comment]
Hi there,

Same issue on my side. Here are some examples to help:

![example 1](http://lab.deliver.ee/github/barcode_1.jpg)
![example 2](http://lab.deliver.ee/github/barcode_2.jpg)

**Comment by serratus** [comment]
Thanks for the images. The problem seemed to be related to #30 and should work now. Please take another try so I can close this issue.
![34](https://cloud.githubusercontent.com/assets/1381822/7550603/71cc8fb0-f668-11e4-895c-c2a480e1d6ce.png)

**Comment by syntaxTerr0r** [comment]
I confirm it perfectly work now on my examples. Thanks a lot.

**Comment by jamsshhayd** [comment]
It still has the same issue, I am getting incorrect readings whenever I try to read it in live stream mode. 
![Uploading 33cd9f04-9a6d-4c18-9085-18ca499561ba.jpg…]()

**Comment by risha700** [comment]
Such a great example, unfortunately it is not accurate :(

**Comment by ericblade** [comment]
Your comment does not really have enough context to make sense. Please clarify.

**Comment by risha700** [comment]
@ericblade 
here are some samples for EAN-13 type with decode.reader settings 
```
            decoder: {
                readers: [
                    "code_128_reader",
                    "ean_reader",
                    "ean_8_reader",
                    "code_39_reader",
                    "code_39_vin_reader",
                    "upc_reader",
                    "upc_e_reader",
                    "i2of5_reader",

                ],
...}

```
<img width="1673" alt="Screen Shot 2020-01-20 at 2 38 33 PM" src="https://user-images.githubusercontent.com/25058544/72756379-a358ef00-3b92-11ea-9bca-94830ce1bb58.png">


another sample with limited readers

```
            decoder: {
                readers: [
                    "i2of5_reader",
                ],
```
<img width="1668" alt="Screen Shot 2020-01-20 at 2 41 51 PM" src="https://user-images.githubusercontent.com/25058544/72756501-03e82c00-3b93-11ea-864a-b066cd3e91ef.png">
