### ISSUE TITLE
Questions About ThePlugin

### ISSUE THREAD

**Issue by AlexMachin1997** [serratus/quaggaJS#340]
Hi,

Im looking to create a bar code reader using QuaggaJS. But I have a few questions which can be found below ?

1) Can the ID be extracted on both static images and livestream ?
2) Can the ID be used for a database query to say a SQL or NoSQL database ?
3) Is this plugin well supported ?
4) Does this work with ReactJS or React-Native ?

**Comment by michaeltrollan** [comment]
Based on my experience recently implementing QuaggaJS, these would be my personal answers:

1. Yes, my implementation offers users the ability to upload an image or to use their camera. Both work.
2. Yes. Once the scanner finds the ID, it is a string you can use for anything you have access to do, including making a database query.
3. The plugin is open-source, so little official support is available. You will largely be responsible for making it work yourself. This is an improvement over writing it from scratch, however. And cheaper than a piece of paid software.
4. Yes. It is an npm package which should give you no trouble being imported and used in a ReactJS and React-Native app. 

Hope that helps with your analysis.

**Comment by michaeltrollan** [comment]
Be aware that for a mobile web-app, this plugin relies on technology which is not supported in iOS Chrome, and recently stopped working in iOS 12 Safari as well. See my open issue here: https://github.com/serratus/quaggaJS/issues/339

**Comment by ericblade** [comment]
> Be aware that if you are using Quagga for a website (i.e. that users access by going to a URL in a browser), this plugin relies on technology which is not supported in iOS Chrome, and recently stopped working in iOS 12 Safari as well.
> 
> See my open issue here: #339

for what it's worth, i've got 3 new iOS users of my app, that all report it working fine in iOS 12, after I updated the camera requirements section of my app.

**Comment by AlexMachin1997** [comment]
For the time being its going to be safer to use a native solution I think, probably going to use React-Native to build the app. It makes more sense to use native technologies for what I want to do. If it didn't require a barcode scanner it would be a different story.

**Comment by michaeltrollan** [comment]
For what it's worth, I have a production web application doing barcode scanning for one of the top 3 auto manufacturing brands.

**Comment by AlexMachin1997** [comment]
@michaeltrollan Really? was it difficult to implement?
