### ISSUE TITLE
Can I use quaggaJS with my own mediaStream or ImageData ?

### ISSUE THREAD

**Issue by Bajdzis** [serratus/quaggaJS#345]
Hi, I tried to use `decodeSingle`  function but creating base64 URI from canvas was very slow.

I need to have my own mediaStream because I have to add QRCode scanner and use `noiseSuppression` and `torch`.

What is the best solution to achieve my goal?

**Comment by ericblade** [comment]
it'd take me a bit to dig through some code to see if that's something that can be done, i don't know about it for sure at the moment.  You should be able to enable camera options by using something a bit like

````
            const track = window.Quagga && window.Quagga.CameraAccess && window.Quagga.CameraAccess.getActiveTrack();
            if (track && typeof track.getCapabilities === 'function') {
                track.applyConstraints({ advanced: [{ torch: true }] }).catch(err => console.warn('* error enabling torch', err));
            }
````
