### ISSUE TITLE
How can I get live with locator without menus?

### ISSUE THREAD

**Issue by AnilGupte** [serratus/quaggaJS#355]
I have got this utility to work (mostly), but now I want to integrate it into my application.  I am using an iFrame to include the file that will do the work and embeds the camera.  This works also, but now I need to remove the menus.

Is there an example without the menus?  Or better still, is there documentation that describes how to set the parameters and I can remove the menu items that I don't need.

**Comment by ericblade** [comment]
yes, there's no reason to load the demo page into an iframe, that sounds particularly difficult to operate with.

There's a description of virtually all the parameters in the README, and plenty of examples.

Do you have some more specific questions as to how to do something inparticular?

**Comment by AnilGupte** [comment]
I have cleaned up that file to a large extent.  Here it is:

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <title>index</title>
    <meta name="description" content="" />
    <meta name="author" content="Christoph Oberhofer" />

    <meta name="viewport" content="width=device-width; initial-scale=1.0; user-scalable=no" />
    <link rel="stylesheet" type="text/css" href="css/styles.css" />
  </head>	
  <body>
	<div style="height:300px;width:500px;margin:auto;margin-top:-20px;margin-bottom:0px">
		<div class="controls" style="display:inline;float:none;">
			<input type="hidden" name="decoder_readers" value="code_128">
			<input type="hidden" name="input-stream_constraints" value="1280x720">
			<input type="hidden" name="locator_patch-size" value="medium">
			<input type="hidden" name="locator_half-sample" />
			<select name="input-stream_constraints" id="deviceSelection"></select>
		</div>
		<div id="interactive" class="viewport"></div>
	</div>
    <script src="q/vendor/jquery-1.9.0.min.js" type="text/javascript"></script>
    <script src="//webrtc.github.io/adapter/adapter-latest.js" type="text/javascript"></script>
    <script src="q/dist/quagga.js" type="text/javascript"></script>
    <script src="q/live_w_locator.js" type="text/javascript"></script>
  </body>
</html>
```
Still haven't founnd a way to get rid of the Camera Selector Dropdown.  Also, a big empty space appears below the interactive viewport, using the fllowing HTML (proboably inserted by the JavaScript).
`<canvas class="drawingBuffer" width="640" height="480"></canvas>`
Anyway, to get rid of that?

**Comment by ericblade** [comment]
That is an example that is meant to show you how to use it.  It is not meant to be included into another page.

**Comment by AnilGupte** [comment]
Even if I were not including it in another page, how would I go about removing user input and customizing it?  Where is the CSS to, (for example) remove the lower empty space?

**Comment by ericblade** [comment]
https://github.com/serratus/quaggaJS/tree/master/example/css
