### ISSUE TITLE
Barcodes not detecting corectly

### ISSUE THREAD

**Issue by binduks** [serratus/quaggaJS#36]
Hello 

You closed my issue, but my issue not solved. i posted a second comment there with your file input method and strream method
Can you check the below images reading with your file input method

http://serratus.github.io/quaggaJS/examples/file_input.html

![barcodegen](https://cloud.githubusercontent.com/assets/12252364/7586806/56d6274e-f8ce-11e4-8f5b-80c029948202.png)
![samplejpg](https://cloud.githubusercontent.com/assets/12252364/7586807/5e41c646-f8ce-11e4-85e8-670bf0340c2a.jpg)
![barcodegen128](https://cloud.githubusercontent.com/assets/12252364/7586810/6339aca4-f8ce-11e4-885d-45c06e8fbf28.png)
![barcodegenupc](https://cloud.githubusercontent.com/assets/12252364/7586812/65fd77fe-f8ce-11e4-8491-d07d501b6514.png)

**Comment by serratus** [comment]
Hi,

sorry to close your issue without discussing it properly. I managed to decode all of your examples by simply setting the patch-size to ``large`` (because the barcode covers more than 70% of the image) and the proper decoder (EAN, UPC, Code 128, UPC). See for yourself:
![36](https://cloud.githubusercontent.com/assets/1381822/7594867/ca14f784-f8e3-11e4-8fb9-ea0b4aa00fbb.png)

Hope this helps. Do you think we can close this issue?

**Comment by binduks** [comment]
Hello 

Thank you for your fast reply. 

I tried these images with the file input method example given in the link

http://serratus.github.io/quaggaJS/examples/file_input.html

But I am not getting any output. I am attaching the screen here.

![image2](https://cloud.githubusercontent.com/assets/12252364/7604004/2fd6ea98-f95a-11e4-84d3-ac4ccfdcaaf2.jpg)

**Comment by serratus** [comment]
That's unexpected. Can you try re-running it with ``workers`` set zero? Which version of Chrome are you using?

**Comment by binduks** [comment]
Hello 

The error is not only with my system i tried in other chromes too, in my mobile too, The earlier worked versions also not working now.

**Comment by serratus** [comment]
Can you tell me which version of Chrome you are using? Does it also happen in Firefox?

**Comment by serratus** [comment]
@binduks are you still having problems using the examples in Chrome? If not, please close this issue.

**Comment by lmadeira** [comment]
Same problem here. Trying to decode an EAN 13 barcode (7896326902974) but some times it reads 2820326902974:

![screenshot_2015-06-05-14-38-43](https://cloud.githubusercontent.com/assets/13368/8011681/17bb914a-0b91-11e5-9481-6231b4c44e10.png)

**Comment by serratus** [comment]
@lmadeira Thanks for reporting this issue. I'm aware of this situation and try to improve the reduction of false positives steadily. Hopefully I can find some time to adjust the parameters accordingly. Unfortunately, this requires quite a lot of testing and won't be published quickly. I'll keep you in the loop.

**Comment by serratus** [comment]
I've managed to squash some bugs in the implementation (see 31df5d8faff10325b0f94cdd28f4e990eb38fc08). With the latest update, you should get much more reliable results. Please report back to me in the next coming days. I'll close that issue otherwise.

**Comment by binduks** [comment]
thank you for reply, sorry for someday i was away frm this, now again i hve issue with live stream. could u pls help me in this, it is an urgent for me
