### ISSUE TITLE
Code 39 barcode not reading

### ISSUE THREAD

**Issue by Shenanigan911** [serratus/quaggaJS#361]
I'm having a hard time with this barcode.  Other formats (ean, upc, code 128) are working great, and other barcode apps are able to read this as a code 39, but it is failing for me.

![barcode](https://user-images.githubusercontent.com/20913763/54637358-1747d980-4a4e-11e9-96ab-cb5bd96aa0fa.jpg)

Here's the configuration I'm working with:
````
var liveStreamConfig = {
    inputStream: {
	type: "LiveStream",
	constraints: {
	    width: {min: 640},
	    height: {min: 480},
	    aspectRatio: {min: 1, max: 100},
	    facingMode: "environment" 
	}
    },
    locator: {
	patchSize: "medium",
	halfSample: "false" 
    },
    numOfWorkers: (navigator.hardwareConcurrency ? navigator.hardwareConcurrency : 4),
    decoder: {
	"readers": [ 
	{"format": "upc_reader",  
	 "config": {}
	},
	{"format": "ean_reader",  
	 "config": {}
	},
	{"format": "code_128_reader",  
	 "config": {}
	}
    ];
    },
    locate: true 
};````

**Comment by StuMcNeill** [comment]
You're not configured to read Code 39 barcodes.  You should add `code_39_reader` to your list of readers.

**Comment by acorncom** [comment]
Looks like this issue can be closed
