### ISSUE TITLE
How to switch the torch ON

### ISSUE THREAD

**Issue by johny77g** [serratus/quaggaJS#364]
I am using quagga scan to input field application (Android/Chrome) https://serratus.github.io/quaggaJS/v1.0.0-beta.1/examples/scan-to-input/ 
and have an issue how to switch the torch on.

I was trying to put code as following in different places but did not succeed

```
var track = Quagga.CameraAccess.getActiveTrack();
track.applyConstraints({advanced: [{torch: true}]});
```
Where to place/what code (inside the original - scan to input - code) to have possibility to have the torch ON.

**Comment by achu94** [comment]
Hey, if your device have multiple deivces(cameras) not all of them are supporting the torch, you have to find the right one and than start the stream with Quagga,start() than you can put torch on.

**Comment by johny77g** [comment]
Hi, yes it's true. For example on Galaxy A52 only one camera out of four available is supporting torch.
