### ISSUE TITLE
Zebra TC25 | The Barcode 

### ISSUE THREAD

**Issue by RaghavendraNK** [serratus/quaggaJS#366]
Hi we are using Zebra TC25 , where it has top camera, but when we use Quagga its taking only back camera for barcode scanning(tested in both firefox and chrome) so how we can change the configuration point to top side camera.

Please suggest

![zebra](https://user-images.githubusercontent.com/8822120/55498056-4a9a8300-5660-11e9-916f-4498de0ce0b4.jpg)

**Comment by ericblade** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/enumerateDevices
