### ISSUE TITLE
TypeError: Cannot read property 'x' of null

### ISSUE THREAD

**Issue by nabrih** [serratus/quaggaJS#379]
When i load it to my project, error appear like this:

> TypeError: Cannot read property 'x' of null
    at Object.checkImageConstraints (<anonymous>:6494:71)
    at canRecord (<anonymous>:3615:79)
    at Object.that.trigger (<anonymous>:5696:29)
    at <anonymous>:3591:26

just show the camera, but no green line

**Comment by ericblade** [comment]
You'll need to provide more information than just "load it"

**Comment by nabrih** [comment]
i use jQuery .load() function like this:

`$('#readerContainer').load("barcodeScanner.html");`

here is in the console :
![image](https://user-images.githubusercontent.com/15963359/61423463-18284380-a93a-11e9-9d75-e3746a9a9797.png)

**Comment by ericblade** [comment]
... loading a sample html page into your document is most definitely not going to work.
