### ISSUE TITLE
Request for Bower Support

### ISSUE THREAD

**Issue by jclarkin** [serratus/quaggaJS#39]
I would like to use your project via bower.

To do so would require:
* [`bower.json`](https://github.com/serratus/quaggaJS/pull/40) file
* [Tagging](https://help.github.com/articles/working-with-tags/) a release in github with the version (`0.6.6` as of now)
* [Registering](http://bower.io/docs/creating-packages/) the repo with Bower.io (`bower quagga git@github.com:serratus/quaggaJS.git`)

Might that be a possibility?

**Comment by serratus** [comment]
Thanks for the detailed description. I'll let you know when it's done.

**Comment by MrChoclate** [comment]
+1

**Comment by bretthodel** [comment]
+1

**Comment by serratus** [comment]
Sorry for the long delay. I don't have any experience yet regarding bower, nor have I ever used it. This is something I have to change right away. I hope to have something ready by the end of the week.

**Comment by jclarkin** [comment]
Wow, cool!
ᐧ

On Tue, Jul 7, 2015 at 6:50 PM, Christoph Oberhofer <
notifications@github.com> wrote:

> Sorry for the long delay. I don't have any experience yet regarding bower,
> nor have I ever used it. This is something I have to change right away. I
> hope to have something ready by the end of the week.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serratus/quaggaJS/issues/39#issuecomment-119366104>.
>



-- 

 ― Jonathan Clarkin <http://jclarkin.github.io> ―
