### ISSUE TITLE
Select barcode type from Quagga

### ISSUE THREAD

**Issue by cheahengsoon** [serratus/quaggaJS#390]
I want decode the value of Barcode by selecting from Dropdownlist, but it's not working.
When I switch to other barcode Type,its not working.
Here with my source code.
```
<select id="mySelect" onchange="myFunction()">
        <option>Please Select Barcode Type</option>
        <option value="code_128_reader">code_128</option>

        <option value="ean_8_reader">ean_8</option>

    </select> 
```

Here with my javascript
```
 function myFunction() {

        Quagga.init({
            inputStream: {
                name: "Live",
                type: "LiveStream",
                target: document.querySelector('#camera')    // Or '#yourElement' (optional)
            },
            decoder: {
                readers: ["document.getElementById("mySelect").value"]

            }
        }, function (err) {
            if (err) {
                console.log(err);
                return
            }
            console.log("Initialization finished. Ready to start");
            Quagga.start();
        });

        Quagga.onDetected(function (data) {
            console.log(data);

            document.querySelector("#resultado").innerHTML = data.codeResult.code;

        });
    }
```

**Comment by ericblade** [comment]
Your readers line is a string, not code that refers to that value.

**Comment by cheahengsoon** [comment]
I had correct it.

But when I want to change to other BarCode type , need to include the code as below?
```
Quagga.offDetected();
                  Quagga.offProcessed();
                    Quagga.stop();
```

**Comment by ericblade** [comment]
I don't believe there is any way to change the readers at runtime, so yes you would need to call .stop() on it, then .start() again with new readers set.  I would warn that you might find you need to have a couple of seconds of delay between calling stop and start, though, if you're using a live video feed -- at least in Android, calling stop() then start() rapidly causes my phone (Android 8) to crash.
