### ISSUE TITLE
Scan speed is too Slow in iPhone. Version is 12.4

### ISSUE THREAD

**Issue by SumanDontha16** [serratus/quaggaJS#392]
Hello, I know this is not an issue but I just wonder if scan speed can be improved a little bit in iPhone (iOS)? Its working fine in Andriod devices scans too fast, not in iPhone.

I'm using to React and have a Scanner component.

Here's my init inside scanner.component.js:

Quagga.init(
      {
        inputStream: {
          type: 'LiveStream',
          constraints: {
            width: 640,
            height: 480,
            facingMode: 'environment', // or user
          },
        },
        locator: {
          patchSize: 'medium',
          halfSample: true,
        },
        numOfWorkers: 4,
        decoder: {
          readers: ['code_39_reader'],
        },
        locate: true,
        frequency: 1,

        debug: {
          drawBoundingBox: true,
          showFrequency: true,
          drawScanline: true,
          showPattern: true,
        },
      },
      function(err) {
        if (err) {
          return console.log(err)
        }
        Quagga.start()
      },
    )
    Quagga.onDetected(this._onDetected)
  }

  componentWillUnmount() {
    Quagga.offDetected(this._onDetected)
    Quagga.stop()
  }

  _onDetected(result) {
    const drawingCanvas = Quagga.canvas.dom.overlay
    drawingCanvas.style.display = 'none'
    Quagga.stop()
    this.props.onDetected(result)
  }
} 

Any help appreciated.

Versions
quagga@0.12.1
react@16.4.0

Regards,
Suman

**Comment by ericblade** [comment]
Turn off the debug things?

Otherwise, there are several tips in the readme for improving speed/accuracy, you might want to go through there.

**Comment by SumanDontha16** [comment]
Thanks @ericblade for the suggestion. I have removed the `debug`. Then also it was not working. Need you help on this. 

numOfWorkers, frequency do we need to change on these. I have added a audio on Detect to get the beep sound. It's also not working.

Quagga.init(
{
inputStream: {
type: 'LiveStream',
constraints: {
width: 640,
height: 480,
facingMode: 'environment', // or user
},
},
locator: {
patchSize: 'medium',
halfSample: true,
},
numOfWorkers: 4,
decoder: {
readers: ['code_39_reader'],
},
locate: true,
frequency: 1,
  },
  function(err) {
    if (err) {
      return console.log(err)
    }
    Quagga.start()
  },
)
Quagga.onDetected(this._onDetected)
}

componentWillUnmount() {
Quagga.offDetected(this._onDetected)
Quagga.stop()
}

_onDetected(result) {
const drawingCanvas = Quagga.canvas.dom.overlay
drawingCanvas.style.display = 'none'

var audio = new Audio('barcode.wav');
audio.play();
Quagga.stop()
this.props.onDetected(result)
}
}

Any help appreciated.

**Comment by ericblade** [comment]
.. I really unfortunately don't have any thing specific, but you might try playing with resolution, locator on/off and other locator settings, etc, and see if you can find something acceptable.

fwiw, I use
````            numOfWorkers: window.navigator.hardwareConcurrency || 2, ````

running 4 threads might be too little or too much depending on the hardware it's run on...
