### ISSUE TITLE
example do not work with node.js 

### ISSUE THREAD

**Issue by vasylhumenyuk** [serratus/quaggaJS#393]
my current node version 10.16.0

my code sample. 

var Quagga = require('quagga').default;

Quagga.decodeSingle({
    src: "file1.png",
    numOfWorkers: 0,  // Needs to be 0 when used within node
    inputStream: {
        size: 800  // restrict input-size to be 800px in width (long-side)
    },
    decoder: {
        readers: ["code_128_reader" ] // List of active readers
    },
}, function(result) {
    if(result.codeResult) {
        console.log("result", result.codeResult.code);
    } else {
        console.log("not detected");
    }
});

i have  always not detected . images from site with samples and examples

**Comment by ericblade** [comment]
are you using code 128 barcodes?

**Comment by vasylhumenyuk** [comment]
sorry, it works.   i made mistake with downloading image.
thank you for fast reply. I realized my mistake in the process of writing
the answer to you.

[image: image.png]
and the result - only lines.
