### ISSUE TITLE
Android Not Working WebView

### ISSUE THREAD

**Issue by federicoprimomo** [serratus/quaggaJS#396]
I have a website where I use this library, accessing with the phone chrome, it works perfectly.
Then I made an application, with Android Studio, and in the webview I call that page, 
But it doesn't open the camera.
Then android studio log says:

> **I/chromium: [INFO:CONSOLE(101)] "[object DOMException]", source: https://www.XXX.com.ar/AAA/BBB(101)**

Here there is a screen capture.
[](https://ibb.co/KsMgt0J)
 Thanks in advance.

**Comment by ericblade** [comment]
I'm not entirely familiar with the Android app packaging process, but my first suspicion is that you'll need to provide permissions to access the camera.

**Comment by federicoprimomo** [comment]
Permission are OK, into manifest

**Comment by ericblade** [comment]
If you can provide some code, maybe we can help further.

**Comment by federicoprimomo** [comment]
ANDROID MANIFEST:
```
<?xml version="1.0" encoding="utf-8"?>

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.autoshop24">
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-feature android:name="android.hardware.camera" android:required="true" />
    <uses-feature android:name="android.hardware.camera.autofocus" />

    <application

        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        <activity android:name=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>

</manifest>
```
MAIN ACTIVITY:
```
package com.example.autoshop24;
import android.net.http.SslError;
import androidx.appcompat.app.AppCompatActivity;
import android.webkit.WebView;
import android.os.Bundle;
import android.Manifest;
import android.webkit.WebSettings;
import android.webkit.SslErrorHandler;
import android.webkit.WebChromeClient;
import android.webkit.WebView;
import android.webkit.WebViewClient;
import android.webkit.WebViewClient;
public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        int permissionCheck = this.checkSelfPermission(Manifest.permission.CAMERA);
        if (permissionCheck== android.content.pm.PackageManager.PERMISSION_DENIED) {
            requestPermissions(new String[]{Manifest.permission.CAMERA},5);
        }
        WebView myWebView = (WebView) findViewById(R.id.webView);
        WebSettings webSettings = myWebView.getSettings();
        webSettings.setJavaScriptEnabled(true);
        webSettings.setUseWideViewPort(true);
        webSettings.setJavaScriptCanOpenWindowsAutomatically(true);
        webSettings.setAppCacheEnabled(true);
        webSettings.setDomStorageEnabled(true);
        webSettings.setSupportZoom(true);
        myWebView.setWebViewClient(new WebViewClient(){
            @Override
            public void onReceivedSslError(WebView view, SslErrorHandler handler, SslError error) {
                handler.proceed();
            }
        });
        myWebView.loadUrl("https://www.XXXXXX.com.ar/");
    }
}

ACTIVITY MAIN:
```
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity">

    <WebView
        android:id="@+id/webView"
        android:layout_width="fill_parent"
        android:layout_height="fill_parent"
        android:layout_alignParentStart="true"
        android:layout_alignParentLeft="true"
        android:layout_alignParentTop="true"
        android:layout_alignParentEnd="true"
        android:layout_alignParentRight="true"
        android:layout_alignParentBottom="true"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintHorizontal_bias="0.5"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

</androidx.constraintlayout.widget.ConstraintLayout>
```
```

**Comment by federicoprimomo** [comment]
any help?

**Comment by federicoprimomo** [comment]
I solved the issue adding this lines before url open:

```
        myWebView.setWebChromeClient(new WebChromeClient() {
            @Override
            public void onPermissionRequest(android.webkit.PermissionRequest request) {
                request.grant(request.getResources());
            }
        });
```

**Comment by ericblade** [comment]
seems that you were granting permission at the android level, but still needed to tell Chrome to get permission, or something like that.  Glad you found it :)
