### ISSUE TITLE
Manually define camera?

### ISSUE THREAD

**Issue by RobertDickey** [serratus/quaggaJS#397]
Is there a way to manually define a camera? I would like my users to be able to set a default. I can store the ID myself, but cannot figure out how to init the camera from the start with the provided ID.

**Comment by ericblade** [comment]
By providing the deviceId in the constraints object in the inputStream configuration.  Suchas

````
        const constraints = {
            width: {
                min: 640,
            },
            height: {
                min: 480,
            },
            aspectRatio: {
                min: 1,
                max: 2,
            },
            focusMode: 'continuous',
            ...(!this.props.cameraId && { facingMode: 'environment' }),
            ...(this.props.cameraId && { deviceId: this.props.cameraId }),
        };

        Quagga.init({
            inputStream: {
                type: 'LiveStream',
                target: document.querySelector('#scannerViewport'),
                constraints,
            },
            locator: {
                patchSize: 'medium',
                halfSample: true,
            },
            numOfWorkers: window.navigator.hardwareConcurrency || 2,
            decoder: {
                readers: ['upc_reader', 'ean_reader'],
            },
....
````

**Comment by RobertDickey** [comment]
I may have done it wrong. I set deviceId to the hardware ID provided by quagga like


```
state: {
            inputStream: {
                type : "LiveStream",
                constraints: {
                    width: {min: 1140},
                    height: {min: 900},
                    facingMode: "exact: environment",
                   deviceId: 046d:082d,
                    aspectRatio: {min: 1, max: 2},

                }
            },
            locator: {
                patchSize: "medium",
                halfSample: true
            },
            numOfWorkers: 2,
            frequency: 10,
            decoder: {
                readers : [{
                    format: "code_39_reader",
                    config: {}
                }]
            },
            locate: false
        },
        lastResult : null
    };
```

is this correct? It still defaults to the other camera.

**Comment by ericblade** [comment]
I've seen problems when having both facingMode and deviceId specified, so my React component above only puts facingMode in when deviceId isn't known

This is what I get from a call to Quagga.CameraAccess.enumerateVideoDevices()

![image](https://user-images.githubusercontent.com/1451847/66090357-03c71080-e551-11e9-9832-e70716b7e01a.png)

The deviceId is usually quite a long string.  Maybe you are using a different browser/OS than me, but it looks like you're using a USB device number, which isn't, as far as i know, what is returned by enumerateDevices

**Comment by RobertDickey** [comment]
Thank you for the help. Sorry for the mistakes. and thank you always helping with this library! Perhaps I'm not understanding how to output the deviceID then. One question I have is when I use chrome to inspect the device selection dropdown I see nothing, even though the device list is populated. I guess that is due to the how it is being called and generated via JS?

**Comment by ericblade** [comment]
my working code is a bit too complex to easily paste in, as i'm using redux to store all my data in my app.. but.. what i did above, was just open a browser console on a new tab, and do

```
navigator.mediaDevices.enumerateDevices().then((x) => console.log(x));
```
on my pc, i get several audio in and out devices, and my one webcam video device.
