### ISSUE TITLE
Can i use quaggaJS on JSP?

### ISSUE THREAD

**Issue by doy0818b** [serratus/quaggaJS#398]
I trying to get barcode number for a product using jsp, but it does not work.
According to the guide, quaggaJS can use script tags
I tried to create the following example script that includes dist / quagga.min.js but it doesn't work.
https://serratus.github.io/quaggaJS/v1.0.0-beta.1/examples/scan-to-input/
I copied this page to see if it worked, but it failed. 
this is the best way for my project.

I would appreciate it if you could tell me how to use this as jsp.

:My development environment is tomcat and jsp in eclipse.

**Comment by ericblade** [comment]
We will need a better description of "it doesn't work" to be able to help you.  I doubt that it's anything related to JSP, as long as the HTML the client is receiving is correct.

**Comment by doy0818b** [comment]
thank you for reply.

i tried copy that web page. but nothing happens when I press the button.

this is my jsp code.

`<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">    
    <link rel="canonical" href="https://serratus.github.io/v1.0.0-beta.1/examples/scan-to-input/" />
    <link rel="stylesheet" href="https://serratus.github.io/quaggaJS/stylesheets/styles.css">
    <link rel="stylesheet" href="https://serratus.github.io/quaggaJS/stylesheets/example.css">
    <link rel="stylesheet" href="https://serratus.github.io/quaggaJS/stylesheets/pygment_trac.css">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">

  </head>
  <body>    
  
  	<div>
	<form>
    <div class="input-field">
        <label for="isbn_input">EAN:</label>
        <input id="isbn_input" class="isbn" type="text" />
        <button type="button" class="icon-barcode button scan"> </button>
    </div>
	</form>   	
	
	</div>
	
	
	
	
	<script src="quagga.js" type="text/javascript"></script>
    <script>
	var Quagga = window.Quagga;
	var App = {
	    _scanner: null,
	    init: function() {
	        this.attachListeners();
	    },
	    activateScanner: function() {
	        var scanner = this.configureScanner('.overlay__content'),
	            onDetected = function (result) {
	                document.querySelector('input.isbn').value = result.codeResult.code;
	                stop();
	            }.bind(this),
	            stop = function() {
	                scanner.stop();  // should also clear all event-listeners?
	                scanner.removeEventListener('detected', onDetected);
	                this.hideOverlay();
	                this.attachListeners();
	            }.bind(this);

	        this.showOverlay(stop);
	        scanner.addEventListener('detected', onDetected).start();
	    },
	    attachListeners: function() {
	        var self = this,
	            button = document.querySelector('.input-field input + button.scan');

	        button.addEventListener("click", function onClick(e) {
	            e.preventDefault();
	            button.removeEventListener("click", onClick);
	            self.activateScanner();
	        });
	    },
	    showOverlay: function(cancelCb) {
	        if (!this._overlay) {
	            var content = document.createElement('div'),
	                closeButton = document.createElement('div');

	            closeButton.appendChild(document.createTextNode('X'));
	            content.className = 'overlay__content';
	            closeButton.className = 'overlay__close';
	            this._overlay = document.createElement('div');
	            this._overlay.className = 'overlay';
	            this._overlay.appendChild(content);
	            content.appendChild(closeButton);
	            closeButton.addEventListener('click', function closeClick() {
	                closeButton.removeEventListener('click', closeClick);
	                cancelCb();
	            });
	            document.body.appendChild(this._overlay);
	        } else {
	            var closeButton = document.querySelector('.overlay__close');
	            closeButton.addEventListener('click', function closeClick() {
	                closeButton.removeEventListener('click', closeClick);
	                cancelCb();
	            });
	        }
	        this._overlay.style.display = "block";
	    },
	    hideOverlay: function() {
	        if (this._overlay) {
	            this._overlay.style.display = "none";
	        }
	    },
	    configureScanner: function(selector) {
	        if (!this._scanner) {
	            this._scanner = Quagga
	                .decoder({readers: ['ean_reader']})
	                .locator({patchSize: 'medium'})
	                .fromVideo({
	                    target: selector,
	                    constraints: {
	                        width: 800,
	                        height: 600,
	                        facingMode: "environment"
	                    }
	                });
	        }
	        return this._scanner;
	    }
	};
	App.init();
		
	</script>	

  </body>
</html>
`

**Comment by ericblade** [comment]
"nothing happens" isn't really a description here, I think you'll need to learn to use your browser's debugger to see what the source of the problem is.  I'm going to guess that most likely you're not loading it from a secure server (https) which is necessary for camera access in browser.  As you can see from the link above, that exact code works fine, and whatever software is serving it isn't relevant, so you'll need to look at the javascript console in chrome or whatever to see what is failing.

**Comment by solsticesurfer** [comment]
Yes, you can use it with JSP. Java Server Pages (JSP) is just a convenience format for creating a Java servlet that returns HTML code to the client. The returned code is no different than if you had coded the web page's content manually. JSP does not interpret, modify, or run any of the HTML or JavaScript code on the server side. 

If you want to remove JSP from the equation as a possible cause of why it might not be working for you, simply create a plain HTML page and try to get the scanning to work from there first. Really, tho, there is no difference between a standard HTML page and a JSP page as far as the browser is concerned. The results are identical.
