### ISSUE TITLE
 Incorrect numbers on iphone

### ISSUE THREAD

**Issue by danielschmitz** [serratus/quaggaJS#401]
Hi all,

I am always having incorrect numbers on the iphone 8. In android it works normal.

video: https://www.dropbox.com/s/r45rr1ggq1ve5wt/IMG_1150.MP4?dl=0

I need to do some extra configuration?

**Comment by ericblade** [comment]
My advice would be to try different resolution and locator settings, perhaps iphone 8's camera at 640x480 doesn't work similarly to whatever your android phone's camera is.  Increasing resolution may require changing the locator settings.

**Comment by danielschmitz** [comment]
Works fine with 1920x1080, thanks
