### ISSUE TITLE
How to decode entire image

### ISSUE THREAD

**Issue by mamcgree** [serratus/quaggaJS#404]
Greetings...
Your scanner works great.  But when I load an image of multiple barcodes (all  code_39) and set to locate and muliple the onDetected only returns 1 barcode.  Is there a settings to ask for the entire image to be decoded.
Thank you in advance

**Comment by mamcgree** [comment]
Figured it out.. thanks

**Comment by ericblade** [comment]
what did you do?

**Comment by mamcgree** [comment]
I used the example file_input.html and changed the decoder to include multiple:true.  When I ran it it gave an error for the Quagga.onDetected fuction because the code was looking for result.codeResult.code which does not exist for multiple.  It returns an array of objects which might have multiple codeResult objects and box objects.  I just thought if I changed it to multiple the example would handle it, but it was written to just handle one.  Hope that helps..
Cheers..
