### ISSUE TITLE
Barcode never detected

### ISSUE THREAD

**Issue by drentsch** [serratus/quaggaJS#412]
Hi, 
i have integrated quagga in a existing project.
if try to read barcode with decodeSingle is working with each file from quagga-test-fixtures-code_128
If y try to read one of my one images no barcode was detected.
i have generated my img with online-barcode-generator. Other online-barcode-scanner can detect the code.

My Code:
var dataUrl = canvas.toDataURL('image/jpeg');
var lx = qs(dataUrl);

function qs(img) {
              Quagga.decodeSingle({
                  decoder: {
                      readers: ["code_128_reader"] // List of active readers
                  },
                  locate: true, // try to locate the barcode in the image
                  src: img
              }, function (result) {
                  if (result.codeResult) {
                      console.log("result", result.codeResult.code);
                  } else {
                      console.log("not detected");
                  }
              });
          }

any idea what i'm doing wrong?
Attached you found my image.

Thanks
![image-002](https://user-images.githubusercontent.com/3909661/72524134-8904d580-3861-11ea-9d68-a75d76343217.jpg)

**Comment by ericblade** [comment]
There must be whitespace around the image for that to read.  Try 
![image](https://user-images.githubusercontent.com/1451847/72536845-096b0c80-3849-11ea-870a-efb3a84d9499.png)

I suppose we could try inserting whitespace around an image, that might make it possible to detect when there's too small of a border around an image

**Comment by drentsch** [comment]
many thanks, yes as simple as that, works fine
