### ISSUE TITLE
Camera not opening up in iOS Chrome, but it works in Safari and Android Chrome, Desktop browsers etc

### ISSUE THREAD

**Issue by iamntg** [serratus/quaggaJS#413]
Hi,

The camera prompt is not showing, camera not opening in iOS Chrome browser.
 but the same is working well in safari, android and desktop browsers.

while inspecting chrome in iOS, 
Error showing as: 
`**ERROR** Can't get user media, this is not supported.`

The same works well in chrome,
I believe safari and chrome shares the same engine, not sure why this issue happens only in Chrome.

Anybody have any solutions for this?

**Comment by iamntg** [comment]
Update:
Checked with Firefox, Opera and Edge in iOS, all having same issue as Chrome.

Dont know whether iOS gives camera access to safari only. 

is there a work around for this?

**Comment by ericblade** [comment]
There is not. Application based webviews do not have access to getusermedia in iOS presently. All web browsers on iOS but safari are descendents of the provided webview, and cannot provide camera access.

You'll have to use safari or some sort of phonegap / Cordova plugin that gives native access.
