### ISSUE TITLE
Modern phones have multiple environment facing cameras.. Quagga picks wrong one

### ISSUE THREAD

**Issue by gregbengis** [serratus/quaggaJS#414]
Need ability to specify which camera to use beyond 'environment' and 'user'

**Comment by ericblade** [comment]
Query the devices using Quagga.CameraAccess.enumerateVideoDevices i believe the function is called, and then you can specify a deviceId instead of a 'environment' or 'user'.

**Comment by gregbengis** [comment]
I did try that, I had a drop down of 4 cameras I could choose from, but
each unique deviceId bought up the same camera

**Comment by ericblade** [comment]
I guarantee that that is not a problem with the library itself, as I use this function every day -- can you post your Quagga.init() configuration?  Also might help to say what kind of device, though I'm not really in depth familiar with anything other than the 2 that I've used Q with routinely, a N5 and a G6... 

On my G6, there are two rear cameras and a front, one of the rears is wide-angle, and can't read anything barcode like at all, and that's the default 'environment' camera, so i definitely use the deviceId constraint exclusively.

**Comment by gregbengis** [comment]
I have tested it again, and each option pulls up the front facing camera! only 'environment' chooses a rear.
I'm using a Huawei P30 Pro.
I've tried other JS solutions as a result, and they all show a different camera for each deviceId as expected..
Here is my config:
`
{
                    inputStream: {
                        name: "Live",
                        type: "LiveStream",
                        constraints: {
                            height: this.height,
                            width: this.width,
                            facingMode: this.selectedCamera
                        },
                        target: document.querySelector('#interactive')
                    },

                    decoder: {
                        readers: ["code_39_reader", "code_39_vin_reader"],
                        multiple: false
                    },
                    locate: true
                }
`
Sorry, I am not sure how to make JSON format nicely here..

**Comment by ericblade** [comment]
You want to replace the 'facingMode' key with 'deviceId' i believe is the name for the key used in constraints to ask for a specific camera.  

https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints

to format code in github, surround it with three backticks ( ` )

**Comment by gregbengis** [comment]
Thank you, that did the trick! Sorry for late response.

**Comment by TravBradfield** [comment]
I am able to get a list of cameras and then use the correct one. But how do you display this to your users? There isn't much information about what each camera is or how to programmatically select which to use. 

Please let me know if you had better luck?

**Comment by ericblade** [comment]
Unfortunately, my experience with cell cameras is that it tends to return something like "device 0" and "device 1" for the valid camera names, if not just the hex ID of the device.  It's pretty crappy.  In Windows, the enumerateDevices call returns the actual names of the devices.

I use a form select element to get the user's choice (this is from a laptop PC that presently has a built-in camera, and a VCR connected to it, no external cameras)

![image](https://user-images.githubusercontent.com/1451847/88862045-4dae7080-d1cd-11ea-9273-1564dbe57528.png)
