### ISSUE TITLE
When changing orientation localization area disappears

### ISSUE THREAD

**Issue by ajess33** [serratus/quaggaJS#415]
Quagga - 0.12.1
React - 16.11.0

So I have a localization area setup but when I change the screen orientation the area (box) never renders again.

I thought stopping Quagga and then re-initializing each time the screen was resized would fix this issue but it didn't seem to do it. Quagga does re-init when resizing, the area is just gone and I can no longer scan anything.

I feel like this shouldn't be happening if I am re-initializing each time.

Does anyone have any ideas on how to achieve this?

**Comment by ericblade** [comment]
what did you figure out?

**Comment by ajess33** [comment]
> what did you figure out?

I realized I wasn't stopping Quagga correctly. Once I fixed that the barcode area would re-render to correct dimensions. Do you know of any other way to update the size without having to reinit?

**Comment by ericblade** [comment]
That, I don't know, a lot of that is handled in initalization, so I doubt there's a way to resize the live area . . . worthy of a feature request, though...
