### ISSUE TITLE
Quagga.decodeSingle not running at all

### ISSUE THREAD

**Issue by Jarmahent** [serratus/quaggaJS#416]
I have:   (Reader = base64 image)
```
  function  scanImage(reader){
      // convert image file to base64 string
      console.log("Running scanner")
      Quagga.decodeSingle(
        {
          decoder: {
            readers: ["code_39_reader"] // List of active readers
          },
          locate: true, // try to locate the barcode in the image
          src: reader.result // or 'data:image/jpg;base64,' + data
        },
        function(result) {
          console.log("Results run")
        }
      );
    },
```

I run `console.log("Running scanner"` it logs when i call the function but thats it nothing else happens. I have no idea what it was working but all of a sudden it just stopped working.

**Comment by Jarmahent** [comment]
This was an issue with `reader.result` being empty. There should really be error handling for if the input is empty.

**Comment by ericblade** [comment]
feel free to file a request for improvement at https://www.github.com/ericblade/quagga2
