### ISSUE TITLE
QuaggaJS and Angular

### ISSUE THREAD

**Issue by camp0sfer** [serratus/quaggaJS#422]
I'm looking at a QuaggaJS examples. But looking at the examples, I'm not sure how to adapt it to Angular. Can someone post something?

**Comment by Josee9988** [comment]
https://www.npmjs.com/package/ngx-barcode-scanner#demo it is mainly made with quagga

**Comment by camp0sfer** [comment]
I've tried use this one but doesn't have demo and examples, I dont know how to use :(

**Comment by Josee9988** [comment]
> I've tried use this one but doesn't have demo and examples, I dont know how to use :(

The readme.md has a complete angular demo. Simply copy and paste into a new component and it'll magically work :open_mouth: @Fernyan

**Comment by camp0sfer** [comment]
I tried again and work! Tks for the response ❤️
