### ISSUE TITLE
Able to squeeze it down to under 10MB?

### ISSUE THREAD

**Issue by JPSeabury** [serratus/quaggaJS#437]
I'm trying to implement a barcode scanner using quaggaJS in Salesforce. Salesforce limits the size of downloadable static resources to 10MB. The current quaggaJS library is just over 18MB.

Is there a slim / skinny version available?

**Comment by ericblade** [comment]
Not sure where you're seeing that -- in quaggajs, the minified browser lib is only 92Kb, and the node lib is just a bit over 1Mb.  Even in my fork, which has a much larger output, it's only 280Kb minified, and node lib is a bit over 1.2Mb.  (i do need to figure out if there's a way i can decrease that...)

**Comment by JPSeabury** [comment]
Thanks. PEBKAC.
