### ISSUE TITLE
We have tested IOS 14 safari, chrome, issues.

### ISSUE THREAD

**Issue by Orinwebsolutions** [serratus/quaggaJS#443]
**Tested url** : https://serratus.github.io/quaggaJS/examples/live_w_locator.html

- iPad mini 4 (IOS- 14.0.1)
 > Chrome (version - 85.0.4183.109)
  > Error
![error 1](https://user-images.githubusercontent.com/24728173/95167730-d220ff00-07cd-11eb-9cd9-0db08eaf9354.jpeg)
  > Opening view
![image 1](https://user-images.githubusercontent.com/24728173/95167744-db11d080-07cd-11eb-82c8-65cfe97c6f1d.jpeg)
 > Safari (Version 14)
  > Camera too much zoom in
![image 2](https://user-images.githubusercontent.com/24728173/95167769-e6fd9280-07cd-11eb-8d96-b42a058791ac.jpeg)

- iPhone 6s (IOS 13.7)
 > Safari (Version 13)
  > Working
  > Chrome (version - 85.0.4183.109)
  > Error
![error 2](https://user-images.githubusercontent.com/24728173/95167794-ef55cd80-07cd-11eb-8a3a-6ec39a9d3ceb.PNG)
  > view 
![image 3](https://user-images.githubusercontent.com/24728173/95167816-f67cdb80-07cd-11eb-8033-bbc38e22ec9f.PNG)
 > Firefox (version 28.2)
  > Same as Chrome

**Tested URL** : https://serratus.github.io/quaggaJS/v1.0.0-beta.1/examples/scan-to-input/

- iPad mini 4 (IOS- 14.0.1)
 > Safari (working)
 > Chrome (not working)
![image 1](https://user-images.githubusercontent.com/24728173/95167906-12807d00-07ce-11eb-99d3-2c76d0ceb9e2.jpeg)
  > Error
![image 3](https://user-images.githubusercontent.com/24728173/95167932-1dd3a880-07ce-11eb-9aee-ff7dd3b6a3d4.PNG)

**Comment by Tezting** [comment]
Hi,
We also have issues with latest Safari on iOS and Mac.
It seems that beta1 works fine. But there is no real documentation on it.

If someone finds a solution please share it.

**Comment by Orinwebsolutions** [comment]
Hi Team seem like some Tezting provide some solution for IOS14 safari((https://github.com/serratus/quaggaJS/issues/444#issuecomment-704243664)). But still for IOS chrome have issue.

**Comment by ericblade** [comment]
Chrome will never work in iOS until they (Apple) allow WebView to access the camera.
