### ISSUE TITLE
Stopped working after upgrade to Safari 14.0 and iOS 14

### ISSUE THREAD

**Issue by Tezting** [serratus/quaggaJS#444]
Hi,
Our implementation has been stable and working for years.
But after upgrading to latest Safari on Mac and latest iOS on iPhone the plugin does not work correctly anymore.

This is how it looks in our app and when we visit the demo page:
https://serratus.github.io/quaggaJS/examples/live_w_locator.html

<img width="1073" alt="Screenshot 2020-10-06 at 14 24 06" src="https://user-images.githubusercontent.com/3736129/95201321-0b626a80-07e0-11eb-947c-af3c49e6b0dd.png">

Beta1 works fine...

**Comment by Tezting** [comment]
Found the problem:
aspectRatio: {min: 1, max: 100},

If I remove that line, everything works... Why is this now broken?

**Comment by ericblade** [comment]
This is making me think that iOS 14 is responding unexpectedly, and quite possibly incorrectly, to the constraints requests passed in by getUserMedia.  @Tezting do you have any other constraints in your config?
