### ISSUE TITLE
Pure Js

### ISSUE THREAD

**Issue by GatorN8r** [serratus/quaggaJS#447]
Can this be converted into a pure js app

**Comment by ericblade** [comment]
What does that mean?

**Comment by GatorN8r** [comment]
sorry if this came off as vague, this project is currently using a framework and i assume angular, im currently running a project based soley on knockout js so hence asking if this application can be converted into a pure javascript or jquery application, i know typescript is javascript i just need to know if i tried to replicate calling all the libraries the project requires will i not run into a dead end whereby there are some underlying support from the framework.

**Comment by ericblade** [comment]
This is a javascript library, that you can include into pretty much anything, node or browser.  Some of the examples use jquery and some other things I'm not familiar with, but you don't need those to make it work.  You can just use a script tag to load the code, and run with it like that, if you'd like.

There are people using this in Angular, React, and more, as well as just "plain" html/js
