### ISSUE TITLE
How do I determine from the result set (or other means) what type of barcode was read?

### ISSUE THREAD

**Issue by madmanpierre** [serratus/quaggaJS#45]
In my current test case, I have told it to allow readers: ["code_128_reader", "ean_reader", 'code_39_reader'] 
I am getting back some quirky results, and when I look at the result.codeResult.code I see that I need to strip off start and stop bits on some formats. So I think I need to know - does Quagga think it read a code 128, or an EAN or a 39? so I can post process (and debug) --- currently my test camera is getting some interesting barcode readings from the row of books behind me. Sometimes in the Detected Callback I'm getting a 0 length code, other times 2 or 3 characters. Other times proper EAN etc.., readings.
Is the format of the code read somewhere in the result object? (codeset is always returning "" even on 'good reads' - that is where I thought I might be expecting to see which format was 'located'.)
If this isn't clear, I'll try to explain better!

**Comment by serratus** [comment]
Good question indeed. To be honest, I usually focus on reading only one type of barcode at a time, so this problem did not surface yet. Having the type of barcode in the result is really useful metadata. I'll try to come up with a good solution for that. Thanks for pointing that out!

Start and stop bits should all be stripped from the actual result you get in ``result.codeResult.code``. I'll review the code again to make sure this isn't present anywhere.

**Comment by serratus** [comment]
In the current release, the ``result.codeResult`` now contains a new field called ``format`` which is set to one of the following:
- code_12
- code_39
- codabar
- ean_13
- ean_8
- upc_a
- upc_e

**Comment by madmanpierre** [comment]
Thanks, I'll test this tomorrow. This also gives another benefit: I can let my users check the barcodes they need to read, tell them what format it is, and then restrict the reader in the future to just the formats they require. (While *I* can tell many of these apart by a quick look - most users will not be able to.)

**Comment by madmanpierre** [comment]
For people reading this thread later ... the 1st listed format returned is code_128, not code_12

**Comment by madmanpierre** [comment]
Can I confirm the following statement:

**Comment by serratus** [comment]
Thanks, I updated the post and corrected the typo (`code_128`).
For EAN & UPC codes, the result is only returned if the checksum is valid, and returns the code including the check digit. The calling code does not need to confirm the check digit, but can strip it if desired.
