### ISSUE TITLE
UNA GRANDE MERDA

### ISSUE THREAD

**Issue by x3n0peltis** [serratus/quaggaJS#451]
CODICE MAL COMMENTATO, NIENTE TYPE, UNA MERDA NON VI MERITATE NEANCHE CHE LO TRADUCA IN INGLESE STO MESSAGGIO
![jojo_doggo](https://user-images.githubusercontent.com/58561122/101998911-cf63ee00-3cd7-11eb-830a-5eecefb916c6.png)

**Comment by sebdisdv** [comment]
par mi non funsiona mia tanto

**Comment by euberdeveloper** [comment]
XENO SAMA

**Comment by euberdeveloper** [comment]
NAIMOLI

**Comment by euberdeveloper** [comment]
@CarloZanotto

**Comment by euberdeveloper** [comment]
Never seen a code like that 
![Bocelli_PP](https://user-images.githubusercontent.com/33126163/101999734-48674380-3ce0-11eb-84f1-9aeb3690b723.jpeg)

**Comment by ericblade** [comment]
This is not helpful, but you concern is appreciated.
