### ISSUE TITLE
Uncaught TypeError: t.readers.forEach is not a function

### ISSUE THREAD

**Issue by NickScriwanek** [serratus/quaggaJS#456]
I'm getting this error in my console log: Uncaught TypeError: t.readers.forEach is not a function.
The camera feed works, but I'm not getting any data in my console logs when reading the EAN-13 codes.

My code:
```
Quagga.init({
        inputStream : {
          name : "Live",
          type : "LiveStream",
          target: document.querySelector('#barcode-scanner')    // Or '#yourElement' (optional)
        },
        decoder : {
          readers : "ean_reader"
        }
      }, function(err) {
          if (err) {
              console.log(err);
              return
          }
          console.log("Initialization finished. Ready to start");
          Quagga.start();
      });

      Quagga.onDetected(function(data){

        console.log(data);
```

**Comment by ericblade** [comment]
looks like it works here? https://codepen.io/ericblade/pen/wvzxPLB

that is using my fork, but it should work identically.  i do have quite a difficult time with getting quagga to detect a barcode at all on my laptop camera, though, so maybe it's failing for you in a way i'm not hitting.

**Comment by NickScriwanek** [comment]
It doesn't even get through the initialization for me, I attached a screenshot for the console when I run the Codepen.
![image](https://user-images.githubusercontent.com/60963760/104088236-8c108700-5265-11eb-823f-40eed6336008.png)

The following image is my console with the full quaggajs instead of the minified version.
![image](https://user-images.githubusercontent.com/60963760/104088385-d3e3de00-5266-11eb-9a51-4c57f8199486.png)

**Comment by ericblade** [comment]
hmm. that just .. doesn't make much sense.  that same pen works fine here.  Only thing i can think of is somehow the readers config isn't valid for you, which doesn't make sense, or that you're using a really ancient version of Chrome, which probably also doesn't make sense.    Any chance you could break on the error, and find out what the 'config' object in question looks like?

**Comment by NickScriwanek** [comment]
I deleted all of my chrome extensions to see if that's the problem, but I'm still getting this error.

![image](https://user-images.githubusercontent.com/60963760/104123867-c9e8da80-534d-11eb-8258-a345ee25b027.png)
![image](https://user-images.githubusercontent.com/60963760/104123939-3fed4180-534e-11eb-919a-1d490be820e0.png)
That is where the error is apparently.

I wouldn't mind having a discord call if you're up for it, I think that would make communicating a lot easier.

**Comment by ericblade** [comment]
well, so, readers is supposed to be a string array (or array of QuaggaJSReaderConfig).  It still doesn't fail for me in init() with it being a string.. but.. i think that's where your problem is..

**Comment by NickScriwanek** [comment]
I found the issue.  readers: "ean_reader" in the code should be  readers: ["ean_reader"]. Not sure why it should be an array if it's only one reader, but thanks for your help!

**Comment by ericblade** [comment]
> I found the issue. readers: "ean_reader" in the code should be readers: ["ean_reader"]. Not sure why it should be an array if it's only one reader, but thanks for your help!

it was like that when i found it. :-)  i'm also not a big fan of adding additional code to parse "string | Array<string>".  I'll make a note that we should check that and call it an error, though.
