### ISSUE TITLE
file_input works on your example site, not with local example code. 

### ISSUE THREAD

**Issue by attentiondotnet** [serratus/quaggaJS#46]
Hi. When I use your site and select an image, here, http://serratus.github.io/quaggaJS/examples/file_input.html I am  able to get the code from the image, but when I use the file_input.js, quagga.js and the file_input.html code locally, I am not able to decode the image. The image is being processed, but I never get to the onDetected event. Am I missing something, or is there a way to debug the process? 

Thanks

**Comment by serratus** [comment]
@attentiondotnet How did you solve the problem? Maybe some security-restrictions when using ``file://`` protocol?
