### ISSUE TITLE
iOS 14, no camera's available.

### ISSUE THREAD

**Issue by Jelmer7** [serratus/quaggaJS#460]
On iOS14 there seem to be no camera's available, also the canvas or output element seems to get an infinite (or atleast a rediculous) height.
iOS13 works fine.

Tested using your example page on an Iphone 11, 12 (iOS 14), in combination with your example page.

![image](https://user-images.githubusercontent.com/15048772/110293640-20d9fb80-7fef-11eb-9931-a1bf85375408.png)

**Comment by ericblade** [comment]
iOS 14 seems to have given some bizarre meaning to the commonly used aspect ratio settings 'min' 1 'max' 100, and screws things up pretty hard.

Also, still only works in Safari, I think, but getUserMedia() is being exported to app context and will be available in alternate browsers and html based iOS apps in a future update? 14.something?

**Comment by Jelmer7** [comment]
Thanks for the quick response! I indeed had set `aspectRatio: {min: 1, max: 100},` and the customer was using an alternative browser.

**Comment by ericblade** [comment]
https://github.com/ericblade/quagga2/issues/283

looks like 14.3 beta contains support for Chrome / apps / alterna-browsers / etc to use getUserMedia!

aspectRatio should be significantly less than max 100.  I'm honestly not sure what is best, i just don't even use that constraint anymore.  min 1 max 2 seems to work?  probably not necessary.
