### ISSUE TITLE
Error handling - swallowed up (displayed on console) - how do I find out?

### ISSUE THREAD

**Issue by madmanpierre** [serratus/quaggaJS#47]
I notice that, if I disconnect my camera, line 8078 throws a console.log(e) but my code doesn't seem to get a chance to be notified of it and/or notify my user.

Am I missing a way? If I'm not, could you allow for an optional error call back function as well for those of us who want to notify our users or take appropriate action?

**Comment by serratus** [comment]
You mean physically disconnecting the camera, or by software means? I'll look into that.

**Comment by madmanpierre** [comment]
Physically. It was a USB camera.

**Comment by serratus** [comment]
[Quagga.init()](https://github.com/serratus/quaggaJS#quaggainitconfig-callback) now receives an error as first argument which can be used to determine the cause of the error. For example, if the constraints cannot be met (e.g.: if the device has no camera) or if the browser does not support this feature. Could you please retry and close the issue?

**Comment by madmanpierre** [comment]
worked for me. And I've updated the d.ts to match so when we pull it in it will have it.
