### ISSUE TITLE
Strange behavior in IOS 14 

### ISSUE THREAD

**Issue by szamszara** [serratus/quaggaJS#470]
Hello,

Works great with android, but I found a strange behavior in IOS 14.
I attach two screenshoots.

1. In landscape mode, the camera works, but only a tiny line shows
2. In portrait mode, the camera works, but zoom in too much, so nothing seen.

Can you fix it?
Thanks,

![IMG_0497](https://user-images.githubusercontent.com/65263583/117960373-36381280-b31d-11eb-889e-65c74f4eb017.jpg)
![IMG_0499](https://user-images.githubusercontent.com/65263583/117960391-3a643000-b31d-11eb-9c9c-036de29617d3.jpg)

**Comment by ericblade** [comment]
I don't have the ability to change the live demos, but if you're having this problem yourself, then you need to remove the line that sets aspect ratio to max: 100

**Comment by szamszara** [comment]
Thanks, it is working now.
If I remove this line:
`//aspectRatio: {min: 1, max: 100},`
it will not cause trouble in another way e.g. for android, etc.

**Comment by ericblade** [comment]
it shouldn't. it's unkown why iOS 14+ respond with absolutely useless aspect ratio when given that.
