### ISSUE TITLE
Question: Is this project still maintained? 

### ISSUE THREAD

**Issue by ghevge** [serratus/quaggaJS#489]
Hey, I'm looking for a javascript bar code scanner library, and I stumbled over this project, but from what I can see its last release was way back in 2017. 

So my  question is: should I pick this library or shall I look for another one, which is actively maintained?

Thanks

**Comment by ericblade** [comment]
Until Serratus decides to return, or designates some other official continuation, I maintain a fork at https://github.com/ericblade/quagga2

**Comment by ghevge** [comment]
@ericblade  Thanks for letting me know! I will switch to quagga2!

**Comment by ghevge** [comment]
Maybe you should put a note on the quagga README file to redirect users to quagga2. 
For some reasons,  Google didn't provided any references to quagga2, when searching for barcode reader javascript libs

**Comment by ericblade** [comment]
I don't want to make it appear that Serratus officially supports my fork as a continuation, unless he voices that opinion.

**Comment by ghevge** [comment]
Just create a pull request and assign it to him.  You will find out that way his opinion :)

**Comment by ghevge** [comment]
@serratus what's your opinion regarding my request above?
