### ISSUE TITLE
init with video element

### ISSUE THREAD

**Issue by jtn-d** [serratus/quaggaJS#52]
Would be it possible add init variation that takes video element as one argument, e.g. initWithVideo : function(config, cb, video)?

Current implementation queries #interactive.viewport from document and further video, which doesn't work with Shadow DOM (web components).

              var $viewport = document.querySelector("#interactive.viewport");
              if ($viewport) {
                video = $viewport.querySelector("video");
                if (!video) {
                  video = document.createElement("video");
                  $viewport.appendChild(video);
                }
              }

I would nice to utilise this great library to implement e.g. Polymer element.

**Comment by serratus** [comment]
Thanks for pointing that out. I have that on my todo-list for ages now, but it haven't had much priority yet. That's going to change and I'll try to come up with a solution that suits most users. My idea is, to include the element to the `config` object, either as a DomNode, or even selector. I guess you are looking for a way to pass in a Video-element as a DomNode, right?

**Comment by jtn-d** [comment]
Yes, exactly. So it would be caller's responsibility to layout and style elements and pass them to library.

**Comment by serratus** [comment]
Fixed by #89
