### ISSUE TITLE
Edge Browser

### ISSUE THREAD

**Issue by madmanpierre** [serratus/quaggaJS#56]
When you're ready to start testing with Edge, let me know. At this point I'll just say it doesn't work for us, and I'll gather you a better error description when you're ready to work on it (in case there are any quick updates from MS over the next few days.) Note: According to MS, it 'should' be working in Edge. A bug report I submitted in IE 11 came back to me last week as 'good news, it's fixed and working in Edge'. And the errors are the same in debug mode and when using web workers - I mention this because I am told that the web worker method you are using wouldn't have worked even if the user media object did.

**Comment by serratus** [comment]
Thanks for reporting back the issues with Edge. I'm still undecided if I should update my machine to Windows 10 or not. I'd rather test it in a VM first, and then upgrade if necessary. Do you already have experience with Edge so far? Have you already used the beta?

**Comment by madmanpierre** [comment]
I did *not* use the beta. I kept planning on having one or two machines use the beta but just never had the time.

 

We have updated about 6 developer computers around the world to it.

 

I should mention first that I hate ‘feature and options denuded iCrap style Metro apps’ and I have bitterly disliked how Windows 8 and (admittedly to a lesser degree Windows 8.1) take away all sorts of power and replaced it with iCrap apps. And how they made multi-monitor systems (I have up to 6 per computer) a real pain to use with all their touch screen ‘make it hard to use a mouse’ interruptions (and I do have a touch screen on my multi-monitor and several others so it’s not that I don’t use touch screens.)

 

Having said that, I own over 100k in MS stock so I am not a MS hater – I’m just a Metro/iCrap-App hater. :)

 

Ok, with my biases clearly stated:

 

Summary: I love Windows 10. 

 

It is not perfect, I’ve run into a couple minor problems (weird one: I have SO many apps that can read jpg that their dialog box won’t let me set my default one !!)

 

But overall, I am really liking Windows 10. It’s what Windows 8 SHOULD have been.

 

We have 2 computers that we have tried to upgrade to 10 that haven’t worked yet. One we don’t know why – it is only a 3 month old computer. A second we know why – there is a Win 8 driver that is failing to upgrade and until I get around and cancel that upgrade or we get the upgrade to go through Win 10 silently just tells me to be patient (so I would argue the error – technically lack of error – is underwhelming.)

 

But on none of them did Windows 10 cause any problems.

 

My senior developer was getting ready to put Win 10 in a VM, but after 2 days of asking me about the 3 or 4 computer I had upgraded, he couldn’t wait and yesterday he upgraded his main dev machine (6 monitors as well) to 10 and that has allowed him to clean the drool out of his keyboard :)

 

About 5 months ago I stopped using IE as my primary browser and Chrome became my primary with Firefox my secondary. (The feature that tipped me over was when IE started having all sorts of the right hand scroll bars auto-disappearing after about 3 seconds, and since it took me about 3.5-4 second to read an average page, it meant I was constantly clicking on advertisements. I got so frustrated with it I made Chrome my primary browser.) And unlike most people, because of my ‘job’ I use lots of browsers every day – IE, Chrome, Firefox, Opera, SeaMonkey, iOS Safari, iOS Chrome, Android Chrome, Metro-iCrap-IE (yes my bias showing again) and occasionally OSX Safari. So my biases are based on lots of use of all of them, not based on using one and never really trying the others.

 

The Edge browser has become my personal favorite now. Other than the markup capability, it is little things, and it ‘looks’ the most modern/professional.

 

But having said all that, if you only have ONE main machine, I would suggest you first make a disk image to a ‘backup’ hard drive before upgrading to Win 10, just in case your experience is not as wonderful as ours has been! This is advice I give everyone (though since I have multiple computers and can switch between them if one fails, I did not follow that advice.)

 

Regards, peter

**Comment by serratus** [comment]
After a few hours of debugging and code-slicing I've finally sorted out the problem with web-workers in IE. From e5acf19e08c34ef4c63d95061810bc7781f2108e on, the Edge browser supports the same features as Chrome and Firefox in regards of Quagga, including `getUserMedia`.

Please report back any further issues, until I close this issue in the next few days.
