### ISSUE TITLE
Demo with live-stream does not work.

### ISSUE THREAD

**Issue by sbhandary** [serratus/quaggaJS#58]
I cant make the QuaggaJS example "Demo with live-stream"  work in chrome or IE. The browsers do support getUserMedia API call.

**Comment by binduks** [comment]
Hello 

Same for me too, live demo not working in chorme tried with workers 4 and 1 for EAN

**Comment by serratus** [comment]
What exactly does not work for you? Do you see errors in the console? Did you try on your mobile device, or desktop computer? Which operating system?
I just tried it in Chrome, and it works perfectly fine. IE is not yet supported, because I do not have Windows 10 installed.

**Comment by rodrigoAbril** [comment]
for me it detects the barcode but does not show the number,
OSX sierra, 
Google Chrome
