### ISSUE TITLE
 live stream  issues with EAN barcode-type

### ISSUE THREAD

**Issue by Dallou** [serratus/quaggaJS#63]
Hi. I'm having problems with decoding EAN barcodes with live stream. 

But I see in your examples that you succeed to decode this type with pictures. I don't understand why it doesn't code.  I haven't change any lines in the library.

**Comment by serratus** [comment]
What does your code look like? Which examples are you trying to run? Because those residing in the master branch might not work out of the box without configuring them correctly. Can you check if the configuration option `readers` includes `ean_reader`?

**Comment by Dallou** [comment]
For the moment, I try to run your example "Using the live-stream from your
webcam" (corresponding to the source code live_w_locator.html
<https://github.com/serratus/quaggaJS/blob/master/example/live_w_locator.html>
) and
i just made few changements in order to make a multiply-reader and it's
works. I check the configuration and i already includes the ean_reader.

 In my opinion, the problem come from the configuration.  I don't manage to
configure it correctly.  Can you explain how to do to configure the program
in order to detect the big EAN_13 such as the one i join to this mail.

2015-09-05 15:42 GMT+02:00 Christoph Oberhofer <notifications@github.com>:

**Comment by serratus** [comment]
I'm sorry, but I can't see an image attached to this issue. Can you maybe upload the image directly in here? 

Basically, if you want to decode big EAN-13 codes, you can set the `patchSize` to `large`, or even `x-large`. The best option would be to try it with a few static images and fiddle around with the configuration until it works for you. What kind's of barcodes are you trying to detect at the same time? the `readers` option accepts an array of reader-definitions. Given that you want to decode Code 128 and EAN-13, the configuration would look like the following:

```javascript
{
  inputStream: {
      type: "LiveStream",
      constraints: {
          width: 640,
          height: 480
      }
  },
  decoder: {
    readers: [
      'code_128_reader',
      'ean_reader'
    ]
  },
  locator: {
    patchSize: "large", // x-small, small, medium, large, x-large
  }
}
```
