### ISSUE TITLE
Does I need to add a video tag?

### ISSUE THREAD

**Issue by fpilee** [serratus/quaggaJS#64]
Sorry but I don't understand how to use this library. The livesteam example works online but I don't know how to use it.  

If i put this on my code I get undefined video on this part of you code:
....
    InputStream.createLiveStream = function(video) {
        video.setAttribute("autoplay", true);
....

Quagga.init({
    inputStream : {
      name : "Live",
      type : "LiveStream"
    },
    decoder : {
      readers : ["code_128_reader"]
    }
  }, function(err) {
      if (err) {
          console.log(err);
          return
      }
      console.log("Initialization finished. Ready to start");
      Quagga.start();
  });

**Comment by ericblade** [comment]
It seems that one needs to add an element within your page with id="interactive", class="viewport"

such as:
        <div style="width: 640; height: 480; background: white" id="interactive" class="viewport"></div>

It seems that the interface is a little bit odd, such as there's no way to independently control the video from the decoding, you can't pass in an element to attach the video to... a problem i'm trying to work out is that when video stops, i'm stuck with a big black empty space.. i might open a pull req on some of these changes, if maintainer would appreciate some API changes to make things line up in ways i would expect.. but then, i'm not always the best person for expecting things in ways that other people find sane, either ;)

**Comment by serratus** [comment]
@ericblade Thanks for answering this question. There is definitely room for improving the API. I'm not really sure how to separate it nice and clean from the DOM and all the dependencies. If you have a suggestions, or even a pull request, I would love to see your ideas. With that, even #52 might get resolved.

**Comment by ericblade-owo** [comment]
Sure, I spent a couple of hours trying to digest a way to get this into an app that would run on my phone for mass scanning of UPC codes.  It seems to work great on my N5, but I suspect that older slower phones are going to crawl with it.

I am unfortunately stuck with work and family things, so I'm not sure I'm able to contribute in the very near future, but if nothing's changed when I get back to it, then I'd be happy to submit any changes that I make for potential inclusion.  If I do anything, it would probably be adding new methods and possibly making additions or changes to some API signatures..

**Comment by serratus** [comment]
Alright then, I'll close this issue for now and continue working on #52.
