### ISSUE TITLE
Local context issue in windows 8.1 Cordova app

### ISSUE THREAD

**Issue by tyroneallen281** [serratus/quaggaJS#67]
I keep getting the following issue in my windows 8.1 Cordova app:
Can’t load <blob:206CFAF7-9077-4449-B2AE-961E738D4AE9>. An app can’t load remote web content in the local context.

Can you please give me help on solving this, I really need help asap. Tx

Extra info:
Uses Angular JS
Windows 8.1
Windows Phone  8.1

**Comment by serratus** [comment]
This error is most probably caused during the web-worker initialization. Just try to set `numOfWorkers: 0` and rerun your code. Do you get the same error on the desktop browser as well? IE 11 I presume?

**Comment by tyroneallen281** [comment]
Thanks that fixes the issue :)
