### ISSUE TITLE
File input demo is broken

### ISSUE THREAD

**Issue by j0sk** [serratus/quaggaJS#69]
I tried on Github.io site and with latest source code on my own server and I found that the results strip is not working.

How to reproduce:
1) Go to site: http://serratus.github.io/quaggaJS/examples/file_input.html
2) Add some barcode image
3) It detects the codeand green rectangle shows that everything is ok
4) But it should do more, to view results on top of the captured image. Following code is not working somehow?!

From file > file_input.html: This is place for details of scanned barcode.
```javascript
<div id="result_strip">
        <ul class="thumbnails"></ul>
</div>
```

From file > file_input.js: This javascript should add those details to the html file. 
```javascript
  Quagga.onDetected(function(result) {
        var code = result.codeResult.code,
            $node,
            canvas = Quagga.canvas.dom.image;

        $node = $('<li><div class="thumbnail"><div class="imgWrapper"><img /></div><div class="caption"><h4 class="code"></h4></div></div></li>');
        $node.find("img").attr("src", canvas.toDataURL());
        $node.find("h4.code").html(code);
        $("#result_strip ul.thumbnails").prepend($node);
    });
```

**Comment by serratus** [comment]
What kind of Barcode are you trying to scan? In case of the example page, the default type is set to decode only __Code 128__ and nothing else. A green rectangle (if you use a copy of my example) indicates only a possible barcode (which could not be decoded). Only if the rectangle turns blue, with a red scanline, the decoding process was successful.

**Comment by deepak-mind** [comment]
I have implemented one of my projects, it works well. I am using File Api.
But how can I auto focus only on bar code area while accessing by Mobile camera, means there should be an predefined rectangle while taking picture..

**Comment by ericblade** [comment]
you can turn locate off, and use the area configuration to define a portion of the viewing area that should be used for a specific area.  as far as autofocus goes, i think that some browsers support turning on/off autofocus,but i haven't found a camera yet that that works on.

**Comment by deepak-mind** [comment]
> you can turn locate off, and use the area configuration to define a portion of the viewing area that should be used for a specific area. as far as autofocus goes, i think that some browsers support turning on/off autofocus,but i haven't found a camera yet that that works on.

Okay let me try, do you have any example for this, could you please provide me If possible ? thanks
