### ISSUE TITLE
Documentation for config options

### ISSUE THREAD

**Issue by M3lkior** [serratus/quaggaJS#73]
Hi,

Your plugin is impressive, great job.
It is possible to document the config variables ? Today, i don't know what are the variables and when to use them.

**Comment by serratus** [comment]
Good point. I'll draft something up which then can improve further. Are you interested in something particular, or do you wish to have a documentation in general about all the configuration options?

**Comment by M3lkior** [comment]
Not in particular. It's just difficult to know how to configure your very good plugin without documentations ^^

**Comment by Nick-Ewer** [comment]
Seconded, I'm trying to use this for mobile and I'm having some trouble getting scanning working consistently, documentation for the config options would help me out quite a bit. Thanks!

**Comment by codeurge** [comment]
:+1 for docs

**Comment by serratus** [comment]
I've added documentation (0fbedf5f6169e3efb57951b114c6e12773c94c60) to most of the properties used within the `config` object. Feedback is very much welcome.

**Comment by M3lkior** [comment]
Thanks @serratus . I bring you a feedback as soon as possible.

**Comment by whatl3y** [comment]
Let me first second the "coolness" of this tool, it's worked nice so far in nodejs where I'm testing it!

Not sure this should be in this documentation issue, but can you add in the config a "debugging" or "logging" option to turn off what gets dumped out to the console when decoding a barcode? Here's what my output looks like, and it doesn't look like there's a way to disable it without commenting out the console.log() calls in the main code:

[ 3264, 2448, 4 ]
Patch-Size: {"x":10,"y":10}
FrameGrabber {"videoSize":[3264,2448],"canvasSize":[800,600],"stepSize":[4.08,4.
08],"size":[800,600],"topRight":{"x":0,"y":0}}
{ x: 800, y: 600 }
Before registering reader:  code_128_reader
Before registering reader:  ean_reader
Before registering reader:  upc_reader
Before registering reader:  codabar_reader
Before registering reader:  i2of5_reader
Registered Readers: {"format":"code_128","config":{}}, {"format":"ean_13","confi
g":{}}, {"format":"upc_a","config":{}}, {"format":"codabar","config":{}}, {"form
at":"i2of5","config":{"normalizeBarSpaceWidth":false}}
