### ISSUE TITLE
Some C39 barcodes not recognised

### ISSUE THREAD

**Issue by sammyblackbaron** [serratus/quaggaJS#74]
Hi,

C39 barcodes generated from most sources seem to work and are scanned by QuaggaJS without trouble:
http://www.racoindustries.com/barcodegenerator/1d/code-39.aspx, for example, works fine.

However, TCPDF's C39 generation doesn't seem to play with QuaggaJS:
http://www.tcpdf.org/examples/example_027.pdf

We have been generating PDFs with C39 barcodes for years using this popular PHP library and have no problem scanning them with phones and dedicated laser barcode scanners.

Can you help shed any light on why the barcodes generated from TCPDF aren't compatible?

Many thanks - especially for this amazing code!

**Comment by serratus** [comment]
I just printed out the example pdf you linked to. As you can see in the following screen, all four Code-39 variations work just fine. Do you use a check-digit? Do you have any other examples that do not work for you? How many characters does your usual code-39 barcode consist of?

<img width="486" alt="code-39-success" src="https://cloud.githubusercontent.com/assets/1381822/10856125/c2199416-7f45-11e5-8434-feb370810e08.png">

**Comment by sammyblackbaron** [comment]
Many thanks for getting back to me.  We don't use check-digit and we usually have around 8-11 digits in the barcode.  Attached is an example of a C39 barcode that isn't working with Quagga.  If you can help with this, I'd really appreciate it.

Thanks
![tr105596-0](https://cloud.githubusercontent.com/assets/3033242/10936526/120f81fe-82e5-11e5-91e9-b93a30789928.jpg)

**Comment by serratus** [comment]
I just played around with your example, and it works for me. What exactly does not work? Which browser do you use? Does the barcode even get outlined?
<img width="696" alt="tr105596" src="https://cloud.githubusercontent.com/assets/1381822/11170987/14a3c2d8-8be4-11e5-8eb6-56078b8e5bb2.png">
