### ISSUE TITLE
Code128 Barcode recognized with error

### ISSUE THREAD

**Issue by victorfugita** [serratus/quaggaJS#76]
I was testing Quagga.JS with my application and was working fine, but yesterday i got a barcode which isn't been recognized properly.

![1510538](https://cloud.githubusercontent.com/assets/6080320/10667434/29101b36-78b6-11e5-8867-185853f2f4d5.jpg)

![1510538_2](https://cloud.githubusercontent.com/assets/6080320/10667507/7d3ab5f4-78b6-11e5-8c19-005921b25f39.jpg)

The plugin's output for this barcode is '151053', missing the last '8'. Is this an issue with the plugin?

Thanks in advance.

**Comment by serratus** [comment]
Thanks for reporting this bug. It's actually an issue within quagga, which is caused by dropping a certain range of characters if they are part of the checksum. I already have a quick-fix at hand, but I'll try to find a better solution, since it should not affect any other barcodes.
