### ISSUE TITLE
Config unclear

### ISSUE THREAD

**Issue by DNWEIJ** [serratus/quaggaJS#77]
Please document the config better, since it is difficult to find out what all options are doing / are for.

**Comment by brendensoares** [comment]
I'm also finding issues understanding what the config needs to be. The process so far has been painful as it requires me to dig into the source to decide what I need to be doing.

So, better docs with more functionality coverage is needed.

**Comment by serratus** [comment]
Thanks for the feedback. Please provide me some of your issues where I could start building up the documentation. I have too little information on where people have the most difficulties with and what the use-cases are. I would appreciate some input here. Thanks

**Comment by brendensoares** [comment]
I had some trouble integrating with React and debugging scans. Part of that is my lack of experience and the other part of lack of docs. It seems there are less docs around the `imageStream` option.

Your answer on #108 was helpful.
