### ISSUE TITLE
Options keyboard

### ISSUE THREAD

**Issue by smartmeter** [serratus/quaggaJS#80]
Hi, thanks for the work and this lib. On the main wiki page, I was unable to find the option to read/hook barcode reader scan from handheld scanner like HID etc.

**Comment by serratus** [comment]
I'm not sure if I understand your question correctly. Are you asking if, instead of camera/image input, quagga could read raw data input from a handheld scanner (HID-USB)? No, that's not in the scope.

**Comment by smartmeter** [comment]
Yes please I was asking if Quagga can detect and acquire that to the text box in the browser.

**Comment by serratus** [comment]
This could be done in another project, but not in the scope of QuaggaJS.
