### ISSUE TITLE
VIN bar codes detection is poor

### ISSUE THREAD

**Issue by sasnong** [serratus/quaggaJS#82]
I tried with a couple of vin bar codes and only once it worked to detect the VIN but on all other images its not detecting.
Is this a known issue ?

I tried the input file upload , see attached for failures 

![20151217_112956](https://cloud.githubusercontent.com/assets/1695673/11900301/aecfec48-a56a-11e5-8ab6-32286a73a780.jpg)
![20151217_135044](https://cloud.githubusercontent.com/assets/1695673/11900304/b1fd56b2-a56a-11e5-8da1-9010ef58b746.jpg)

**Comment by serratus** [comment]
Thanks for your feedback. Reading VIN barcodes is very challenging, because of the following reasons:
1. Density is really high
2. therefore the image must be of high quality
3. Widths of bars often not distributed regulary

I've tried to decode your images and with some adjustment of the parameters I could get them to work. However, I had to crop the second image to make it work. In such cases I would recommend to turn of the localization feature (`{locate: false}`), increase the image quality to 1280 or more and try to scan it aligned to the viewport.

Even though I had localization activated the following images show the results of my scans:
![vin-win-01](https://cloud.githubusercontent.com/assets/1381822/13795376/b6253148-eb00-11e5-834e-16c2f44a86b6.png)
![vin-win-02](https://cloud.githubusercontent.com/assets/1381822/13795378/bb413e74-eb00-11e5-90c5-f0a9b1ee3daa.png)

**Comment by jamsshhayd** [comment]
Was this issue resolved? I am having the same problem with VIN numbers. I am specifying all the barcode types in the decoder object. Here is the snippet that I am using:

`/**Quagga initialiser starts here*/

$(function () {
    var value;
    var App = {
        init: function () {
            Quagga.init(this.state, function (err) {
                if (err) {
                    console.log(err);
                    return;
                }
                App.attachListeners();
                Quagga.start();
            });
        },
        initCameraSelection: function () {
            var streamLabel = Quagga.CameraAccess.getActiveStreamLabel();

            return Quagga.CameraAccess.enumerateVideoDevices()
                .then(function (devices) {
                    function pruneText(text) {
                        return text.length > 30 ? text.substr(0, 30) : text;
                    }
                    var $deviceSelection = document.getElementById("deviceSelection");
                    while ($deviceSelection.firstChild) {
                        $deviceSelection.removeChild($deviceSelection.firstChild);
                    }
                    devices.forEach(function (device) {
                        var $option = document.createElement("option");
                        $option.value = device.deviceId || device.id;
                        $option.appendChild(document.createTextNode(pruneText(device.label || device.deviceId || device.id)));
                        $option.selected = streamLabel === device.label;
                        $deviceSelection.appendChild($option);
                    });
                });
        },
        querySelectedReaders: function () {
            return Array.prototype.slice.call(document.querySelectorAll('.readers input[type=checkbox]'))
                .filter(function (element) {
                    return !!element.checked;
                })
                .map(function (element) {
                    return element.getAttribute("name");
                });
        },
        attachListeners: function () {
            var self = this;

            self.initCameraSelection();
            $(".controls").on("click", "button.stop", function (e) {
                e.preventDefault();
                Quagga.stop();
            });

            $(".controls .reader-config-group").on("change", "input, select", function (e) {
                e.preventDefault();
                var $target = $(e.target);
                // value = $target.attr("type") === "checkbox" ? $target.prop("checked") : $target.val(),
                value = $target.attr("type") === "checkbox" ? this.querySelectedReaders() : $target.val();
                var name = $target.attr("name"),
                    state = self._convertNameToState(name);

                console.log("Value of " + state + " changed to " + value);
                self.setState(state, value);
            });
        },
        _accessByPath: function (obj, path, val) {
            var parts = path.split('.'),
                depth = parts.length,
                setter = (typeof val !== "undefined") ? true : false;

            return parts.reduce(function (o, key, i) {
                if (setter && (i + 1) === depth) {
                    if (typeof o[key] === "object" && typeof val === "object") {
                        Object.assign(o[key], val);
                    } else {
                        o[key] = val;
                    }
                }
                return key in o ? o[key] : {};
            }, obj);
        },
        _convertNameToState: function (name) {
            return name.replace("_", ".").split("-").reduce(function (result, value) {
                return result + value.charAt(0).toUpperCase() + value.substring(1);
            });
        },
        detachListeners: function () {
            $(".controls").off("click", "button.stop");
            $(".controls .reader-config-group").off("change", "input, select");
        },
        setState: function (path, value) {
            var self = this;

            if (typeof self._accessByPath(self.inputMapper, path) === "function") {
                value = self._accessByPath(self.inputMapper, path)(value);
            }

            self._accessByPath(self.state, path, value);

            console.log(JSON.stringify(self.state));
            App.detachListeners();
            Quagga.stop();
            App.init();
        },
        inputMapper: {
            inputStream: {
                constraints: function (value) {
                    if (/^(\d+)x(\d+)$/.test(value)) {
                        var values = value.split('x');
                        return {
                            width: { min: parseInt(values[0]) },
                            height: { min: parseInt(values[1]) }
                        };
                    }
                    return {
                        deviceId: value
                    };
                }
            },
            numOfWorkers: function (value) {
                return parseInt(value);
            },
            decoder: {
                readers: function (value) {
                    if (value === 'ean_extended') {
                        return [{
                            format: "ean_reader",
                            config: {
                                supplements: [
                                    'ean_5_reader', 'ean_2_reader'
                                ]
                            }
                        }];
                    }
                    console.log("value before format :" + value);
                    return [{
                        format: value + "_reader",
                        config: {}
                    }];
                }
            }
        },
        state: {
            inputStream: {
                type: "LiveStream",
                constraints: {
                    width: { min: 640 },
                    height: { min: 480 },
                    aspectRatio: { min: 1, max: 100 },
                    facingMode: "environment" // or user
                }
            },
            locator: {
                patchSize: "x-small",
                halfSample: false
            },
            numOfWorkers: 4,
            decoder: {
                readers: [
                    "code_128_reader",
                    "ean_reader",
                    "ean_8_reader",
                    "code_39_reader",
                    "code_39_vin_reader",
                    "codabar_reader",
                    "upc_reader",
                    "upc_e_reader",
                    "i2of5_reader"
                ]
            },
            locate: false,
            multiple: false
        },
        lastResult: null
    };

    //value =  App.querySelectedReaders() ;
    App.init();

    Quagga.onProcessed(function (result) {
        var drawingCtx = Quagga.canvas.ctx.overlay,
            drawingCanvas = Quagga.canvas.dom.overlay;

        if (result) {
            if (result.boxes) {
                drawingCtx.clearRect(0, 0, parseInt(drawingCanvas.getAttribute("width")), parseInt(drawingCanvas.getAttribute("height")));
                result.boxes.filter(function (box) {
                    return box !== result.box;
                }).forEach(function (box) {
                    Quagga.ImageDebug.drawPath(box, { x: 0, y: 1 }, drawingCtx, { color: "green", lineWidth: 2 });
                });
            }

            if (result.box) {
                Quagga.ImageDebug.drawPath(result.box, { x: 0, y: 1 }, drawingCtx, { color: "#00F", lineWidth: 2 });
            }

            if (result.codeResult && result.codeResult.code) {
                Quagga.ImageDebug.drawPath(result.line, { x: 'x', y: 'y' }, drawingCtx, { color: 'red', lineWidth: 3 });
            }
        }
    });

    Quagga.onDetected(function (result) {
        Quagga.stop();
        var code = result.codeResult.code;
        location.href = "../Cars.aspx?value=" + code;

        /*
        if (App.lastResult !== code) {
            App.lastResult = code;
            var $node = null, canvas = Quagga.canvas.dom.image;

            $node = $('<li><div class="thumbnail"><div class="imgWrapper"><img /></div><div class="caption"><h4 class="code"></h4></div></div></li>');
            $node.find("img").attr("src", canvas.toDataURL());
            $node.find("h4.code").html(code);
            $("#result_strip ul.thumbnails").prepend($node);
        }
        */
    });
});`
