### ISSUE TITLE
does not work for the new browser

### ISSUE THREAD

**Issue by flint002** [serratus/quaggaJS#84]
http://serratus.github.io/quaggaJS/examples/live_w_locator.html

i use chrome Version 47.0.2526.106 m and Firefox 43.0.1

**Comment by SwarShah** [comment]
I had the same issue but if you try it with HTTPS it should work.
https://serratus.github.io/quaggaJS/examples/live_w_locator.html

**Comment by yourwebmaker** [comment]
@flint002 , please change the issue's title for an appropriate one.

**Comment by flint002** [comment]
@SwarShah thank you  it worked ..but now i must  config SSL in local webserver

@yourwebmaker I dont understand .. but now working after upgrading Firefox 43.0.4
