### ISSUE TITLE
Replace navigator.getUserMedia by navigator.mediaDevices.getUserMedia

### ISSUE THREAD

**Issue by yourwebmaker** [serratus/quaggaJS#85]
Actually we're using ``navigator.getUserMedia`` which is a deprecated feature.

See: https://developer.mozilla.org/en/docs/Web/API/Navigator/getUserMedia 

See: https://github.com/serratus/quaggaJS/blob/master/src/camera_access.js#L14

**Comment by serratus** [comment]
Thanks for pointing that out. I was experimenting with the new interface a while back, and at the time it was not widely supported. I suppose now is a good time to switch over to the new API. I'll do it ASAP, but if you have time, a PR is very much appreciated.

**Comment by yourwebmaker** [comment]
I'm now cloning it and will take a look into the code in order check if I'm able to do this PR.

Thanks.

**Comment by serratus** [comment]
This was fixed along with #97
