### ISSUE TITLE
browser support

### ISSUE THREAD

**Issue by zackd** [serratus/quaggaJS#87]
Hi there! 

I've just been assessing browser support for quaggajs, and thought I'd share these very rough initial results.

NB. I'm focusing on mobile ATM, so I'm ONLY looking at support for passing a static image to decodeSingle via `input[type=file]`

required features:
- web workers: http://caniuse.com/#feat=webworkers
- canvas: http://caniuse.com/#feat=canvas
- typed arrays: http://caniuse.com/#feat=typedarrays
- blob URLs: http://caniuse.com/#feat=bloburls
- blob builder: http://caniuse.com/#feat=blobbuilder

supported browsers:
IE10+, IE Edge, IE Mobile 11+
Firefox (iOS, Android), 
Chrome (iOS, Android) 
Safari 6+, iOS Safari 6.1+
Android browser 46+ (Android 5+ WebView: Chromium 46)
Blackberry browser 10+
Opera mobile 33+

I'll probably have missed some things here, but should a useful starting point..

anyway, thanks for sharing this awesome lib :)

**Comment by serratus** [comment]
Thanks for sharing this. It might be very useful as part of the README. Could you open a PR which includes your findings? If you cannot find time to do it in the near future, I'll try to incorporate this myself. Thanks again!
